// 中药种子数据入库脚本(Phase 1)
// 用法: DATABASE_URL=... DIRECT_URL=... npx tsx scripts/seed-herbs-db.ts
// 幂等:已存在的分类/中药自动跳过;重复执行安全
import { PrismaClient } from "@prisma/client";

const db = new PrismaClient();

// 分类表:名称 → sortOrder(按教材章节)
const CATEGORIES: { name: string; sortOrder: number }[] = [
  { name: "解表药", sortOrder: 1 },
  { name: "清热药", sortOrder: 2 },
  { name: "泻下药", sortOrder: 3 },
  { name: "祛风湿药", sortOrder: 4 },
  { name: "化湿药", sortOrder: 5 },
  { name: "利水渗湿药", sortOrder: 6 },
  { name: "温里药", sortOrder: 7 },
  { name: "理气药", sortOrder: 8 },
  { name: "消食药", sortOrder: 9 },
  { name: "驱虫药", sortOrder: 10 },
  { name: "止血药", sortOrder: 11 },
  { name: "活血化瘀药", sortOrder: 12 },
  { name: "化痰止咳平喘药", sortOrder: 13 },
  { name: "安神药", sortOrder: 14 },
  { name: "平肝息风药", sortOrder: 15 },
  { name: "开窍药", sortOrder: 16 },
  { name: "补虚药", sortOrder: 17 },
  { name: "收涩药", sortOrder: 18 },
];

// 种子 26 味(公开标准整理,来源标注)
const SEED_HERBS: {
  id: string;
  name: string;
  category: string;
  property: string;
  meridian: string;
  functions: string;
  indications: string;
  level: string;
  mnemonic?: string;
  mnemonicExplanation?: string;
}[] = [
  { id: "h_mahuang", name: "麻黄", category: "解表药", property: "辛、微苦,温", meridian: "肺、膀胱", functions: "发汗解表,宣肺平喘,利水消肿", indications: "风寒感冒,咳嗽气喘,风水水肿", level: "一类", mnemonic: "麻黄辛温,发汗解表,宣肺平喘", mnemonicExplanation: "麻黄发汗力强,为发汗解表第一要药" },
  { id: "h_guizhi", name: "桂枝", category: "解表药", property: "辛、甘,温", meridian: "心、肺、膀胱", functions: "发汗解肌,温通经脉,助阳化气", indications: "风寒感冒,寒凝血滞诸痛,痰饮水肿", level: "一类", mnemonic: "桂枝辛温,解肌通脉", mnemonicExplanation: "桂枝善温通经脉,和营解肌" },
  { id: "h_baishao", name: "白芍", category: "补虚药", property: "苦、酸,微寒", meridian: "肝、脾", functions: "养血敛阴,柔肝止痛,平抑肝阳", indications: "血虚萎黄,肝阳上亢,腹痛拘挛", level: "一类", mnemonic: "白芍养血柔肝", mnemonicExplanation: "白芍养血敛阴,与桂枝配伍调和营卫" },
  { id: "h_shigao", name: "石膏", category: "清热药", property: "甘、辛,大寒", meridian: "肺、胃", functions: "生用清热泻火,除烦止渴;煅用收湿敛疮", indications: "气分实热证,肺热喘咳,胃火牙痛", level: "一类", mnemonic: "石膏大寒清气热", mnemonicExplanation: "石膏为清泻肺胃气分实热之要药" },
  { id: "h_zhimu", name: "知母", category: "清热药", property: "苦、甘,寒", meridian: "肺、胃、肾", functions: "清热泻火,滋阴润燥", indications: "热病烦渴,肺热燥咳,骨蒸潮热", level: "一类", mnemonic: "知母清润三经", mnemonicExplanation: "知母既清肺胃实热,又滋肾阴" },
  { id: "h_huangqin", name: "黄芩", category: "清热药", property: "苦,寒", meridian: "肺、胆、脾、大肠、小肠", functions: "清热燥湿,泻火解毒,止血,安胎", indications: "湿温暑湿,肺热咳嗽,血热吐衄,胎动不安", level: "一类", mnemonic: "黄芩燥湿安胎", mnemonicExplanation: "黄芩善清上焦肺热,兼能安胎" },
  { id: "h_huanglian", name: "黄连", category: "清热药", property: "苦,寒", meridian: "心、脾、胃、肝、胆、大肠", functions: "清热燥湿,泻火解毒", indications: "湿热痞满,呕吐吞酸,泻痢,心火亢盛", level: "一类", mnemonic: "黄连清心止痢", mnemonicExplanation: "黄连善清心经实火,为治湿热泻痢要药" },
  { id: "h_huangbai", name: "黄柏", category: "清热药", property: "苦,寒", meridian: "肾、膀胱、大肠", functions: "清热燥湿,泻火除蒸,解毒疗疮", indications: "湿热泻痢,黄疸尿赤,骨蒸劳热", level: "一类", mnemonic: "黄柏清下焦湿热", mnemonicExplanation: "黄柏善清下焦湿热,退虚热" },
  { id: "h_zhizi", name: "栀子", category: "清热药", property: "苦,寒", meridian: "心、肺、三焦", functions: "泻火除烦,清热利湿,凉血解毒", indications: "热病心烦,湿热黄疸,血热吐衄", level: "一类", mnemonic: "栀子泻火除烦", mnemonicExplanation: "栀子清三焦之火,尤善清心除烦" },
  { id: "h_dahuang", name: "大黄", category: "泻下药", property: "苦,寒", meridian: "脾、胃、大肠、肝、心包", functions: "泻下攻积,清热泻火,凉血解毒,逐瘀通经", indications: "积滞便秘,血热吐衄,瘀血经闭", level: "一类", mnemonic: "大黄攻积逐瘀", mnemonicExplanation: "大黄为泻下攻积要药,生用后下" },
  { id: "h_huoxiang", name: "藿香", category: "化湿药", property: "辛,微温", meridian: "脾、胃、肺", functions: "化湿醒脾,解暑发表,和中止呕", indications: "湿阻中焦,暑湿感冒,呕吐", level: "一类", mnemonic: "藿香化湿止呕", mnemonicExplanation: "藿香芳香化湿,为暑湿要药" },
  { id: "h_fuling", name: "茯苓", category: "利水渗湿药", property: "甘、淡,平", meridian: "心、肺、脾、肾", functions: "利水渗湿,健脾,宁心", indications: "水肿尿少,痰饮眩悸,脾虚食少,心神不安", level: "一类", mnemonic: "茯苓利水健脾", mnemonicExplanation: "茯苓甘淡利水,兼健脾宁心" },
  { id: "h_fuzi", name: "附子", category: "温里药", property: "辛、甘,大热,有毒", meridian: "心、肾、脾", functions: "回阳救逆,补火助阳,散寒止痛", indications: "亡阳虚脱,肢冷脉微,阳痿宫冷", level: "一类", mnemonic: "附子回阳救逆", mnemonicExplanation: "附子大热,为回阳救逆第一要药(有毒,先煎)" },
  { id: "h_ganjiang", name: "干姜", category: "温里药", property: "辛,热", meridian: "脾、胃、肾、心、肺", functions: "温中散寒,回阳通脉,温肺化饮", indications: "脘腹冷痛,亡阳证,寒饮喘咳", level: "一类", mnemonic: "干姜温中化饮", mnemonicExplanation: "干姜温中散寒,为温中主药" },
  { id: "h_chenpi", name: "陈皮", category: "理气药", property: "辛、苦,温", meridian: "脾、肺", functions: "理气健脾,燥湿化痰", indications: "脘腹胀满,食少吐泻,咳嗽痰多", level: "一类", mnemonic: "陈皮理气化痰", mnemonicExplanation: "陈皮理气燥湿,为治痰要药" },
  { id: "h_sanqi", name: "三七", category: "止血药", property: "甘、微苦,温", meridian: "肝、胃", functions: "散瘀止血,消肿定痛", indications: "咯血吐血,跌打损伤,瘀血肿痛", level: "一类", mnemonic: "三七化瘀止血", mnemonicExplanation: "三七止血不留瘀,化瘀不伤正" },
  { id: "h_chuanxiong", name: "川芎", category: "活血化瘀药", property: "辛,温", meridian: "肝、胆、心包", functions: "活血行气,祛风止痛", indications: "血瘀气滞痛证,头痛,风湿痹痛", level: "一类", mnemonic: "川芎行气活血", mnemonicExplanation: "川芎为血中气药,善治头痛" },
  { id: "h_danggui", name: "当归", category: "补虚药", property: "甘、辛,温", meridian: "肝、心、脾", functions: "补血活血,调经止痛,润肠通便", indications: "血虚萎黄,月经不调,虚寒腹痛,肠燥便秘", level: "一类", mnemonic: "当归补血调经", mnemonicExplanation: "当归为补血要药,兼活血止痛" },
  { id: "h_banxia", name: "半夏", category: "化痰止咳平喘药", property: "辛,温,有毒", meridian: "脾、胃、肺", functions: "燥湿化痰,降逆止呕,消痞散结", indications: "湿痰寒痰,呕吐,心下痞,梅核气", level: "一类", mnemonic: "半夏燥湿止呕", mnemonicExplanation: "半夏为燥湿化痰要药(有毒,姜制)" },
  { id: "h_kuandonghua", name: "款冬花", category: "化痰止咳平喘药", property: "辛、微苦,温", meridian: "肺", functions: "润肺下气,止咳化痰", indications: "新久咳嗽,喘咳痰多,劳嗽咳血", level: "二类", mnemonic: "款冬止咳", mnemonicExplanation: "款冬花为治咳要药,无论寒热虚实皆可配用" },
  { id: "h_suanzaoren", name: "酸枣仁", category: "安神药", property: "甘、酸,平", meridian: "心、肝、胆", functions: "养心补肝,宁心安神,敛汗,生津", indications: "虚烦不眠,惊悸多梦,体虚多汗", level: "一类", mnemonic: "枣仁养心安神", mnemonicExplanation: "酸枣仁为养心安神要药" },
  { id: "h_gouteng", name: "钩藤", category: "平肝息风药", property: "甘,凉", meridian: "肝、心包", functions: "清热平肝,息风定惊", indications: "肝阳上亢,头晕目眩,惊痫抽搐", level: "一类", mnemonic: "钩藤平肝息风", mnemonicExplanation: "钩藤清热息风,后下" },
  { id: "h_renshen", name: "人参", category: "补虚药", property: "甘、微苦,微温", meridian: "脾、肺、心、肾", functions: "大补元气,复脉固脱,补脾益肺,生津养血,安神益智", indications: "体虚欲脱,肢冷脉微,脾虚食少,肺虚喘咳", level: "一类", mnemonic: "人参大补元气", mnemonicExplanation: "人参为大补元气之要药" },
  { id: "h_huangqi", name: "黄芪", category: "补虚药", property: "甘,微温", meridian: "脾、肺", functions: "补气升阳,固表止汗,利水消肿,托毒生肌", indications: "气虚乏力,中气下陷,自汗,水肿,疮疡难溃", level: "一类", mnemonic: "黄芪补气升阳", mnemonicExplanation: "黄芪为补气要药,善升阳固表" },
  { id: "h_gancao", name: "甘草", category: "补虚药", property: "甘,平", meridian: "心、肺、脾、胃", functions: "补脾益气,清热解毒,祛痰止咳,缓急止痛,调和诸药", indications: "脾胃虚弱,咳嗽痰多,脘腹挛急疼痛,药食中毒", level: "一类", mnemonic: "甘草调和诸药", mnemonicExplanation: "甘草为调和诸药之使药(生用泻火,炙用补中)" },
  { id: "h_shanzhuyu", name: "山茱萸", category: "收涩药", property: "酸、涩,微温", meridian: "肝、肾", functions: "补益肝肾,收涩固脱", indications: "眩晕耳鸣,腰膝酸痛,阳痿遗精,大汗虚脱", level: "一类", mnemonic: "茱萸补肝涩脱", mnemonicExplanation: "山茱萸既补肝肾又敛汗固脱" },
  // ===== 数据扩充(2026-08 第二批,按 18 分类补齐常用药) =====
  { id: "h_zisu", name: "紫苏", category: "解表药", property: "辛,温", meridian: "肺、脾", functions: "解表散寒,行气和胃", indications: "风寒感冒,咳嗽呕恶,妊娠呕吐,鱼蟹中毒", level: "二类", mnemonic: "紫苏散寒行气", mnemonicExplanation: "紫苏发表散寒兼理气和中,解鱼蟹毒" },
  { id: "h_shengjiang", name: "生姜", category: "解表药", property: "辛,微温", meridian: "肺、脾、胃", functions: "解表散寒,温中止呕,化痰止咳", indications: "风寒感冒,胃寒呕吐,寒痰咳嗽,解半夏毒", level: "一类", mnemonic: "生姜温胃止呕", mnemonicExplanation: "生姜为呕家圣药,善温胃散寒止呕" },
  { id: "h_jingjie", name: "荆芥", category: "解表药", property: "辛,微温", meridian: "肺、肝", functions: "解表散风,透疹,消疮", indications: "感冒头痛,麻疹不透,风疹瘙痒,疮疡初起", level: "二类", mnemonic: "荆芥透疹散风", mnemonicExplanation: "荆芥轻扬透散,善透疹止痒" },
  { id: "h_fangfeng", name: "防风", category: "解表药", property: "辛、甘,微温", meridian: "膀胱、肝、脾", functions: "祛风解表,胜湿止痛,止痉", indications: "感冒头痛,风湿痹痛,风疹瘙痒,破伤风", level: "二类", mnemonic: "防风祛风圣药", mnemonicExplanation: "防风为风药中之润剂,祛风不伤津" },
  { id: "h_qianghuo", name: "羌活", category: "解表药", property: "辛、苦,温", meridian: "膀胱、肾", functions: "解表散寒,祛风胜湿,止痛", indications: "风寒感冒,头痛项强,风湿痹痛,肩背酸痛", level: "二类", mnemonic: "羌活胜湿止痛", mnemonicExplanation: "羌活善治上半身风寒湿痹与太阳头痛" },
  { id: "h_baizhi", name: "白芷", category: "解表药", property: "辛,温", meridian: "肺、胃、大肠", functions: "解表散寒,祛风止痛,通鼻窍,燥湿止带,消肿排脓", indications: "感冒头痛,眉棱骨痛,鼻塞鼻渊,带下,疮疡肿痛", level: "二类", mnemonic: "白芷通窍止痛", mnemonicExplanation: "白芷善通鼻窍,治阳明头痛与鼻渊要药" },
  { id: "h_bohe", name: "薄荷", category: "解表药", property: "辛,凉", meridian: "肺、肝", functions: "疏散风热,清利头目,利咽透疹,疏肝行气", indications: "风热感冒,头痛目赤,咽喉肿痛,麻疹不透,肝郁气滞", level: "一类", mnemonic: "薄荷疏风利咽", mnemonicExplanation: "薄荷轻清凉散,善清利头目咽喉(后下)" },
  { id: "h_sangye", name: "桑叶", category: "解表药", property: "甘、苦,寒", meridian: "肺、肝", functions: "疏散风热,清肺润燥,平肝明目,凉血止血", indications: "风热感冒,肺热燥咳,头晕头痛,目赤昏花", level: "二类", mnemonic: "桑叶清肺明目", mnemonicExplanation: "桑叶既疏风热又清肝明目,与菊花相须为用" },
  { id: "h_juhua", name: "菊花", category: "解表药", property: "甘、苦,微寒", meridian: "肺、肝", functions: "疏散风热,平肝明目,清热解毒", indications: "风热感冒,头痛眩晕,目赤肿痛,疮痈肿毒", level: "一类", mnemonic: "菊花平肝明目", mnemonicExplanation: "菊花善平肝明目,为治目疾常用药" },
  { id: "h_gegen", name: "葛根", category: "解表药", property: "甘、辛,凉", meridian: "脾、胃、肺", functions: "解肌退热,生津止渴,透疹,升阳止泻,通经活络", indications: "外感发热头痛,项背强痛,消渴,麻疹不透,热泻热痢", level: "二类", mnemonic: "葛根生津升阳", mnemonicExplanation: "葛根解肌生津,善治项背强痛与脾虚泄泻" },
  { id: "h_chaihu", name: "柴胡", category: "解表药", property: "辛、苦,微寒", meridian: "肝、胆、肺", functions: "疏散退热,疏肝解郁,升举阳气", indications: "感冒发热,寒热往来,肝郁气滞,气虚下陷", level: "一类", mnemonic: "柴胡疏肝退热", mnemonicExplanation: "柴胡为和解少阳、疏肝解郁要药" },
  { id: "h_jinyinhua", name: "金银花", category: "清热药", property: "甘,寒", meridian: "肺、心、胃", functions: "清热解毒,疏散风热", indications: "痈肿疔疮,喉痹丹毒,风热感冒,温病发热", level: "一类", mnemonic: "银花清热解毒", mnemonicExplanation: "金银花为清热解毒要药,善治一切痈肿疮毒" },
  { id: "h_lianqiao", name: "连翘", category: "清热药", property: "苦,微寒", meridian: "肺、心、小肠", functions: "清热解毒,消肿散结,疏散风热", indications: "痈疽瘰疬,乳痈丹毒,风热感冒,温病初起", level: "二类", mnemonic: "连翘疮家圣药", mnemonicExplanation: "连翘为疮家圣药,善散结消肿" },
  { id: "h_pugongying", name: "蒲公英", category: "清热药", property: "苦、甘,寒", meridian: "肝、胃", functions: "清热解毒,消肿散结,利尿通淋", indications: "疔疮肿毒,乳痈,瘰疬,目赤,热淋涩痛", level: "二类", mnemonic: "公英消痈通淋", mnemonicExplanation: "蒲公英善治乳痈,兼能利尿通淋" },
  { id: "h_banlangen", name: "板蓝根", category: "清热药", property: "苦,寒", meridian: "心、胃", functions: "清热解毒,凉血利咽", indications: "温疫时毒,发热咽痛,温毒发斑,痄腮", level: "二类", mnemonic: "板蓝凉血利咽", mnemonicExplanation: "板蓝根善治咽喉肿痛与温毒发斑" },
  { id: "h_shengdihuang", name: "生地黄", category: "清热药", property: "甘、苦,寒", meridian: "心、肝、肾", functions: "清热凉血,养阴生津", indications: "热入营血,温毒发斑,吐血衄血,热病伤阴", level: "一类", mnemonic: "生地凉血养阴", mnemonicExplanation: "生地为清热凉血要药,兼养阴生津" },
  { id: "h_xuanshen", name: "玄参", category: "清热药", property: "甘、苦、咸,微寒", meridian: "肺、胃、肾", functions: "清热凉血,滋阴降火,解毒散结", indications: "热入营血,咽喉肿痛,瘰疬痰核,阴虚火旺", level: "二类", mnemonic: "玄参降火散结", mnemonicExplanation: "玄参既清营血热又滋阴降火,善消瘰疬" },
  { id: "h_mudanpi", name: "牡丹皮", category: "清热药", property: "苦、辛,微寒", meridian: "心、肝、肾", functions: "清热凉血,活血化瘀", indications: "热入营血,温毒发斑,吐血衄血,经闭痛经,跌扑伤痛", level: "二类", mnemonic: "丹皮凉血活血", mnemonicExplanation: "牡丹皮凉血而不留瘀,活血而不妄行" },
  { id: "h_chishao", name: "赤芍", category: "清热药", property: "苦,微寒", meridian: "肝", functions: "清热凉血,散瘀止痛", indications: "温毒发斑,吐血衄血,目赤肿痛,肝郁胁痛,经闭痛经", level: "二类", mnemonic: "赤芍凉血散瘀", mnemonicExplanation: "赤芍善凉血活血,治瘀热互结诸证" },
  { id: "h_qinghao", name: "青蒿", category: "清热药", property: "苦、辛,寒", meridian: "肝、胆", functions: "清虚热,除骨蒸,解暑热,截疟", indications: "温邪伤阴,夜热早凉,骨蒸劳热,暑热烦渴,疟疾寒热", level: "二类", mnemonic: "青蒿退蒸截疟", mnemonicExplanation: "青蒿善清透虚热,为治疟要药(后下)" },
  { id: "h_digupi", name: "地骨皮", category: "清热药", property: "甘,寒", meridian: "肺、肝、肾", functions: "凉血除蒸,清肺降火", indications: "阴虚潮热,骨蒸盗汗,肺热咳嗽,血热妄行", level: "二类", mnemonic: "地骨清肺退蒸", mnemonicExplanation: "地骨皮善退虚热骨蒸,又清肺降火" },
  { id: "h_xiakucao", name: "夏枯草", category: "清热药", property: "辛、苦,寒", meridian: "肝、胆", functions: "清肝泻火,明目,散结消肿", indications: "目赤肿痛,头痛眩晕,瘰疬瘿瘤,乳痈肿痛", level: "二类", mnemonic: "夏枯清肝散结", mnemonicExplanation: "夏枯草善清肝火,为治瘰疬瘿瘤要药" },
  { id: "h_mangxiao", name: "芒硝", category: "泻下药", property: "咸、苦,寒", meridian: "胃、大肠", functions: "泻下通便,润燥软坚,清火消肿", indications: "实热积滞,大便燥结,痈肿疮毒,目赤咽痛", level: "二类", mnemonic: "芒硝软坚通便", mnemonicExplanation: "芒硝咸寒软坚,善治燥结便秘(冲服)" },
  { id: "h_huomaren", name: "火麻仁", category: "泻下药", property: "甘,平", meridian: "脾、胃、大肠", functions: "润肠通便", indications: "血虚津亏,肠燥便秘", level: "二类", mnemonic: "麻仁润肠通便", mnemonicExplanation: "火麻仁质润多脂,为润肠通便之缓下药" },
  { id: "h_duhuo", name: "独活", category: "祛风湿药", property: "辛、苦,微温", meridian: "肾、膀胱", functions: "祛风除湿,通痹止痛", indications: "风寒湿痹,腰膝疼痛,少阴伏风头痛", level: "二类", mnemonic: "独活下部痹痛", mnemonicExplanation: "独活善祛下半身风寒湿邪,治腰膝痹痛" },
  { id: "h_weilingxian", name: "威灵仙", category: "祛风湿药", property: "辛、咸,温", meridian: "膀胱", functions: "祛风湿,通经络,止痛,消骨鲠", indications: "风湿痹痛,肢体麻木,筋脉拘挛,骨鲠咽喉", level: "二类", mnemonic: "灵仙通络止痛", mnemonicExplanation: "威灵仙善通十二经络,为治风湿痹痛要药" },
  { id: "h_qinjiao", name: "秦艽", category: "祛风湿药", property: "辛、苦,平", meridian: "胃、肝、胆", functions: "祛风湿,清湿热,止痹痛,退虚热", indications: "风湿痹痛,筋脉拘挛,骨蒸潮热,湿热黄疸", level: "二类", mnemonic: "秦艽祛风退蒸", mnemonicExplanation: "秦艽性平不燥,痹证寒热皆宜,兼退虚热" },
  { id: "h_sangjisheng", name: "桑寄生", category: "祛风湿药", property: "苦、甘,平", meridian: "肝、肾", functions: "祛风湿,补肝肾,强筋骨,安胎", indications: "风湿痹痛,腰膝酸软,胎动不安,崩漏经多", level: "二类", mnemonic: "寄生强骨安胎", mnemonicExplanation: "桑寄生祛风湿而兼补肝肾,为安胎要药" },
  { id: "h_peilan", name: "佩兰", category: "化湿药", property: "辛,平", meridian: "脾、胃、肺", functions: "芳香化湿,醒脾开胃,发表解暑", indications: "湿浊中阻,脘痞呕恶,口中甜腻,暑湿表证", level: "二类", mnemonic: "佩兰醒脾化湿", mnemonicExplanation: "佩兰善化湿醒脾,为治脾瘅口甜要药" },
  { id: "h_houpo", name: "厚朴", category: "化湿药", property: "苦、辛,温", meridian: "脾、胃、肺、大肠", functions: "燥湿消痰,下气除满", indications: "湿滞伤中,脘痞吐泻,食积气滞,痰饮喘咳", level: "二类", mnemonic: "厚朴下气除满", mnemonicExplanation: "厚朴善除胃肠气滞之胀满,兼能平喘" },
  { id: "h_sharen", name: "砂仁", category: "化湿药", property: "辛,温", meridian: "脾、胃", functions: "化湿开胃,温脾止泻,理气安胎", indications: "湿浊中阻,脘痞不饥,脾胃虚寒吐泻,妊娠恶阻", level: "二类", mnemonic: "砂仁化湿安胎", mnemonicExplanation: "砂仁芳香化湿行气,为安胎常用药(后下)" },
  { id: "h_zhuling", name: "猪苓", category: "利水渗湿药", property: "甘、淡,平", meridian: "肾、膀胱", functions: "利水渗湿", indications: "小便不利,水肿胀满,泄泻,淋浊带下", level: "二类", mnemonic: "猪苓利水渗湿", mnemonicExplanation: "猪苓利水之力强于茯苓,为利水要药" },
  { id: "h_zexie", name: "泽泻", category: "利水渗湿药", property: "甘,寒", meridian: "肾、膀胱", functions: "利水渗湿,泄热,化浊降脂", indications: "小便不利,水肿胀满,泄泻尿少,痰饮眩晕,高脂血症", level: "二类", mnemonic: "泽泻渗湿泄热", mnemonicExplanation: "泽泻利水而兼泄肾经虚火" },
  { id: "h_yiyiren", name: "薏苡仁", category: "利水渗湿药", property: "甘、淡,凉", meridian: "脾、胃、肺", functions: "利水渗湿,健脾止泻,除痹,排脓,解毒散结", indications: "水肿脚气,脾虚泄泻,湿痹拘挛,肺痈肠痈,赘疣", level: "二类", mnemonic: "薏米健脾除痹", mnemonicExplanation: "薏苡仁利水健脾而不伤正,兼除湿痹" },
  { id: "h_cheqianzi", name: "车前子", category: "利水渗湿药", property: "甘,微寒", meridian: "肝、肾、肺、小肠", functions: "清热利尿通淋,渗湿止泻,明目,祛痰", indications: "热淋涩痛,水肿胀满,暑湿泄泻,目赤肿痛,痰热咳嗽", level: "二类", mnemonic: "车前通淋明目", mnemonicExplanation: "车前子善清膀胱湿热,兼明目祛痰(包煎)" },
  { id: "h_jinqiancao", name: "金钱草", category: "利水渗湿药", property: "甘、咸,微寒", meridian: "肝、胆、肾、膀胱", functions: "利湿退黄,利尿通淋,解毒消肿", indications: "湿热黄疸,胆胀胁痛,石淋热淋,痈肿疔疮", level: "二类", mnemonic: "金钱排石退黄", mnemonicExplanation: "金钱草为治石淋要药,善利湿退黄" },
  { id: "h_yinchen", name: "茵陈", category: "利水渗湿药", property: "苦、辛,微寒", meridian: "脾、胃、肝、胆", functions: "清利湿热,利胆退黄", indications: "黄疸尿少,湿温暑湿,湿疮瘙痒", level: "二类", mnemonic: "茵陈退黄要药", mnemonicExplanation: "茵陈为治黄疸之要药,无论阳黄阴黄皆可用" },
  { id: "h_rougui", name: "肉桂", category: "温里药", property: "辛、甘,大热", meridian: "肾、脾、心、肝", functions: "补火助阳,散寒止痛,温通经脉,引火归元", indications: "命门火衰,肢冷脉微,脘腹冷痛,经闭痛经,虚阳上浮", level: "二类", mnemonic: "肉桂补火助阳", mnemonicExplanation: "肉桂善补命门之火,引火归元(后下)" },
  { id: "h_wuzhuyu", name: "吴茱萸", category: "温里药", property: "辛、苦,热", meridian: "肝、肾、脾、胃", functions: "散寒止痛,降逆止呕,助阳止泻", indications: "厥阴头痛,寒疝腹痛,呕吐吞酸,五更泄泻", level: "二类", mnemonic: "茱萸散寒止呕", mnemonicExplanation: "吴茱萸善散肝经寒邪,治厥阴巅顶头痛" },
  { id: "h_dingxiang", name: "丁香", category: "温里药", property: "辛,温", meridian: "脾、胃、肾", functions: "温中降逆,散寒止痛,温肾助阳", indications: "脾胃虚寒,呃逆呕吐,脘腹冷痛,阳痿宫冷", level: "二类", mnemonic: "丁香温胃止呃", mnemonicExplanation: "丁香善降逆气,为治虚寒呃逆要药" },
  { id: "h_zhishi", name: "枳实", category: "理气药", property: "苦、辛、酸,微寒", meridian: "脾、胃", functions: "破气消积,化痰散痞", indications: "积滞内停,痞满胀痛,泻痢后重,大便不通,痰滞胸脘", level: "二类", mnemonic: "枳实破气消痞", mnemonicExplanation: "枳实破气力峻,善消痞除满" },
  { id: "h_muxiang", name: "木香", category: "理气药", property: "辛、苦,温", meridian: "脾、胃、大肠、胆、三焦", functions: "行气止痛,健脾消食", indications: "脘腹胀痛,泻痢后重,食积不消,不思饮食", level: "二类", mnemonic: "木香行气止痛", mnemonicExplanation: "木香为行气止痛要药,善调中焦气滞" },
  { id: "h_xiangfu", name: "香附", category: "理气药", property: "辛、微苦、微甘,平", meridian: "肝、脾、三焦", functions: "疏肝解郁,理气宽中,调经止痛", indications: "肝郁气滞,胸胁胀痛,疝气疼痛,月经不调,乳房胀痛", level: "二类", mnemonic: "香附气病总司", mnemonicExplanation: "香附为妇科调经之要药,善疏肝理气" },
  { id: "h_chenxiang", name: "沉香", category: "理气药", property: "辛、苦,微温", meridian: "脾、胃、肾", functions: "行气止痛,温中止呕,纳气平喘", indications: "胸腹胀闷疼痛,胃寒呕吐呃逆,肾虚气逆喘促", level: "二类", mnemonic: "沉香纳气平喘", mnemonicExplanation: "沉香善降逆气,纳肾气以平喘(后下)" },
  { id: "h_xiebai", name: "薤白", category: "理气药", property: "辛、苦,温", meridian: "心、肺、胃、大肠", functions: "通阳散结,行气导滞", indications: "胸痹心痛,脘腹痞满胀痛,泻痢后重", level: "二类", mnemonic: "薤白通阳宽胸", mnemonicExplanation: "薤白善通胸阳,为治胸痹要药" },
  { id: "h_shanzha", name: "山楂", category: "消食药", property: "酸、甘,微温", meridian: "脾、胃、肝", functions: "消食健胃,行气散瘀,化浊降脂", indications: "肉食积滞,胃脘胀满,泻痢腹痛,瘀血经闭,高脂血症", level: "一类", mnemonic: "山楂消肉化积", mnemonicExplanation: "山楂善消肉食积滞,兼能活血化瘀" },
  { id: "h_shenqu", name: "神曲", category: "消食药", property: "甘、辛,温", meridian: "脾、胃", functions: "消食和胃", indications: "饮食积滞,脘腹胀满,食少纳呆", level: "二类", mnemonic: "神曲消食和胃", mnemonicExplanation: "神曲善消面食积滞,兼能解表退乳" },
  { id: "h_maiya", name: "麦芽", category: "消食药", property: "甘,平", meridian: "脾、胃、肝", functions: "行气消食,健脾开胃,回乳消胀", indications: "食积不消,脘腹胀痛,脾虚食少,乳汁郁积,断乳", level: "二类", mnemonic: "麦芽消面回乳", mnemonicExplanation: "麦芽善消米面薯芋食积,大量用回乳" },
  { id: "h_jineijin", name: "鸡内金", category: "消食药", property: "甘,平", meridian: "脾、胃、小肠、膀胱", functions: "健胃消食,涩精止遗,通淋化石", indications: "食积不化,消化不良,小儿疳积,遗尿遗精,石淋涩痛", level: "二类", mnemonic: "鸡内金化石消积", mnemonicExplanation: "鸡内金消食力强,兼能化石通淋" },
  { id: "h_shijunzi", name: "使君子", category: "驱虫药", property: "甘,温", meridian: "脾、胃", functions: "杀虫消积", indications: "蛔虫病,蛲虫病,虫积腹痛,小儿疳积", level: "二类", mnemonic: "使君驱蛔消疳", mnemonicExplanation: "使君子为驱蛔要药,味甘小儿喜服(忌热茶)" },
  { id: "h_binglang", name: "槟榔", category: "驱虫药", property: "苦、辛,温", meridian: "胃、大肠", functions: "杀虫,消积,行气,利水,截疟", indications: "绦虫蛔虫等虫积腹痛,食积气滞,水肿脚气,疟疾", level: "二类", mnemonic: "槟榔驱绦消积", mnemonicExplanation: "槟榔善驱绦虫,兼行气利水" },
  { id: "h_baimaogen", name: "白茅根", category: "止血药", property: "甘,寒", meridian: "肺、胃、膀胱", functions: "凉血止血,清热利尿", indications: "血热吐血衄血,尿血血淋,热病烦渴,热淋涩痛", level: "二类", mnemonic: "茅根凉血利尿", mnemonicExplanation: "白茅根凉血止血而兼利尿,为治尿血要药" },
  { id: "h_diyu", name: "地榆", category: "止血药", property: "苦、酸、涩,微寒", meridian: "肝、大肠", functions: "凉血止血,解毒敛疮", indications: "便血痔血,血痢崩漏,水火烫伤,痈肿疮毒", level: "二类", mnemonic: "地榆凉血敛疮", mnemonicExplanation: "地榆善治下焦血热出血,外敷治烫伤" },
  { id: "h_baiji", name: "白及", category: "止血药", property: "苦、甘、涩,微寒", meridian: "肺、胃、肝", functions: "收敛止血,消肿生肌", indications: "咯血吐血,外伤出血,疮疡肿毒,皮肤皲裂", level: "二类", mnemonic: "白及敛肺止血", mnemonicExplanation: "白及收敛止血力强,善治肺胃出血(畏乌头)" },
  { id: "h_aiye", name: "艾叶", category: "止血药", property: "辛、苦,温", meridian: "肝、脾、肾", functions: "温经止血,散寒止痛,调经安胎", indications: "虚寒性吐血衄血,崩漏下血,少腹冷痛,经寒不调,胎动不安", level: "二类", mnemonic: "艾叶温经安胎", mnemonicExplanation: "艾叶善温经止血,为妇科安胎要药,灸治常用" },
  { id: "h_daji", name: "大蓟", category: "止血药", property: "甘、苦,凉", meridian: "心、肝", functions: "凉血止血,散瘀解毒消痈", indications: "衄血吐血,尿血便血,崩漏,外伤出血,痈肿疮毒", level: "二类", mnemonic: "大蓟凉血散瘀", mnemonicExplanation: "大蓟凉血止血兼散瘀消痈,止血不留瘀" },
  { id: "h_danshen", name: "丹参", category: "活血化瘀药", property: "苦,微寒", meridian: "心、肝", functions: "活血祛瘀,通经止痛,清心除烦,凉血消痈", indications: "胸痹心痛,脘腹胁痛,癥瘕积聚,月经不调,心烦不眠", level: "一类", mnemonic: "丹参祛瘀生新", mnemonicExplanation: "丹参为活血化瘀要药,兼清心除烦" },
  { id: "h_taoren", name: "桃仁", category: "活血化瘀药", property: "苦、甘,平", meridian: "心、肝、大肠", functions: "活血祛瘀,润肠通便,止咳平喘", indications: "经闭痛经,癥瘕痞块,跌打损伤,肠燥便秘,咳嗽气喘", level: "二类", mnemonic: "桃仁祛瘀通便", mnemonicExplanation: "桃仁活血力缓兼润肠,为活血化瘀常用药" },
  { id: "h_honghua", name: "红花", category: "活血化瘀药", property: "辛,温", meridian: "心、肝", functions: "活血通经,散瘀止痛", indications: "经闭痛经,恶露不行,癥瘕痞块,跌打损伤,疮疡肿痛", level: "一类", mnemonic: "红花活血通经", mnemonicExplanation: "红花为活血通经要药,少用活血多用破血" },
  { id: "h_yanhusuo", name: "延胡索", category: "活血化瘀药", property: "辛、苦,温", meridian: "肝、脾", functions: "活血,行气,止痛", indications: "气血瘀滞诸痛证,胸痹心痛,脘腹疼痛,跌扑伤痛", level: "二类", mnemonic: "元胡行气止痛", mnemonicExplanation: "延胡索行血中气滞,为止痛要药(醋制增效)" },
  { id: "h_yimucao", name: "益母草", category: "活血化瘀药", property: "苦、辛,微寒", meridian: "肝、心包、膀胱", functions: "活血调经,利尿消肿,清热解毒", indications: "月经不调,痛经经闭,恶露不尽,水肿尿少,疮疡肿毒", level: "二类", mnemonic: "益母调经利水", mnemonicExplanation: "益母草为妇科经产要药,兼利水消肿" },
  { id: "h_niuxi", name: "牛膝", category: "活血化瘀药", property: "苦、甘、酸,平", meridian: "肝、肾", functions: "逐瘀通经,补肝肾,强筋骨,利尿通淋,引血下行", indications: "经闭痛经,腰膝酸痛,筋骨无力,淋证水肿,头痛眩晕", level: "二类", mnemonic: "牛膝引血下行", mnemonicExplanation: "牛膝善引血引火下行,又补肝肾强筋骨(怀牛膝佳)" },
  { id: "h_ruxiang", name: "乳香", category: "活血化瘀药", property: "辛、苦,温", meridian: "心、肝、脾", functions: "活血行气止痛,消肿生肌", indications: "跌打损伤,疮疡肿痛,胸痹心痛,风湿痹痛", level: "二类", mnemonic: "乳香活血定痛", mnemonicExplanation: "乳香活血行气止痛,为伤科要药" },
  { id: "h_ezhu", name: "莪术", category: "活血化瘀药", property: "辛、苦,温", meridian: "肝、脾", functions: "行气破血,消积止痛", indications: "癥瘕痞块,瘀血经闭,胸痹心痛,食积脘腹胀痛", level: "二类", mnemonic: "莪术破血消癥", mnemonicExplanation: "莪术破血行气力峻,善消癥瘕积块" },
  { id: "h_jiegeng", name: "桔梗", category: "化痰止咳平喘药", property: "苦、辛,平", meridian: "肺", functions: "宣肺,利咽,祛痰,排脓", indications: "咳嗽痰多,胸闷不畅,咽痛音哑,肺痈吐脓", level: "二类", mnemonic: "桔梗宣肺利咽", mnemonicExplanation: "桔梗为肺经气分要药,善宣肺祛痰排脓" },
  { id: "h_chuanbeimu", name: "川贝母", category: "化痰止咳平喘药", property: "苦、甘,微寒", meridian: "肺、心", functions: "清热润肺,化痰止咳,散结消痈", indications: "肺热燥咳,干咳少痰,阴虚劳嗽,瘰疬乳痈", level: "一类", mnemonic: "川贝润肺散结", mnemonicExplanation: "川贝性润,善治肺虚燥咳(反乌头)" },
  { id: "h_zhebeimu", name: "浙贝母", category: "化痰止咳平喘药", property: "苦,寒", meridian: "肺、心", functions: "清热化痰止咳,解毒散结消痈", indications: "风热咳嗽,痰火咳嗽,瘰疬瘿瘤,痈疮肿毒", level: "二类", mnemonic: "浙贝清热散结", mnemonicExplanation: "浙贝苦寒开泄,善治外感痰热与瘰疬(反乌头)" },
  { id: "h_gualou", name: "瓜蒌", category: "化痰止咳平喘药", property: "甘、微苦,寒", meridian: "肺、胃、大肠", functions: "清热涤痰,宽胸散结,润燥滑肠", indications: "肺热咳嗽,痰浊黄稠,胸痹心痛,结胸痞满,肠燥便秘", level: "二类", mnemonic: "瓜蒌宽胸涤痰", mnemonicExplanation: "瓜蒌善涤痰宽胸,为治胸痹要药(反乌头)" },
  { id: "h_zhuru", name: "竹茹", category: "化痰止咳平喘药", property: "甘,微寒", meridian: "肺、胃、心", functions: "清热化痰,除烦止呕", indications: "痰热咳嗽,胆火挟痰,烦热呕吐,胎动不安", level: "二类", mnemonic: "竹茹清热止呕", mnemonicExplanation: "竹茹善清胃热止呕,为治胃热呕吐要药" },
  { id: "h_kuxingren", name: "苦杏仁", category: "化痰止咳平喘药", property: "苦,微温,有毒", meridian: "肺、大肠", functions: "降气止咳平喘,润肠通便", indications: "咳嗽气喘,胸满痰多,肠燥便秘", level: "一类", mnemonic: "杏仁降气平喘", mnemonicExplanation: "苦杏仁善降肺气止咳喘,兼润肠(有毒,用量宜慎)" },
  { id: "h_zisuzi", name: "紫苏子", category: "化痰止咳平喘药", property: "辛,温", meridian: "肺、大肠", functions: "降气化痰,止咳平喘,润肠通便", indications: "痰壅气逆,咳嗽气喘,肠燥便秘", level: "二类", mnemonic: "苏子降气化痰", mnemonicExplanation: "紫苏子善降肺气化痰,为治喘咳要药" },
  { id: "h_baibu", name: "百部", category: "化痰止咳平喘药", property: "甘、苦,微温", meridian: "肺", functions: "润肺下气止咳,杀虫灭虱", indications: "新久咳嗽,肺痨咳嗽,百日咳,蛲虫,头虱", level: "二类", mnemonic: "百部润肺止咳", mnemonicExplanation: "百部甘润苦降,治新久虚劳咳嗽皆宜" },
  { id: "h_sangbaipi", name: "桑白皮", category: "化痰止咳平喘药", property: "甘,寒", meridian: "肺", functions: "泻肺平喘,利水消肿", indications: "肺热喘咳,水饮停肺,胀满喘急,水肿小便不利", level: "二类", mnemonic: "桑皮泻肺利水", mnemonicExplanation: "桑白皮善泻肺中水气而平喘,兼利水消肿" },
  { id: "h_yuanzhi", name: "远志", category: "安神药", property: "苦、辛,温", meridian: "心、肾、肺", functions: "安神益智,祛痰开窍,消散痈肿", indications: "心肾不交,失眠多梦,健忘惊悸,咳嗽痰多,痈疽疮肿", level: "二类", mnemonic: "远志安神祛痰", mnemonicExplanation: "远志交通心肾以安神,兼祛痰开窍" },
  { id: "h_baiziren", name: "柏子仁", category: "安神药", property: "甘,平", meridian: "心、肾、大肠", functions: "养心安神,润肠通便,止汗", indications: "阴血不足,虚烦失眠,心悸怔忡,肠燥便秘,阴虚盗汗", level: "二类", mnemonic: "柏子养心安神", mnemonicExplanation: "柏子仁养心安神而兼润肠,为养心常用药" },
  { id: "h_longgu", name: "龙骨", category: "安神药", property: "甘、涩,平", meridian: "心、肝、肾", functions: "镇惊安神,平肝潜阳,收敛固涩", indications: "心神不宁,心悸失眠,惊痫癫狂,肝阳眩晕,滑脱诸证", level: "二类", mnemonic: "龙骨镇惊固涩", mnemonicExplanation: "龙骨生用镇惊潜阳,煅用收敛固涩(先煎)" },
  { id: "h_hehuanpi", name: "合欢皮", category: "安神药", property: "甘,平", meridian: "心、肝、肺", functions: "解郁安神,活血消肿", indications: "心神不宁,忿怒忧郁,烦躁失眠,跌扑伤痛,疮痈肿毒", level: "二类", mnemonic: "合欢解郁安神", mnemonicExplanation: "合欢皮善解郁安神,为悦心安神要药" },
  { id: "h_tianma", name: "天麻", category: "平肝息风药", property: "甘,平", meridian: "肝", functions: "息风止痉,平抑肝阳,祛风通络", indications: "肝风内动,惊痫抽搐,眩晕头痛,肢体麻木,风湿痹痛", level: "一类", mnemonic: "天麻平肝息风", mnemonicExplanation: "天麻为止眩晕要药,平肝息风而不燥" },
  { id: "h_shijueming", name: "石决明", category: "平肝息风药", property: "咸,寒", meridian: "肝", functions: "平肝潜阳,清肝明目", indications: "肝阳上亢,头晕目眩,目赤翳障,视物昏花", level: "二类", mnemonic: "石决明潜阳明目", mnemonicExplanation: "石决明为平肝潜阳、清肝明目要药(先煎)" },
  { id: "h_quanxie", name: "全蝎", category: "平肝息风药", property: "辛,平,有毒", meridian: "肝", functions: "息风镇痉,通络止痛,攻毒散结", indications: "小儿惊风,抽搐痉挛,中风口歪,半身不遂,风湿顽痹", level: "二类", mnemonic: "全蝎镇痉通络", mnemonicExplanation: "全蝎善息风止痉,为治痉挛抽搐要药(有毒)" },
  { id: "h_lingyangjiao", name: "羚羊角", category: "平肝息风药", property: "咸,寒", meridian: "肝、心", functions: "平肝息风,清肝明目,散血解毒", indications: "肝风内动,惊痫抽搐,肝阳头痛眩晕,温毒发斑", level: "二类", mnemonic: "羚角息风清热", mnemonicExplanation: "羚羊角为息风止痉要药,尤宜热极生风(磨粉冲服)" },
  { id: "h_dilong", name: "地龙", category: "平肝息风药", property: "咸,寒", meridian: "肝、脾、膀胱", functions: "清热定惊,通络,平喘,利尿", indications: "高热神昏,惊痫抽搐,关节痹痛,肺热喘咳,热结尿闭", level: "二类", mnemonic: "地龙清热通络", mnemonicExplanation: "地龙善清热息风通络,兼平喘利尿" },
  { id: "h_shichangpu", name: "石菖蒲", category: "开窍药", property: "辛、苦,温", meridian: "心、胃", functions: "开窍豁痰,醒神益智,化湿开胃", indications: "痰蒙清窍,神昏癫痫,健忘失眠,耳鸣耳聋,脘痞不饥", level: "二类", mnemonic: "菖蒲开窍益智", mnemonicExplanation: "石菖蒲善豁痰开窍醒神,兼化湿开胃" },
  { id: "h_bingpian", name: "冰片", category: "开窍药", property: "辛、苦,微寒", meridian: "心、脾、肺", functions: "开窍醒神,清热止痛", indications: "热病神昏,痉厥,中风痰厥,目赤口疮,咽喉肿痛", level: "二类", mnemonic: "冰片开窍止痛", mnemonicExplanation: "冰片辛香走窜,善开窍醒神(不入煎剂,研末用)" },
  { id: "h_shexiang", name: "麝香", category: "开窍药", property: "辛,温", meridian: "心、脾", functions: "开窍醒神,活血通经,消肿止痛", indications: "热病神昏,中风痰厥,经闭癥瘕,跌打损伤,疮疡肿毒", level: "二类", mnemonic: "麝香开窍醒神", mnemonicExplanation: "麝香为开窍醒神第一要药,兼活血通经(孕妇禁用)" },
  { id: "h_dangshen", name: "党参", category: "补虚药", property: "甘,平", meridian: "脾、肺", functions: "健脾益肺,养血生津", indications: "脾肺气虚,食少倦怠,咳嗽虚喘,气血不足,面色萎黄", level: "二类", mnemonic: "党参健脾益气", mnemonicExplanation: "党参补脾肺气之力似人参而力缓,为常用补气药" },
  { id: "h_baizhu", name: "白术", category: "补虚药", property: "苦、甘,温", meridian: "脾、胃", functions: "健脾益气,燥湿利水,止汗,安胎", indications: "脾虚食少,腹胀泄泻,痰饮眩悸,水肿,自汗,胎动不安", level: "一类", mnemonic: "白术健脾燥湿", mnemonicExplanation: "白术为补气健脾第一要药,善燥湿利水" },
  { id: "h_shanyao", name: "山药", category: "补虚药", property: "甘,平", meridian: "脾、肺、肾", functions: "补脾养胃,生津益肺,补肾涩精", indications: "脾虚食少,久泻不止,肺虚喘咳,肾虚遗精,带下尿频", level: "二类", mnemonic: "山药平补三脏", mnemonicExplanation: "山药甘平补脾肺肾,为平补三焦常用药" },
  { id: "h_dazao", name: "大枣", category: "补虚药", property: "甘,温", meridian: "脾、胃、心", functions: "补中益气,养血安神", indications: "脾虚食少,乏力便溏,妇人脏躁,营卫不和", level: "二类", mnemonic: "大枣补中养血", mnemonicExplanation: "大枣补中益气,养血安神,为调和营卫常用药" },
  { id: "h_shudihuang", name: "熟地黄", category: "补虚药", property: "甘,微温", meridian: "肝、肾", functions: "补血滋阴,益精填髓", indications: "血虚萎黄,心悸怔忡,月经不调,肝肾阴虚,腰膝酸软", level: "一类", mnemonic: "熟地补血填髓", mnemonicExplanation: "熟地黄为补血要药,善滋阴填精(滋腻碍胃)" },
  { id: "h_heshouwu", name: "何首乌", category: "补虚药", property: "苦、甘、涩,微温", meridian: "肝、肾", functions: "补肝肾,益精血,乌须发,强筋骨", indications: "血虚萎黄,眩晕耳鸣,须发早白,腰膝酸软,肠燥便秘", level: "二类", mnemonic: "首乌乌须益精", mnemonicExplanation: "制首乌补肝肾益精血,为乌须发要药" },
  { id: "h_ejiao", name: "阿胶", category: "补虚药", property: "甘,平", meridian: "肺、肝、肾", functions: "补血滋阴,润燥,止血", indications: "血虚萎黄,眩晕心悸,肌痿无力,吐血衄血,便血崩漏", level: "二类", mnemonic: "阿胶补血润燥", mnemonicExplanation: "阿胶为补血要药,兼滋阴润燥止血(烊化服)" },
  { id: "h_maidong", name: "麦冬", category: "补虚药", property: "甘、微苦,微寒", meridian: "心、肺、胃", functions: "养阴生津,润肺清心", indications: "肺燥干咳,阴虚劳嗽,喉痹咽痛,津伤口渴,心烦失眠", level: "一类", mnemonic: "麦冬养阴润肺", mnemonicExplanation: "麦冬善养肺胃心三经之阴,为滋阴要药" },
  { id: "h_gouqizi", name: "枸杞子", category: "补虚药", property: "甘,平", meridian: "肝、肾", functions: "滋补肝肾,益精明目", indications: "虚劳精亏,腰膝酸痛,眩晕耳鸣,内热消渴,目昏不明", level: "一类", mnemonic: "枸杞滋补明目", mnemonicExplanation: "枸杞子平补肝肾精血,为明目常用药" },
  { id: "h_duzhong", name: "杜仲", category: "补虚药", property: "甘,温", meridian: "肝、肾", functions: "补肝肾,强筋骨,安胎", indications: "腰膝酸软,筋骨无力,头晕目眩,妊娠漏血,胎动不安", level: "二类", mnemonic: "杜仲强骨安胎", mnemonicExplanation: "杜仲补肝肾强腰膝,为安胎要药" },
  { id: "h_xuduan", name: "续断", category: "补虚药", property: "苦、辛,微温", meridian: "肝、肾", functions: "补肝肾,强筋骨,续折伤,止崩漏", indications: "腰膝酸软,风湿痹痛,跌扑损伤,筋伤骨折,崩漏胎漏", level: "二类", mnemonic: "续断接骨安胎", mnemonicExplanation: "续断善续筋接骨,兼补肝肾安胎" },
  { id: "h_yinyanghuo", name: "淫羊藿", category: "补虚药", property: "辛、甘,温", meridian: "肝、肾", functions: "补肾壮阳,祛风除湿", indications: "肾阳不足,阳痿遗精,腰膝冷痛,风湿痹痛,筋骨痿软", level: "二类", mnemonic: "淫羊藿壮阳", mnemonicExplanation: "淫羊藿补肾壮阳而兼祛风湿,为壮阳要药" },
  { id: "h_wuweizi", name: "五味子", category: "收涩药", property: "酸、甘,温", meridian: "肺、心、肾", functions: "收敛固涩,益气生津,补肾宁心", indications: "久嗽虚喘,梦遗滑精,遗尿尿频,久泻不止,自汗盗汗", level: "二类", mnemonic: "五味敛肺滋肾", mnemonicExplanation: "五味子五味俱全以酸为主,善敛肺滋肾止汗" },
  { id: "h_wumei", name: "乌梅", category: "收涩药", property: "酸、涩,平", meridian: "肝、脾、肺、大肠", functions: "敛肺,涩肠,生津,安蛔", indications: "肺虚久咳,久泻久痢,虚热消渴,蛔厥呕吐腹痛", level: "二类", mnemonic: "乌梅敛肺安蛔", mnemonicExplanation: "乌梅酸涩收敛,善敛肺涩肠,安蛔止痛" },
  { id: "h_roudoukou", name: "肉豆蔻", category: "收涩药", property: "辛,温", meridian: "脾、胃、大肠", functions: "温中行气,涩肠止泻", indications: "脾胃虚寒,久泻不止,脘腹胀痛,食少呕吐", level: "二类", mnemonic: "肉蔻涩肠止泻", mnemonicExplanation: "肉豆蔻温中涩肠,治虚寒久泻要药(煨用)" },
  { id: "h_lianzi", name: "莲子", category: "收涩药", property: "甘、涩,平", meridian: "脾、肾、心", functions: "补脾止泻,止带,益肾涩精,养心安神", indications: "脾虚泄泻,带下,遗精滑精,虚烦失眠", level: "二类", mnemonic: "莲子补脾涩精", mnemonicExplanation: "莲子平补脾肾,涩精止泻兼养心安神" },
  { id: "h_jinyingzi", name: "金樱子", category: "收涩药", property: "酸、甘、涩,平", meridian: "肾、膀胱、大肠", functions: "固精缩尿,固崩止带,涩肠止泻", indications: "遗精滑精,遗尿尿频,崩漏带下,久泻久痢", level: "二类", mnemonic: "金樱固精缩尿", mnemonicExplanation: "金樱子酸涩收敛,善固精缩尿止带" },
  // ===== 第三批扩充(2026-08,目标 300+ 味) =====
  { id: "h_xiangru", name: "香薷", category: "解表药", property: "辛,微温", meridian: "肺、脾、胃", functions: "发汗解表,化湿和中,利水消肿", indications: "暑湿感冒,恶寒发热,头痛无汗,腹痛吐泻,水肿小便不利", level: "二类", mnemonic: "香薷夏月麻黄", mnemonicExplanation: "香薷发汗解表兼化湿,为治阴暑要药" },
  { id: "h_gaoben", name: "藁本", category: "解表药", property: "辛,温", meridian: "膀胱", functions: "祛风散寒,除湿止痛", indications: "风寒感冒,巅顶头痛,风寒湿痹,肢节疼痛", level: "二类", mnemonic: "藁本巅顶止痛", mnemonicExplanation: "藁本善达巅顶,为治太阳巅顶头痛要药" },
  { id: "h_xixin", name: "细辛", category: "解表药", property: "辛,温,有小毒", meridian: "肺、肾、心", functions: "解表散寒,祛风止痛,通窍,温肺化饮", indications: "风寒感冒,头痛牙痛,鼻塞鼻渊,痰饮喘咳", level: "一类", mnemonic: "细辛通窍止痛", mnemonicExplanation: "细辛辛温走窜,善止诸痛、通鼻窍(不过钱)" },
  { id: "h_cangerzi", name: "苍耳子", category: "解表药", property: "辛、苦,温,有毒", meridian: "肺", functions: "散风寒,通鼻窍,祛风湿", indications: "鼻渊头痛,风寒头痛,风湿痹痛,风疹瘙痒", level: "二类", mnemonic: "苍耳通鼻祛风", mnemonicExplanation: "苍耳子为治鼻渊要药,兼祛风湿(有毒,炒用)" },
  { id: "h_xinyi", name: "辛夷", category: "解表药", property: "辛,温", meridian: "肺、胃", functions: "散风寒,通鼻窍", indications: "风寒感冒,鼻塞流涕,鼻渊鼻鼽", level: "二类", mnemonic: "辛夷通鼻要药", mnemonicExplanation: "辛夷善通鼻窍,为治鼻渊鼻塞之专药(包煎)" },
  { id: "h_niubangzi", name: "牛蒡子", category: "解表药", property: "辛、苦,寒", meridian: "肺、胃", functions: "疏散风热,宣肺祛痰,利咽透疹,解毒消肿", indications: "风热感冒,咽喉肿痛,麻疹不透,痈肿疮毒,咳嗽痰多", level: "二类", mnemonic: "牛蒡利咽透疹", mnemonicExplanation: "牛蒡子善利咽透疹,兼能解毒消肿" },
  { id: "h_chantui", name: "蝉蜕", category: "解表药", property: "甘,寒", meridian: "肺、肝", functions: "疏散风热,利咽开音,透疹,明目退翳,息风止痉", indications: "风热感冒,咽痛音哑,麻疹不透,目赤翳障,小儿惊风", level: "二类", mnemonic: "蝉蜕开音退翳", mnemonicExplanation: "蝉蜕善利咽开音,为治失音要药" },
  { id: "h_manjingzi", name: "蔓荆子", category: "解表药", property: "辛、苦,微寒", meridian: "膀胱、肝、胃", functions: "疏散风热,清利头目", indications: "风热感冒,头昏头痛,目赤肿痛,耳鸣耳聋", level: "二类", mnemonic: "蔓荆清利头目", mnemonicExplanation: "蔓荆子善治风热头痛目赤" },
  { id: "h_shengma", name: "升麻", category: "解表药", property: "辛、微甘,微寒", meridian: "肺、脾、胃、大肠", functions: "发表透疹,清热解毒,升举阳气", indications: "风热头痛,麻疹不透,齿痛口疮,咽喉肿痛,中气下陷", level: "二类", mnemonic: "升麻升阳举陷", mnemonicExplanation: "升麻善升脾胃清阳,治气虚下陷诸证" },
  { id: "h_dandouchi", name: "淡豆豉", category: "解表药", property: "苦、辛,凉", meridian: "肺、胃", functions: "解表,除烦,宣发郁热", indications: "感冒头痛,寒热头痛,心烦懊憹,虚烦不眠", level: "二类", mnemonic: "豆豉解表除烦", mnemonicExplanation: "淡豆豉解表力缓,善宣郁除烦" },
  { id: "h_fuping", name: "浮萍", category: "解表药", property: "辛,寒", meridian: "肺、膀胱", functions: "宣散风热,透疹,利尿", indications: "风热感冒,麻疹不透,风疹瘙痒,水肿尿少", level: "二类", mnemonic: "浮萍透疹利水", mnemonicExplanation: "浮萍轻浮升散,善透疹而兼利水" },
  { id: "h_daqingye", name: "大青叶", category: "清热药", property: "苦,寒", meridian: "心、胃", functions: "清热解毒,凉血消斑", indications: "温病高热,神昏发斑,喉痹,丹毒,痈肿", level: "二类", mnemonic: "大青凉血消斑", mnemonicExplanation: "大青叶善清气血实热,凉血消斑" },
  { id: "h_qingdai", name: "青黛", category: "清热药", property: "咸,寒", meridian: "肝、肺", functions: "清热解毒,凉血消斑,泻火定惊", indications: "温毒发斑,吐血衄血,痄腮喉痹,小儿惊痫", level: "二类", mnemonic: "青黛凉血定惊", mnemonicExplanation: "青黛善清肝火,凉血消斑(冲服)" },
  { id: "h_zicao", name: "紫草", category: "清热药", property: "甘、咸,寒", meridian: "心、肝", functions: "清热凉血,活血解毒,透疹消斑", indications: "温毒发斑,血热毒盛,斑疹紫黑,麻疹不透,疮疡湿疹", level: "二类", mnemonic: "紫草凉血透疹", mnemonicExplanation: "紫草善凉血透疹,为治斑疹要药" },
  { id: "h_shuiniujiao", name: "水牛角", category: "清热药", property: "苦,寒", meridian: "心、肝", functions: "清热凉血,解毒,定惊", indications: "温病高热,神昏谵语,发斑发疹,吐血衄血,惊风癫狂", level: "二类", mnemonic: "水牛角凉血定惊", mnemonicExplanation: "水牛角为犀角代用品,善清心肝实热" },
  { id: "h_baiwei", name: "白薇", category: "清热药", property: "苦、咸,寒", meridian: "胃、肝、肾", functions: "清热凉血,利尿通淋,解毒疗疮", indications: "阴虚内热,骨蒸潮热,产后虚热,热淋血淋,疮痈肿毒", level: "二类", mnemonic: "白薇退虚热", mnemonicExplanation: "白薇善清虚热,兼利尿通淋" },
  { id: "h_yinchaihu", name: "银柴胡", category: "清热药", property: "甘,微寒", meridian: "肝、胃", functions: "退虚热,清疳热", indications: "阴虚发热,骨蒸劳热,小儿疳热,盗汗", level: "二类", mnemonic: "银柴胡退疳热", mnemonicExplanation: "银柴胡专退虚热疳热,无升散之弊" },
  { id: "h_huhuanglian", name: "胡黄连", category: "清热药", property: "苦,寒", meridian: "肝、胃、大肠", functions: "退虚热,除疳热,清湿热", indications: "骨蒸潮热,小儿疳热,湿热泻痢,痔疮肿痛", level: "二类", mnemonic: "胡连退蒸除疳", mnemonicExplanation: "胡黄连善退虚热,除疳热,清下焦湿热" },
  { id: "h_longdan", name: "龙胆", category: "清热药", property: "苦,寒", meridian: "肝、胆", functions: "清热燥湿,泻肝胆火", indications: "湿热黄疸,阴肿阴痒,带下,湿疹瘙痒,肝火头痛目赤", level: "二类", mnemonic: "龙胆泻肝燥湿", mnemonicExplanation: "龙胆善泻肝胆实火,清下焦湿热" },
  { id: "h_kushen", name: "苦参", category: "清热药", property: "苦,寒", meridian: "心、肝、胃、大肠、膀胱", functions: "清热燥湿,杀虫,利尿", indications: "热痢便血,黄疸尿闭,赤白带下,阴肿阴痒,湿疹疥癣", level: "二类", mnemonic: "苦参燥湿杀虫", mnemonicExplanation: "苦参清热燥湿而兼杀虫止痒,治皮肤病常用" },
  { id: "h_chuanxinlian", name: "穿心莲", category: "清热药", property: "苦,寒", meridian: "心、肺、大肠、膀胱", functions: "清热解毒,凉血消肿", indications: "感冒发热,咽喉肿痛,肺热咳嗽,湿热泻痢,热淋", level: "二类", mnemonic: "穿心莲清热解毒", mnemonicExplanation: "穿心莲善清肺胃湿热毒邪" },
  { id: "h_shandougen", name: "山豆根", category: "清热药", property: "苦,寒,有毒", meridian: "肺、胃", functions: "清热解毒,消肿利咽", indications: "火毒蕴结,咽喉肿痛,齿龈肿痛,肺热咳嗽", level: "二类", mnemonic: "山豆根治咽痛", mnemonicExplanation: "山豆根为治咽喉肿痛要药(有毒,用量宜慎)" },
  { id: "h_shegan", name: "射干", category: "清热药", property: "苦,寒", meridian: "肺", functions: "清热解毒,消痰利咽", indications: "咽喉肿痛,痰盛咳喘,痰涎壅盛", level: "二类", mnemonic: "射干利咽消痰", mnemonicExplanation: "射干善清肺利咽,兼降痰浊" },
  { id: "h_machixian", name: "马齿苋", category: "清热药", property: "酸,寒", meridian: "肝、大肠", functions: "清热解毒,凉血止血,止痢", indications: "热毒血痢,痈肿疔疮,便血痔血,崩漏下血", level: "二类", mnemonic: "马齿苋止痢", mnemonicExplanation: "马齿苋善治热毒血痢,兼凉血止血" },
  { id: "h_baitouweng", name: "白头翁", category: "清热药", property: "苦,寒", meridian: "胃、大肠", functions: "清热解毒,凉血止痢", indications: "热毒血痢,发热腹痛,下痢脓血,里急后重", level: "二类", mnemonic: "白头翁治痢要药", mnemonicExplanation: "白头翁为治热毒血痢之要药" },
  { id: "h_qinpi", name: "秦皮", category: "清热药", property: "苦、涩,寒", meridian: "肝、胆、大肠", functions: "清热燥湿,收涩止痢,明目", indications: "热痢泄泻,赤白带下,目赤肿痛,目生翳膜", level: "二类", mnemonic: "秦皮止痢明目", mnemonicExplanation: "秦皮清热涩肠止痢,兼清肝明目" },
  { id: "h_yuxingcao", name: "鱼腥草", category: "清热药", property: "辛,微寒", meridian: "肺", functions: "清热解毒,消痈排脓,利尿通淋", indications: "肺痈吐脓,痰热喘咳,热痢,热淋,痈肿疮毒", level: "二类", mnemonic: "鱼腥草治肺痈", mnemonicExplanation: "鱼腥草为治肺痈要药,善排脓消痈" },
  { id: "h_baijiangcao", name: "败酱草", category: "清热药", property: "辛、苦,微寒", meridian: "胃、大肠、肝", functions: "清热解毒,消痈排脓,祛瘀止痛", indications: "肠痈肺痈,痈肿疮毒,产后瘀阻腹痛", level: "二类", mnemonic: "败酱治肠痈", mnemonicExplanation: "败酱草为治肠痈要药,兼祛瘀止痛" },
  { id: "h_hongteng", name: "红藤", category: "清热药", property: "苦,平", meridian: "大肠、肝", functions: "清热解毒,活血止痛,祛风通络", indications: "肠痈腹痛,热毒疮疡,跌打损伤,风湿痹痛", level: "二类", mnemonic: "红藤治肠痈要药", mnemonicExplanation: "红藤善治肠痈,兼活血止痛" },
  { id: "h_baihuasheshecao", name: "白花蛇舌草", category: "清热药", property: "微苦、甘,寒", meridian: "胃、大肠、小肠", functions: "清热解毒,利湿通淋", indications: "痈肿疮毒,咽喉肿痛,毒蛇咬伤,热淋涩痛", level: "二类", mnemonic: "蛇舌草解毒通淋", mnemonicExplanation: "白花蛇舌草清热解毒力强,兼利湿通淋" },
  { id: "h_tufuling", name: "土茯苓", category: "清热药", property: "甘、淡,平", meridian: "肝、胃", functions: "解毒,除湿,通利关节", indications: "梅毒,筋骨疼痛,湿热淋浊,带下,痈肿疮毒", level: "二类", mnemonic: "土茯苓解毒除湿", mnemonicExplanation: "土茯苓善解梅毒及承中毒,兼除湿利关节" },
  { id: "h_taizishen", name: "太子参", category: "补虚药", property: "甘、微苦,平", meridian: "脾、肺", functions: "益气健脾,生津润肺", indications: "脾虚体倦,食欲不振,病后虚弱,气阴不足,自汗口渴", level: "二类", mnemonic: "太子参清补", mnemonicExplanation: "太子参益气养阴而不燥,为清补常用药" },
  { id: "h_huaihua", name: "槐花", category: "止血药", property: "苦,微寒", meridian: "肝、大肠", functions: "凉血止血,清肝泻火", indications: "便血痔血,血痢,崩漏,吐血衄血,肝热目赤头痛", level: "二类", mnemonic: "槐花清肠止血", mnemonicExplanation: "槐花善清大肠血热,为治便血痔血要药" },
  { id: "h_huaimi", name: "槐角", category: "止血药", property: "苦,寒", meridian: "肝、大肠", functions: "清热泻火,凉血止血", indications: "肠热便血,痔肿出血,肝热头痛眩晕", level: "二类", mnemonic: "槐角凉血润肠", mnemonicExplanation: "槐角功似槐花而力强,兼润肠" },
  { id: "h_zonglv", name: "棕榈炭", category: "止血药", property: "苦、涩,平", meridian: "肺、肝、大肠", functions: "收敛止血,止泻止带", indications: "吐血衄血,便血尿血,崩漏下血,久泻久痢,带下", level: "二类", mnemonic: "棕榈炭收敛止血", mnemonicExplanation: "棕榈炭苦涩收敛,为收敛止血之要药" },
  { id: "h_oujie", name: "藕节", category: "止血药", property: "甘、涩,平", meridian: "肝、肺、胃", functions: "收敛止血,化瘀", indications: "吐血衄血,咯血尿血,便血崩漏,外伤出血", level: "二类", mnemonic: "藕节止血不留瘀", mnemonicExplanation: "藕节收敛止血而兼化瘀,止血而不留瘀" },
  { id: "h_shengpuhuang", name: "蒲黄", category: "止血药", property: "甘,平", meridian: "肝、心包", functions: "止血,化瘀,通淋", indications: "吐血衄血,咯血,崩漏,外伤出血,经闭痛经,血淋涩痛", level: "二类", mnemonic: "蒲黄止血化瘀", mnemonicExplanation: "蒲黄生用化瘀,炒用止血,兼通淋(包煎)" },
  { id: "h_cebaiye", name: "侧柏叶", category: "止血药", property: "苦、涩,寒", meridian: "肺、肝、脾", functions: "凉血止血,化痰止咳,生发乌发", indications: "吐血衄血,咯血便血,崩漏下血,肺热咳嗽,血热脱发", level: "二类", mnemonic: "侧柏凉血止咳", mnemonicExplanation: "侧柏叶凉血止血兼化痰止咳,外用生发乌发" },
  { id: "h_qiancao", name: "茜草", category: "止血药", property: "苦,寒", meridian: "肝", functions: "凉血,祛瘀,止血,通经", indications: "吐血衄血,崩漏下血,外伤出血,经闭瘀阻,跌扑肿痛", level: "二类", mnemonic: "茜草凉血化瘀", mnemonicExplanation: "茜草凉血止血兼活血通经,为妇科调经要药" },
  { id: "h_xianhecao", name: "仙鹤草", category: "止血药", property: "苦、涩,平", meridian: "心、肝", functions: "收敛止血,截疟,止痢,解毒,补虚", indications: "各种出血证,疟疾,泻痢,疮疖痈肿,脱力劳伤", level: "二类", mnemonic: "仙鹤草收敛止血", mnemonicExplanation: "仙鹤草收敛止血,凡出血证皆可用之" },
  { id: "h_jicai", name: "荠菜", category: "止血药", property: "甘、淡,凉", meridian: "肝、胃", functions: "凉血止血,清热利尿,明目", indications: "吐血便血,崩漏尿血,水肿,目赤涩痛", level: "二类", mnemonic: "荠菜凉血明目", mnemonicExplanation: "荠菜凉血止血兼利水明目" },
  { id: "h_jianghuang", name: "姜黄", category: "活血化瘀药", property: "辛、苦,温", meridian: "脾、肝", functions: "破血行气,通经止痛", indications: "胸胁刺痛,经闭癥瘕,风湿肩臂疼痛,跌扑肿痛", level: "二类", mnemonic: "姜黄通经止痛", mnemonicExplanation: "姜黄善治肩臂痹痛与血瘀气滞诸痛" },
  { id: "h_sanleng", name: "三棱", category: "活血化瘀药", property: "辛、苦,平", meridian: "肝、脾", functions: "破血行气,消积止痛", indications: "癥瘕痞块,瘀血经闭,食积胀痛,跌扑伤痛", level: "二类", mnemonic: "三棱破血消积", mnemonicExplanation: "三棱破血之力峻猛,常与莪术相须为用" },
  { id: "h_wulingzhi", name: "五灵脂", category: "活血化瘀药", property: "苦、咸、甘,温", meridian: "肝、脾", functions: "活血止痛,化瘀止血", indications: "瘀血阻滞诸痛证,经闭痛经,胸痹心痛,产后瘀滞腹痛", level: "二类", mnemonic: "五灵脂止痛要药", mnemonicExplanation: "五灵脂为治血瘀诸痛要药(包煎,畏人参)" },
  { id: "h_shuizhi", name: "水蛭", category: "活血化瘀药", property: "咸、苦,平,有小毒", meridian: "肝", functions: "破血通经,逐瘀消癥", indications: "血瘀经闭,癥瘕积聚,跌扑损伤,中风偏瘫", level: "二类", mnemonic: "水蛭破血逐瘀", mnemonicExplanation: "水蛭破血逐瘀力峻,善消癥瘕积聚(研末吞服)" },
  { id: "h_mengchong", name: "虻虫", category: "活血化瘀药", property: "苦,微寒,有毒", meridian: "肝", functions: "破血逐瘀,散积消癥", indications: "癥瘕积聚,血瘀经闭,跌打损伤", level: "二类", mnemonic: "虻虫破血逐瘀", mnemonicExplanation: "虻虫破血之力峻猛,多用于瘀血重症" },
  { id: "h_zeqi", name: "泽兰", category: "活血化瘀药", property: "苦、辛,微温", meridian: "肝、脾", functions: "活血调经,祛瘀消痈,利水消肿", indications: "血瘀经闭,痛经,产后瘀滞腹痛,水肿腹水,跌打损伤", level: "二类", mnemonic: "泽兰调经利水", mnemonicExplanation: "泽兰活血调经而兼利水,为妇科要药" },
  { id: "h_wangbuliuxing", name: "王不留行", category: "活血化瘀药", property: "苦,平", meridian: "肝、胃", functions: "活血通经,下乳消肿,利尿通淋", indications: "经闭痛经,乳汁不下,乳痈肿痛,热淋血淋,石淋", level: "二类", mnemonic: "王不留行通乳", mnemonicExplanation: "王不留行善活血通经下乳,为治乳汁不下要药" },
  { id: "h_chongweizi", name: "茺蔚子", category: "活血化瘀药", property: "辛、苦,微寒", meridian: "心包、肝", functions: "活血调经,清肝明目", indications: "月经不调,经闭痛经,产后瘀滞腹痛,肝热头痛,目赤翳障", level: "二类", mnemonic: "茺蔚子调经明目", mnemonicExplanation: "茺蔚子(益母草子)活血调经兼清肝明目" },
  { id: "h_moyao", name: "没药", category: "活血化瘀药", property: "辛、苦,平", meridian: "心、肝、脾", functions: "散瘀定痛,消肿生肌", indications: "跌打损伤,疮疡肿痛,胸痹心痛,痛经经闭", level: "二类", mnemonic: "没药散瘀定痛", mnemonicExplanation: "没药活血止痛消肿生肌,常与乳香相须为用" },
  { id: "h_chuanjiao", name: "穿山甲", category: "活血化瘀药", property: "咸,微寒", meridian: "肝、胃", functions: "活血消癥,通经下乳,消肿排脓,搜风通络", indications: "癥瘕积聚,经闭,乳汁不通,痈肿疮毒,风湿痹痛", level: "二类", mnemonic: "穿山甲通经下乳", mnemonicExplanation: "穿山甲善走窜通络,为通经下乳要药(研末冲服)" },
  { id: "h_liujinu", name: "刘寄奴", category: "活血化瘀药", property: "苦,温", meridian: "心、肝、脾", functions: "散瘀止痛,疗伤止血,破血通经,消食化积", indications: "跌打损伤,瘀滞肿痛,经闭癥瘕,食积腹痛", level: "二类", mnemonic: "刘寄奴疗伤止痛", mnemonicExplanation: "刘寄奴为伤科要药,善散瘀疗伤止痛" },
  { id: "h_zhechong", name: "土鳖虫", category: "活血化瘀药", property: "咸,寒,有小毒", meridian: "肝", functions: "破血逐瘀,续筋接骨", indications: "跌打损伤,筋伤骨折,血瘀经闭,癥瘕痞块", level: "二类", mnemonic: "土鳖虫接骨要药", mnemonicExplanation: "土鳖虫为伤科接骨要药,兼破血逐瘀" },
  { id: "h_zirantong", name: "自然铜", category: "活血化瘀药", property: "辛,平", meridian: "肝", functions: "散瘀止痛,接骨疗伤", indications: "跌打损伤,筋骨折伤,瘀肿疼痛", level: "二类", mnemonic: "自然铜接骨", mnemonicExplanation: "自然铜为接骨疗伤要药(煅用)" },
  { id: "h_xuejie", name: "血竭", category: "活血化瘀药", property: "甘、咸,平", meridian: "心、肝", functions: "活血定痛,化瘀止血,生肌敛疮", indications: "跌打损伤,心腹瘀痛,外伤出血,疮疡不敛", level: "二类", mnemonic: "血竭定痛敛疮", mnemonicExplanation: "血竭内服活血定痛,外用生肌敛疮(研末冲服)" },
  { id: "h_baijiangcan", name: "白僵蚕", category: "平肝息风药", property: "咸、辛,平", meridian: "肝、肺、胃", functions: "息风止痉,祛风止痛,化痰散结", indications: "肝风夹痰,惊痫抽搐,风热头痛,目赤咽痛,瘰疬痰核", level: "二类", mnemonic: "僵蚕息风散结", mnemonicExplanation: "僵蚕息风止痉兼化痰散结,治风痰为患" },
  { id: "h_jiangcan", name: "天南星", category: "化痰止咳平喘药", property: "苦、辛,温,有毒", meridian: "肺、肝、脾", functions: "燥湿化痰,祛风止痉,散结消肿", indications: "湿痰寒痰,风痰眩晕,中风痰壅,癫痫惊风,痈肿蛇伤", level: "二类", mnemonic: "南星燥湿祛风", mnemonicExplanation: "天南星善祛经络风痰,为治风痰要药(制用)" },
  { id: "h_baifuzi", name: "白附子", category: "化痰止咳平喘药", property: "辛,温,有毒", meridian: "胃、肝", functions: "祛风痰,定惊搐,解毒散结止痛", indications: "中风痰壅,口眼歪斜,惊风癫痫,破伤风,瘰疬痰核", level: "二类", mnemonic: "白附子祛风痰", mnemonicExplanation: "白附子善祛头面风痰,治口眼歪斜(制用)" },
  { id: "h_qianhu", name: "前胡", category: "化痰止咳平喘药", property: "苦、辛,微寒", meridian: "肺", functions: "降气化痰,散风清热", indications: "痰热喘满,咳痰黄稠,风热咳嗽痰多", level: "二类", mnemonic: "前胡降气化痰", mnemonicExplanation: "前胡降肺气化痰浊,兼疏散风热" },
  { id: "h_xuanfuhua", name: "旋覆花", category: "化痰止咳平喘药", property: "苦、辛、咸,微温", meridian: "肺、脾、胃、大肠", functions: "降气,消痰,行水,止呕", indications: "风寒咳嗽,痰饮蓄结,胸膈痞闷,呕吐噫气", level: "二类", mnemonic: "旋覆降气消痰", mnemonicExplanation: "旋覆花善降气消痰,为治噫气呕吐要药(包煎)" },
  { id: "h_baiqian", name: "白前", category: "化痰止咳平喘药", property: "辛、苦,微温", meridian: "肺", functions: "降气,消痰,止咳", indications: "肺气壅实,咳嗽痰多,胸满喘急", level: "二类", mnemonic: "白前降气止咳", mnemonicExplanation: "白前善降肺气消痰,为治咳嗽痰多常用药" },
  { id: "h_pipaye", name: "枇杷叶", category: "化痰止咳平喘药", property: "苦,微寒", meridian: "肺、胃", functions: "清肺止咳,降逆止呕", indications: "肺热咳嗽,气逆喘急,胃热呕逆,烦热口渴", level: "二类", mnemonic: "枇杷叶清肺止呕", mnemonicExplanation: "枇杷叶清肺胃之热,止咳止呕(包煎)" },
  { id: "h_mabo", name: "马勃", category: "化痰止咳平喘药", property: "辛,平", meridian: "肺", functions: "清肺利咽,解毒止血", indications: "风热郁肺,咽痛音哑,咳嗽,吐血衄血,外伤出血", level: "二类", mnemonic: "马勃利咽止血", mnemonicExplanation: "马勃善清肺利咽,外用止血" },
  { id: "h_tinglizi", name: "葶苈子", category: "化痰止咳平喘药", property: "辛、苦,大寒", meridian: "肺、膀胱", functions: "泻肺平喘,行水消肿", indications: "痰涎壅肺,喘咳痰多,胸胁胀满,水肿,小便不利", level: "二类", mnemonic: "葶苈泻肺逐水", mnemonicExplanation: "葶苈子泻肺行水之力峻,治痰饮喘咳水肿(包煎)" },
  { id: "h_baiguo", name: "白果", category: "化痰止咳平喘药", property: "甘、苦、涩,平,有毒", meridian: "肺、肾", functions: "敛肺定喘,止带缩尿", indications: "哮喘痰嗽,带下白浊,遗尿尿频", level: "二类", mnemonic: "白果敛肺定喘", mnemonicExplanation: "白果敛肺定喘兼止带缩尿(有毒,勿多食)" },
  { id: "h_huangyaozi", name: "黄药子", category: "化痰止咳平喘药", property: "苦,寒,有毒", meridian: "肺、肝、心", functions: "化痰散结消瘿,清热解毒", indications: "瘿瘤瘰疬,咳嗽痰喘,疮疡肿毒,咽喉肿痛", level: "二类", mnemonic: "黄药子消瘿", mnemonicExplanation: "黄药子为治瘿瘤要药(有毒,久服伤肝)" },
  { id: "h_haihaishi", name: "海蛤壳", category: "化痰止咳平喘药", property: "苦、咸,寒", meridian: "肺、肾、胃", functions: "清热化痰,软坚散结,制酸止痛", indications: "痰火咳嗽,胸胁疼痛,瘰疬瘿瘤,胃痛泛酸", level: "二类", mnemonic: "海蛤清化痰热", mnemonicExplanation: "海蛤壳清化热痰,煅用制酸止痛(先煎)" },
  { id: "h_haipiaoxiao", name: "海螵蛸", category: "收涩药", property: "咸、涩,温", meridian: "脾、肾", functions: "收敛止血,涩精止带,制酸止痛,收湿敛疮", indications: "崩漏便血,吐血衄血,遗精带下,胃痛吞酸,湿疹湿疮", level: "二类", mnemonic: "乌贼骨制酸止带", mnemonicExplanation: "海螵蛸(乌贼骨)收敛止血制酸,为治胃痛泛酸要药" },
  // ===== 第三批扩充(2026-08,目标 300+ 味) =====
  { id: "h_shashen", name: "沙参", category: "补虚药", property: "甘,微寒", meridian: "肺、胃", functions: "养阴清肺,益胃生津", indications: "肺热燥咳,阴虚劳嗽,干咳少痰,胃阴不足,咽干口渴", level: "一类", mnemonic: "沙参养阴润肺", mnemonicExplanation: "沙参善养肺胃之阴,为阴虚燥咳要药" },
  { id: "h_baihe", name: "百合", category: "补虚药", property: "甘,微寒", meridian: "心、肺", functions: "养阴润肺,清心安神", indications: "阴虚燥咳,劳嗽咳血,虚烦惊悸,失眠多梦,精神恍惚", level: "二类", mnemonic: "百合润肺宁心", mnemonicExplanation: "百合润肺止咳兼清心安神,治百合病要药" },
  { id: "h_yuzhu", name: "玉竹", category: "补虚药", property: "甘,微寒", meridian: "肺、胃", functions: "养阴润燥,生津止渴", indications: "肺胃阴伤,燥热咳嗽,咽干口渴,内热消渴", level: "二类", mnemonic: "玉竹滋阴润燥", mnemonicExplanation: "玉竹养阴而不滋腻,为养肺胃阴常用药" },
  { id: "h_shihu", name: "石斛", category: "补虚药", property: "甘,微寒", meridian: "胃、肾", functions: "益胃生津,滋阴清热", indications: "热病津伤,口干烦渴,胃阴不足,食少干呕,阴虚火旺", level: "二类", mnemonic: "石斛益胃生津", mnemonicExplanation: "石斛善养胃阴生津液,为治胃阴不足要药" },
  { id: "h_huangjing", name: "黄精", category: "补虚药", property: "甘,平", meridian: "脾、肺、肾", functions: "补气养阴,健脾,润肺,益肾", indications: "脾胃气虚,体倦乏力,肺虚燥咳,肾虚精亏,须发早白", level: "二类", mnemonic: "黄精平补三脏", mnemonicExplanation: "黄精补脾肺肾三脏之阴气,为平补药" },
  { id: "h_mohanlian", name: "墨旱莲", category: "补虚药", property: "甘、酸,寒", meridian: "肝、肾", functions: "滋补肝肾,凉血止血", indications: "肝肾阴虚,眩晕耳鸣,须发早白,吐血衄血,尿血便血", level: "二类", mnemonic: "旱莲乌须止血", mnemonicExplanation: "墨旱莲滋补肝肾而兼凉血止血,为乌须要药" },
  { id: "h_nvzhenzi", name: "女贞子", category: "补虚药", property: "甘、苦,凉", meridian: "肝、肾", functions: "滋补肝肾,明目乌发", indications: "肝肾阴虚,眩晕耳鸣,腰膝酸软,须发早白,目暗不明", level: "二类", mnemonic: "女贞滋肾明目", mnemonicExplanation: "女贞子补肝肾阴,为治须发早白、目暗要药" },
  { id: "h_guijia", name: "龟甲", category: "补虚药", property: "咸、甘,微寒", meridian: "肝、肾、心", functions: "滋阴潜阳,益肾强骨,养血补心,固经止崩", indications: "阴虚阳亢,骨蒸潮热,腰膝痿软,心虚健忘,崩漏带下", level: "二类", mnemonic: "龟甲滋阴潜阳", mnemonicExplanation: "龟甲善滋阴潜阳,为治阴虚阳亢要药(先煎)" },
  { id: "h_biejia", name: "鳖甲", category: "补虚药", property: "咸,微寒", meridian: "肝、肾", functions: "滋阴潜阳,退热除蒸,软坚散结", indications: "阴虚发热,骨蒸劳热,癥瘕积聚,久疟疟母", level: "二类", mnemonic: "鳖甲退蒸软坚", mnemonicExplanation: "鳖甲滋阴退蒸兼软坚散结,治癥瘕要药(先煎)" },
  { id: "h_lurong", name: "鹿茸", category: "补虚药", property: "甘、咸,温", meridian: "肾、肝", functions: "壮肾阳,益精血,强筋骨,调冲任,托疮毒", indications: "肾阳不足,精血亏虚,畏寒肢冷,阳痿滑精,腰膝酸软", level: "一类", mnemonic: "鹿茸壮阳益精", mnemonicExplanation: "鹿茸为壮肾阳、益精血之要药(研末冲服)" },
  { id: "h_bajitian", name: "巴戟天", category: "补虚药", property: "甘、辛,微温", meridian: "肾、肝", functions: "补肾阳,强筋骨,祛风湿", indications: "阳痿遗精,宫冷不孕,月经不调,少腹冷痛,风湿痹痛", level: "二类", mnemonic: "巴戟温肾强骨", mnemonicExplanation: "巴戟天补肾阳而兼祛风湿,温而不燥" },
  { id: "h_buguzhi", name: "补骨脂", category: "补虚药", property: "辛、苦,温", meridian: "肾、脾", functions: "温肾助阳,纳气平喘,温脾止泻,外用消风祛斑", indications: "肾阳不足,阳痿遗精,腰膝冷痛,肾虚作喘,五更泄泻", level: "二类", mnemonic: "补骨脂温肾止泻", mnemonicExplanation: "补骨脂善温肾阳,为治五更泄泻要药" },
  { id: "h_yizhiren", name: "益智仁", category: "补虚药", property: "辛,温", meridian: "肾、脾", functions: "暖肾固精缩尿,温脾止泻摄唾", indications: "肾虚遗尿,小便频数,遗精白浊,脾寒泄泻,口多唾涎", level: "二类", mnemonic: "益智缩尿摄唾", mnemonicExplanation: "益智仁暖肾固精缩尿,温脾摄唾止泻" },
  { id: "h_tusizi", name: "菟丝子", category: "补虚药", property: "辛、甘,平", meridian: "肝、肾、脾", functions: "补益肝肾,固精缩尿,安胎,明目,止泻", indications: "阳痿遗精,遗尿尿频,腰膝酸软,胎动不安,目暗耳鸣", level: "二类", mnemonic: "菟丝子平补肝肾", mnemonicExplanation: "菟丝子平补肝肾阴阳,兼安胎明目止泻" },
  { id: "h_shayuanzi", name: "沙苑子", category: "补虚药", property: "甘,温", meridian: "肝、肾", functions: "补肾助阳,固精缩尿,养肝明目", indications: "肾虚腰痛,遗精早泄,遗尿尿频,白浊带下,目暗昏花", level: "二类", mnemonic: "沙苑固精明目", mnemonicExplanation: "沙苑子温补肝肾而固精,兼养肝明目" },
  { id: "h_ziheche", name: "紫河车", category: "补虚药", property: "甘、咸,温", meridian: "肺、肝、肾", functions: "温肾补精,益气养血", indications: "虚劳羸瘦,骨蒸盗汗,咳嗽气喘,食少气短,阳痿遗精", level: "二类", mnemonic: "紫河车补精血", mnemonicExplanation: "紫河车(胎盘)为血肉有情之品,大补精血(研末冲服)" },
  { id: "h_gejie", name: "蛤蚧", category: "补虚药", property: "咸,平", meridian: "肺、肾", functions: "补肺益肾,纳气平喘,助阳益精", indications: "肺虚咳嗽,肾虚作喘,虚劳喘咳,阳痿,遗精", level: "二类", mnemonic: "蛤蚧纳气平喘", mnemonicExplanation: "蛤蚧为治虚喘要药,善补肺肾纳气(研末冲服)" },
  { id: "h_dongchongxiacao", name: "冬虫夏草", category: "补虚药", property: "甘,平", meridian: "肺、肾", functions: "补肾益肺,止血化痰", indications: "肾虚精亏,阳痿遗精,久咳虚喘,劳嗽痰血", level: "二类", mnemonic: "虫草补肺益肾", mnemonicExplanation: "冬虫夏草补肺肾而止嗽化痰,为虚损调补要药" },
  { id: "h_hetaoren", name: "核桃仁", category: "补虚药", property: "甘,温", meridian: "肾、肺、大肠", functions: "补肾温肺,润肠通便", indications: "肾虚腰痛,脚软,虚寒喘咳,肠燥便秘", level: "二类", mnemonic: "核桃补肾润肠", mnemonicExplanation: "核桃仁补肾温肺而润肠,为虚喘便秘常用" },
  { id: "h_xianmao", name: "仙茅", category: "补虚药", property: "辛,热,有毒", meridian: "肾、肝、脾", functions: "补肾阳,强筋骨,祛寒湿", indications: "阳痿精冷,小便不禁,腰膝冷痛,筋骨痿软", level: "二类", mnemonic: "仙茅壮阳祛寒", mnemonicExplanation: "仙茅辛热性猛,善补命火而祛寒湿" },
  { id: "h_roucongrong", name: "肉苁蓉", category: "补虚药", property: "甘、咸,温", meridian: "肾、大肠", functions: "补肾阳,益精血,润肠通便", indications: "肾阳不足,精血亏虚,阳痿不孕,腰膝酸软,肠燥便秘", level: "二类", mnemonic: "苁蓉温阳润肠", mnemonicExplanation: "肉苁蓉温而不燥,补而不腻,兼润肠通便" },
  { id: "h_suoyang", name: "锁阳", category: "补虚药", property: "甘,温", meridian: "肝、肾、大肠", functions: "补肾助阳,润肠通便", indications: "肾阳不足,阳痿遗精,腰膝痿软,肠燥便秘", level: "二类", mnemonic: "锁阳壮阳通便", mnemonicExplanation: "锁阳补肾助阳而润肠,与肉苁蓉相须" },
  { id: "h_xiyangshen", name: "西洋参", category: "补虚药", property: "甘、微苦,凉", meridian: "心、肺、肾", functions: "补气养阴,清热生津", indications: "气阴两伤,神疲乏力,虚热烦倦,肺虚久咳,咽干口渴", level: "二类", mnemonic: "西洋参益气养阴", mnemonicExplanation: "西洋参补气养阴而清虚热,为清补要药(另煎)" },
  { id: "h_longyanrou", name: "龙眼肉", category: "补虚药", property: "甘,温", meridian: "心、脾", functions: "补益心脾,养血安神", indications: "气血不足,心悸怔忡,健忘失眠,血虚萎黄", level: "二类", mnemonic: "龙眼补脾养血", mnemonicExplanation: "龙眼肉补心脾益气血,为养血安神常用药" },
  { id: "h_bandianlian", name: "半边莲", category: "清热药", property: "辛,平", meridian: "心、小肠、肺", functions: "清热解毒,利水消肿", indications: "毒蛇咬伤,痈肿疔疮,水肿臌胀,湿热黄疸", level: "二类", mnemonic: "半边莲解蛇毒", mnemonicExplanation: "半边莲为治毒蛇咬伤要药,兼利水消肿" },
  { id: "h_banzhilian", name: "半枝莲", category: "清热药", property: "辛、苦,寒", meridian: "肺、肝、肾", functions: "清热解毒,化瘀利尿", indications: "痈肿疮毒,咽喉肿痛,毒蛇咬伤,水肿,黄疸", level: "二类", mnemonic: "半枝莲解毒化瘀", mnemonicExplanation: "半枝莲清热解毒而兼化瘀利尿" },
  { id: "h_chonglou", name: "重楼", category: "清热药", property: "苦,微寒,有小毒", meridian: "肝", functions: "清热解毒,消肿止痛,凉肝定惊", indications: "痈肿疔疮,咽喉肿痛,蛇虫咬伤,跌扑伤痛,惊风抽搐", level: "二类", mnemonic: "重楼解毒定惊", mnemonicExplanation: "重楼(七叶一枝花)善解蛇毒消肿,兼定惊" },
  { id: "h_shancigu", name: "山慈菇", category: "清热药", property: "甘、微辛,凉,有毒", meridian: "肝、脾", functions: "清热解毒,化痰散结", indications: "痈肿疔毒,瘰疬痰核,蛇虫咬伤,癥瘕痞块", level: "二类", mnemonic: "山慈菇散结", mnemonicExplanation: "山慈菇清热解毒而化痰散结" },
  { id: "h_loulu", name: "漏芦", category: "清热药", property: "苦,寒", meridian: "胃", functions: "清热解毒,消痈散结,通经下乳,舒筋通脉", indications: "乳痈肿痛,痈疽发背,瘰疬疮毒,乳汁不通,骨节疼痛", level: "二类", mnemonic: "漏芦通乳消痈", mnemonicExplanation: "漏芦善治乳痈,兼通经下乳" },
  { id: "h_bailian", name: "白蔹", category: "清热药", property: "苦,微寒", meridian: "心、胃", functions: "清热解毒,消痈散结,敛疮生肌", indications: "痈肿疮毒,瘰疬痰核,烧烫伤,疮疡不敛", level: "二类", mnemonic: "白蔹消痈敛疮", mnemonicExplanation: "白蔹清热解毒消痈,外用敛疮生肌(反乌头)" },
  { id: "h_jinqiaomai", name: "金荞麦", category: "清热药", property: "微辛、涩,凉", meridian: "肺", functions: "清热解毒,排脓祛瘀", indications: "肺痈吐脓,肺热咳喘,咽喉肿痛,痈肿疮毒", level: "二类", mnemonic: "金荞麦排脓", mnemonicExplanation: "金荞麦善治肺痈,清热解毒排脓" },
  { id: "h_dijincao", name: "地锦草", category: "清热药", property: "辛,平", meridian: "肝、大肠", functions: "清热解毒,凉血止血,利湿退黄", indications: "痢疾,泄泻,咯血,便血,尿血,湿热黄疸", level: "二类", mnemonic: "地锦草止痢", mnemonicExplanation: "地锦草清热解毒止痢,兼凉血止血退黄" },
  { id: "h_fanbaicao", name: "翻白草", category: "清热药", property: "苦、寒", meridian: "胃、大肠", functions: "清热解毒,止痢,止血", indications: "湿热泻痢,痈肿疮毒,血热吐衄,便血崩漏", level: "二类", mnemonic: "翻白草治痢", mnemonicExplanation: "翻白草清热解毒止痢,兼止血" },
  { id: "h_kudingcha", name: "苦丁茶", category: "清热药", property: "苦、甘,寒", meridian: "肝、肺、胃", functions: "疏风清热,明目生津", indications: "风热头痛,目赤齿痛,热病烦渴,泄泻痢疾", level: "二类", mnemonic: "苦丁茶清热", mnemonicExplanation: "苦丁茶疏风清热,兼生津止渴" },
  { id: "h_juemingzi", name: "决明子", category: "清热药", property: "甘、苦、咸,微寒", meridian: "肝、大肠", functions: "清肝明目,润肠通便", indications: "目赤涩痛,羞明多泪,头痛眩晕,目暗不明,肠燥便秘", level: "一类", mnemonic: "决明清肝明目", mnemonicExplanation: "决明子为治目疾常用药,兼润肠通便(打碎)" },
  { id: "h_gujingcao", name: "谷精草", category: "清热药", property: "辛、甘,平", meridian: "肝、肺", functions: "疏散风热,明目退翳", indications: "风热目赤,肿痛羞明,眼生翳膜,风热头痛", level: "二类", mnemonic: "谷精退翳明目", mnemonicExplanation: "谷精草善疏散风热而明目退翳" },
  { id: "h_mimenghua", name: "密蒙花", category: "清热药", property: "甘,微寒", meridian: "肝", functions: "清热泻火,养肝明目,退翳", indications: "目赤肿痛,多泪羞明,目生翳膜,肝虚目暗", level: "二类", mnemonic: "密蒙养肝明目", mnemonicExplanation: "密蒙花清肝养肝而退翳明目" },
  { id: "h_qingxiangzi", name: "青葙子", category: "清热药", property: "苦,微寒", meridian: "肝", functions: "清肝泻火,明目退翳", indications: "肝热目赤,眼生翳膜,视物昏花,肝火眩晕", level: "二类", mnemonic: "青葙泻肝明目", mnemonicExplanation: "青葙子善清肝火而明目退翳(青光眼慎用)" },
  { id: "h_lugen", name: "芦根", category: "清热药", property: "甘,寒", meridian: "肺、胃", functions: "清热泻火,生津止渴,除烦,止呕,利尿", indications: "热病烦渴,胃热呕哕,肺热咳嗽,肺痈吐脓,热淋涩痛", level: "一类", mnemonic: "芦根清热生津", mnemonicExplanation: "芦根清肺胃热而生津,治肺痈要药" },
  { id: "h_tianhuafen", name: "天花粉", category: "清热药", property: "甘、微苦,微寒", meridian: "肺、胃", functions: "清热泻火,生津止渴,消肿排脓", indications: "热病烦渴,肺热燥咳,内热消渴,疮疡肿毒", level: "二类", mnemonic: "花粉生津排脓", mnemonicExplanation: "天花粉清热生津兼消肿排脓(反乌头)" },
  { id: "h_zhuye", name: "竹叶", category: "清热药", property: "甘、辛、淡,寒", meridian: "心、肺、胃", functions: "清热泻火,除烦,生津,利尿", indications: "热病烦渴,口疮尿赤,小便短赤涩痛", level: "二类", mnemonic: "竹叶清心除烦", mnemonicExplanation: "竹叶善清心火而除烦,兼利尿" },
  { id: "h_danzhuye", name: "淡竹叶", category: "清热药", property: "甘、淡,寒", meridian: "心、胃、小肠", functions: "清热泻火,除烦止渴,利尿通淋", indications: "热病烦渴,口疮尿赤,小便赤涩淋痛", level: "二类", mnemonic: "淡竹叶清心利尿", mnemonicExplanation: "淡竹叶清心除烦而利尿,善治心火下移小肠" },
  { id: "h_mutong", name: "木通", category: "利水渗湿药", property: "苦,寒", meridian: "心、小肠、膀胱", functions: "利尿通淋,清心除烦,通经下乳", indications: "热淋涩痛,水肿,心烦尿赤,口舌生疮,经闭乳少", level: "二类", mnemonic: "木通通淋下乳", mnemonicExplanation: "木通清心火而利水通淋,兼通经下乳" },
  { id: "h_tongcao", name: "通草", category: "利水渗湿药", property: "甘、淡,微寒", meridian: "肺、胃", functions: "利尿通淋,通气下乳", indications: "淋证涩痛,水肿尿少,产后乳汁不下", level: "二类", mnemonic: "通草通淋下乳", mnemonicExplanation: "通草利水通淋而通气下乳,性缓不峻" },
  { id: "h_bianxu", name: "萹蓄", category: "利水渗湿药", property: "苦,微寒", meridian: "膀胱", functions: "利尿通淋,杀虫,止痒", indications: "热淋涩痛,小便短赤,虫积腹痛,湿疹阴痒", level: "二类", mnemonic: "萹蓄通淋杀虫", mnemonicExplanation: "萹蓄利水通淋而杀虫止痒" },
  { id: "h_qumai", name: "瞿麦", category: "利水渗湿药", property: "苦,寒", meridian: "心、小肠", functions: "利尿通淋,破血通经", indications: "热淋血淋,石淋小便不通,经闭瘀阻", level: "二类", mnemonic: "瞿麦破血通淋", mnemonicExplanation: "瞿麦利尿通淋力强,兼破血通经" },
  { id: "h_shiwei", name: "石韦", category: "利水渗湿药", property: "苦、甘,微寒", meridian: "肺、膀胱", functions: "利尿通淋,清肺止咳,凉血止血", indications: "热淋血淋,石淋,小便涩痛,肺热咳嗽,血热出血", level: "二类", mnemonic: "石韦通淋止血", mnemonicExplanation: "石韦利尿通淋兼凉血止血,为治血淋要药" },
  { id: "h_haijinsha", name: "海金沙", category: "利水渗湿药", property: "甘、咸,寒", meridian: "膀胱、小肠", functions: "清利湿热,通淋止痛", indications: "热淋石淋,血淋膏淋,尿道涩痛,水肿", level: "二类", mnemonic: "海金沙通淋止痛", mnemonicExplanation: "海金沙为治诸淋涩痛要药(包煎)" },
  { id: "h_dengxincao", name: "灯心草", category: "利水渗湿药", property: "甘、淡,微寒", meridian: "心、肺、小肠", functions: "利尿通淋,清心降火", indications: "热淋,水肿,心烦失眠,口舌生疮,小儿夜啼", level: "二类", mnemonic: "灯心草清心利尿", mnemonicExplanation: "灯心草清心火而利小便,兼除烦安神" },
  { id: "h_dongkuizi", name: "冬葵子", category: "利水渗湿药", property: "甘、涩,凉", meridian: "大肠、小肠、膀胱", functions: "利尿通淋,下乳,润肠", indications: "淋证,水肿,乳汁不下,乳房胀痛,肠燥便秘", level: "二类", mnemonic: "冬葵子通淋下乳", mnemonicExplanation: "冬葵子利尿通淋兼下乳润肠" },
  { id: "h_cangzhu", name: "苍术", category: "化湿药", property: "辛、苦,温", meridian: "脾、胃、肝", functions: "燥湿健脾,祛风散寒,明目", indications: "湿阻中焦,脘腹胀满,泄泻水肿,风湿痹痛,夜盲", level: "一类", mnemonic: "苍术燥湿健脾", mnemonicExplanation: "苍术善燥湿健脾,为治湿阻中焦要药" },
  { id: "h_doukou", name: "豆蔻", category: "化湿药", property: "辛,温", meridian: "肺、脾、胃", functions: "化湿行气,温中止呕,开胃消食", indications: "湿浊中阻,不思饮食,胸闷腹胀,寒湿呕逆,食积不消", level: "二类", mnemonic: "豆蔻化湿行气", mnemonicExplanation: "豆蔻(白豆蔻)化湿行气而温中止呕(后下)" },
  { id: "h_caodoukou", name: "草豆蔻", category: "化湿药", property: "辛,温", meridian: "脾、胃", functions: "燥湿行气,温中止呕", indications: "寒湿内阻,脘腹胀满冷痛,嗳气呕逆,不思饮食", level: "二类", mnemonic: "草蔻燥湿止呕", mnemonicExplanation: "草豆蔻燥湿散寒而行气止呕" },
  { id: "h_huajiao", name: "花椒", category: "温里药", property: "辛,温,有小毒", meridian: "脾、胃、肾", functions: "温中止痛,杀虫止痒", indications: "脘腹冷痛,呕吐泄泻,蛔虫腹痛,湿疹阴痒", level: "二类", mnemonic: "花椒温中杀虫", mnemonicExplanation: "花椒温中散寒止痛,兼杀虫止痒" },
  { id: "h_gaoliangjiang", name: "高良姜", category: "温里药", property: "辛,热", meridian: "脾、胃", functions: "温胃止呕,散寒止痛", indications: "胃寒冷痛,呕吐泄泻,脘腹冷痛", level: "二类", mnemonic: "高良姜温胃止痛", mnemonicExplanation: "高良姜善温胃散寒,为治胃寒冷痛要药" },
  { id: "h_xiaohuixiang", name: "小茴香", category: "温里药", property: "辛,温", meridian: "肝、肾、脾、胃", functions: "散寒止痛,理气和胃", indications: "寒疝腹痛,睾丸偏坠,痛经,脘腹胀痛,食少吐泻", level: "二类", mnemonic: "茴香散寒理气", mnemonicExplanation: "小茴香善散肝胃寒邪,治寒疝腹痛" },
  { id: "h_hujiao", name: "胡椒", category: "温里药", property: "辛,热", meridian: "胃、大肠", functions: "温中散寒,下气消痰", indications: "胃寒呕吐,腹痛泄泻,食欲不振,癫痫痰多", level: "二类", mnemonic: "胡椒温中散寒", mnemonicExplanation: "胡椒温中止痛,为调味与温胃常用" },
  { id: "h_bibo", name: "荜茇", category: "温里药", property: "辛,热", meridian: "胃、大肠", functions: "温中散寒,下气止痛", indications: "脘腹冷痛,呕吐泄泻,偏头痛,牙痛", level: "二类", mnemonic: "荜茇温中止痛", mnemonicExplanation: "荜茇温中散寒而止痛,治胃寒痛与牙痛" },
  { id: "h_qingpi", name: "青皮", category: "理气药", property: "苦、辛,温", meridian: "肝、胆、胃", functions: "疏肝破气,消积化滞", indications: "肝郁气滞,胸胁胀痛,疝气疼痛,乳癖乳痈,食积腹痛", level: "二类", mnemonic: "青皮破气疏肝", mnemonicExplanation: "青皮力猛,善破肝气之郁结,消积滞" },
  { id: "h_chuanlianzi", name: "川楝子", category: "理气药", property: "苦,寒,有小毒", meridian: "肝、胃、小肠、膀胱", functions: "疏肝泄热,行气止痛,杀虫", indications: "肝郁化火,胸胁脘腹胀痛,疝气疼痛,虫积腹痛", level: "二类", mnemonic: "川楝泄热止痛", mnemonicExplanation: "川楝子疏肝泄热而止痛,兼杀虫(炒用)" },
  { id: "h_foshou", name: "佛手", category: "理气药", property: "辛、苦,温", meridian: "肝、脾、胃、肺", functions: "疏肝理气,和胃止痛,燥湿化痰", indications: "肝胃气滞,胸胁胀痛,胃脘痞满,食少呕吐,咳嗽痰多", level: "二类", mnemonic: "佛手疏肝理气", mnemonicExplanation: "佛手理气而不伤阴,为治肝胃气滞常用" },
  { id: "h_xiangyuan", name: "香橼", category: "理气药", property: "辛、苦、酸,温", meridian: "肝、脾、肺", functions: "疏肝理气,宽中,化痰", indications: "肝胃气滞,胸胁胀痛,脘腹痞满,呕吐噫气,痰多咳嗽", level: "二类", mnemonic: "香橼理气宽中", mnemonicExplanation: "香橼功似佛手而力缓,理气化痰" },
  { id: "h_wuyao", name: "乌药", category: "理气药", property: "辛,温", meridian: "肺、脾、肾、膀胱", functions: "行气止痛,温肾散寒", indications: "寒凝气滞,胸腹诸痛,疝气疼痛,痛经,膀胱虚冷尿频", level: "二类", mnemonic: "乌药温肾行气", mnemonicExplanation: "乌药善行下焦气滞而温肾散寒" },
  { id: "h_shidi", name: "柿蒂", category: "理气药", property: "苦、涩,平", meridian: "胃", functions: "降逆止呃", indications: "胃气上逆,呃逆", level: "二类", mnemonic: "柿蒂降逆止呃", mnemonicExplanation: "柿蒂善降胃气,为治呃逆之专药" },
  { id: "h_lizhihe", name: "荔枝核", category: "理气药", property: "甘、微苦,温", meridian: "肝、胃", functions: "行气散结,祛寒止痛", indications: "疝气痛,睾丸肿痛,胃脘痛,痛经,产后腹痛", level: "二类", mnemonic: "荔枝核治疝痛", mnemonicExplanation: "荔枝核善行肝胃气滞,为治疝气要药" },
  { id: "h_gansong", name: "甘松", category: "理气药", property: "辛、甘,温", meridian: "脾、胃", functions: "行气止痛,开郁醒脾", indications: "脘腹闷胀,疼痛,不思饮食,思虑伤脾,气郁胸闷", level: "二类", mnemonic: "甘松开郁醒脾", mnemonicExplanation: "甘松理气开郁而醒脾,善治思虑伤脾" },
  // ===== 第四批扩充(2026-08,冲 300+ 味) =====
  { id: "h_laifuzi", name: "莱菔子", category: "消食药", property: "辛、甘,平", meridian: "肺、脾、胃", functions: "消食除胀,降气化痰", indications: "饮食停滞,脘腹胀痛,大便秘结,痰壅喘咳", level: "二类", mnemonic: "莱菔消食降气", mnemonicExplanation: "莱菔子善消食除胀,兼降气化痰(炒用)" },
  { id: "h_guya", name: "谷芽", category: "消食药", property: "甘,温", meridian: "脾、胃", functions: "消食和中,健脾开胃", indications: "食积不消,腹胀口臭,脾胃虚弱,不饥食少", level: "二类", mnemonic: "谷芽健脾开胃", mnemonicExplanation: "谷芽消食力缓,善健脾开胃(炒用)" },
  { id: "h_jishiteng", name: "鸡矢藤", category: "消食药", property: "甘、苦,微寒", meridian: "脾、胃、肝、肺", functions: "消食健胃,化痰止咳,清热解毒,止痛", indications: "食积腹胀,小儿疳积,咳嗽痰多,咽喉肿痛,跌打损伤", level: "二类", mnemonic: "鸡矢藤消积止痛", mnemonicExplanation: "鸡矢藤消食兼止痛,为小儿疳积常用药" },
  { id: "h_kulianpi", name: "苦楝皮", category: "驱虫药", property: "苦,寒,有毒", meridian: "肝、脾、胃", functions: "杀虫,疗癣", indications: "蛔虫病,蛲虫病,虫积腹痛,疥癣瘙痒", level: "二类", mnemonic: "苦楝皮驱蛔", mnemonicExplanation: "苦楝皮驱蛔杀虫力强(有毒,不宜久服)" },
  { id: "h_leiwan", name: "雷丸", category: "驱虫药", property: "微苦,寒,有小毒", meridian: "胃、大肠", functions: "杀虫消积", indications: "绦虫病,钩虫病,蛔虫病,虫积腹痛,小儿疳积", level: "二类", mnemonic: "雷丸驱绦要药", mnemonicExplanation: "雷丸善驱绦虫(不入煎剂,研粉冲服)" },
  { id: "h_qianshi", name: "芡实", category: "收涩药", property: "甘、涩,平", meridian: "脾、肾", functions: "益肾固精,补脾止泻,除湿止带", indications: "遗精滑精,遗尿尿频,脾虚久泻,白浊带下", level: "二类", mnemonic: "芡实固精止带", mnemonicExplanation: "芡实补脾肾而涩精止泻,兼除湿止带" },
  { id: "h_chishizhi", name: "赤石脂", category: "收涩药", property: "甘、酸、涩,温", meridian: "胃、大肠", functions: "涩肠止泻,收敛止血,敛疮生肌", indications: "久泻久痢,便血脱肛,崩漏带下,疮疡久溃不敛", level: "二类", mnemonic: "赤石脂涩肠", mnemonicExplanation: "赤石脂善涩肠止泻止血,外用敛疮(畏官桂)" },
  { id: "h_yuyuliang", name: "禹余粮", category: "收涩药", property: "甘、涩,微寒", meridian: "胃、大肠", functions: "涩肠止泻,收敛止血,止带", indications: "久泻久痢,大便出血,崩漏带下", level: "二类", mnemonic: "禹余粮涩肠止泻", mnemonicExplanation: "禹余粮功似赤石脂,专于收敛固涩" },
  { id: "h_wubeizi", name: "五倍子", category: "收涩药", property: "酸、涩,寒", meridian: "肺、大肠、肾", functions: "敛肺降火,涩肠止泻,敛汗止血,收湿敛疮", indications: "肺虚久咳,久泻久痢,自汗盗汗,便血痔血,疮疡不敛", level: "二类", mnemonic: "五倍子敛肺涩肠", mnemonicExplanation: "五倍子收敛力强,敛肺涩肠止汗止血" },
  { id: "h_yegengteng", name: "夜交藤", category: "安神药", property: "甘,平", meridian: "心、肝", functions: "养血安神,祛风通络", indications: "虚烦失眠,多梦易惊,血虚身痛,风湿痹痛,皮肤瘙痒", level: "二类", mnemonic: "夜交藤安神", mnemonicExplanation: "夜交藤(何首乌藤)养血安神兼祛风通络" },
  { id: "h_cishi", name: "磁石", category: "安神药", property: "咸,寒", meridian: "肝、心、肾", functions: "镇惊安神,平肝潜阳,聪耳明目,纳气平喘", indications: "心神不宁,惊悸失眠,头晕目眩,耳鸣耳聋,肾虚喘促", level: "二类", mnemonic: "磁石镇惊纳气", mnemonicExplanation: "磁石重镇安神,平肝潜阳而纳气平喘(先煎)" },
  { id: "h_hehuanhua", name: "合欢花", category: "安神药", property: "甘,平", meridian: "心、肝", functions: "解郁安神", indications: "心神不宁,忧郁失眠", level: "二类", mnemonic: "合欢花解郁", mnemonicExplanation: "合欢花善解郁安神,治忧郁失眠" },
  { id: "h_lingzhi", name: "灵芝", category: "安神药", property: "甘,平", meridian: "心、肺、肝、肾", functions: "补气安神,止咳平喘", indications: "心神不宁,失眠心悸,肺虚咳喘,虚劳短气", level: "二类", mnemonic: "灵芝安神补气", mnemonicExplanation: "灵芝补心气而安神,兼止咳平喘" },
  { id: "h_muli", name: "牡蛎", category: "平肝息风药", property: "咸,微寒", meridian: "肝、胆、肾", functions: "潜阳补阴,重镇安神,软坚散结,收敛固涩", indications: "肝阳上亢,头晕目眩,惊悸失眠,瘰疬痰核,滑脱诸证", level: "二类", mnemonic: "牡蛎潜阳固涩", mnemonicExplanation: "牡蛎生用潜阳软坚,煅用收敛固涩(先煎)" },
  { id: "h_cjili", name: "刺蒺藜", category: "平肝息风药", property: "辛、苦,微温", meridian: "肝", functions: "平肝解郁,活血祛风,明目,止痒", indications: "头痛眩晕,胸胁胀痛,目赤翳障,风疹瘙痒,乳闭不通", level: "二类", mnemonic: "蒺藜平肝祛风", mnemonicExplanation: "刺蒺藜平肝解郁而祛风明目止痒" },
  { id: "h_luobuma", name: "罗布麻", category: "平肝息风药", property: "甘、苦,凉", meridian: "肝", functions: "平肝安神,清热利水", indications: "肝阳眩晕,心悸失眠,水肿尿少", level: "二类", mnemonic: "罗布麻平肝", mnemonicExplanation: "罗布麻平肝降压,兼清热利水" },
  { id: "h_suhexiang", name: "苏合香", category: "开窍药", property: "辛,温", meridian: "心、脾", functions: "开窍醒神,辟秽止痛", indications: "寒闭神昏,痰厥气厥,胸腹冷痛,真心痛", level: "二类", mnemonic: "苏合香开窍辟秽", mnemonicExplanation: "苏合香善开寒闭,辟秽止痛(入丸散)" },
  { id: "h_fanxieye", name: "番泻叶", category: "泻下药", property: "甘、苦,寒", meridian: "大肠", functions: "泻热行滞,通便,利水", indications: "热结积滞,便秘腹痛,水肿胀满", level: "二类", mnemonic: "番泻叶通便", mnemonicExplanation: "番泻叶泻热通便,为缓下药(泡服)" },
  { id: "h_luhui", name: "芦荟", category: "泻下药", property: "苦,寒", meridian: "肝、胃、大肠", functions: "泻下通便,清肝泻火,杀虫疗疳", indications: "热结便秘,肝火头痛,烦躁惊痫,小儿疳积,癣疮", level: "二类", mnemonic: "芦荟泻火通便", mnemonicExplanation: "芦荟泻下通便而清肝火(入丸散,不入煎剂)" },
  { id: "h_gansui", name: "甘遂", category: "泻下药", property: "苦,寒,有毒", meridian: "肺、肾、大肠", functions: "泻水逐饮,消肿散结", indications: "水肿胀满,胸腹积水,痰饮积聚,风痰癫痫,痈肿疮毒", level: "二类", mnemonic: "甘遂逐水峻药", mnemonicExplanation: "甘遂为泻水逐饮峻药(醋制,反甘草)" },
  { id: "h_qianniuzi", name: "牵牛子", category: "泻下药", property: "苦,寒,有毒", meridian: "肺、肾、大肠", functions: "泻水通便,消痰涤饮,杀虫攻积", indications: "水肿胀满,二便不通,痰饮积聚,气逆喘咳,虫积腹痛", level: "二类", mnemonic: "牵牛泻水攻积", mnemonicExplanation: "牵牛子泻下逐水而杀虫攻积(炒用,畏巴豆)" },
  { id: "h_fangji", name: "防己", category: "祛风湿药", property: "苦、辛,寒", meridian: "膀胱、肺", functions: "祛风止痛,利水消肿", indications: "风湿痹痛,水肿脚气,小便不利,湿疹疮毒", level: "二类", mnemonic: "防己祛风利水", mnemonicExplanation: "防己祛风湿而利水消肿(木防己祛风,汉防己利水)" },
  { id: "h_mugua", name: "木瓜", category: "祛风湿药", property: "酸,温", meridian: "肝、脾", functions: "舒筋活络,和胃化湿", indications: "风湿痹痛,筋脉拘挛,脚气水肿,吐泻转筋", level: "二类", mnemonic: "木瓜舒筋化湿", mnemonicExplanation: "木瓜善舒筋活络,为治转筋要药" },
  { id: "h_shenjincao", name: "伸筋草", category: "祛风湿药", property: "微苦、辛,温", meridian: "肝、脾、肾", functions: "祛风除湿,舒筋活络", indications: "风湿痹痛,关节酸痛,屈伸不利,跌打损伤", level: "二类", mnemonic: "伸筋草舒筋", mnemonicExplanation: "伸筋草善舒筋活络,治筋脉拘挛" },
  { id: "h_lulutong", name: "路路通", category: "祛风湿药", property: "苦,平", meridian: "肝、肾", functions: "祛风活络,利水通经", indications: "风湿痹痛,中风半身不遂,水肿,经闭乳少,风疹瘙痒", level: "二类", mnemonic: "路路通通络", mnemonicExplanation: "路路通善通经络利水,兼下乳" },
  { id: "h_xixiancao", name: "豨莶草", category: "祛风湿药", property: "辛、苦,寒", meridian: "肝、肾", functions: "祛风湿,利关节,解毒", indications: "风湿痹痛,筋骨无力,腰膝酸软,中风半身不遂,疮疡", level: "二类", mnemonic: "豨莶祛风通络", mnemonicExplanation: "豨莶草祛风湿而通络(制用补肝肾)" },
  { id: "h_luoshiteng", name: "络石藤", category: "祛风湿药", property: "苦,微寒", meridian: "心、肝、肾", functions: "祛风通络,凉血消肿", indications: "风湿热痹,筋脉拘挛,咽喉肿痛,痈肿疮毒", level: "二类", mnemonic: "络石藤通络", mnemonicExplanation: "络石藤祛风通络而凉血消肿" },
  { id: "h_jixueteng", name: "鸡血藤", category: "活血化瘀药", property: "苦、甘,温", meridian: "肝、肾", functions: "活血补血,调经止痛,舒筋活络", indications: "月经不调,痛经经闭,风湿痹痛,肢体麻木,血虚萎黄", level: "二类", mnemonic: "鸡血藤补血调经", mnemonicExplanation: "鸡血藤补血活血而调经,为妇科要药" },
  { id: "h_gusuibu", name: "骨碎补", category: "活血化瘀药", property: "苦,温", meridian: "肝、肾", functions: "疗伤止痛,补肾强骨,消风祛斑", indications: "跌扑闪挫,筋骨折伤,肾虚腰痛,耳鸣耳聋,斑秃", level: "二类", mnemonic: "骨碎补接骨", mnemonicExplanation: "骨碎补善续伤接骨,兼补肾强骨" },
  { id: "h_sumu", name: "苏木", category: "活血化瘀药", property: "甘、咸,平", meridian: "心、肝、脾", functions: "活血祛瘀,消肿止痛", indications: "跌打损伤,骨折筋伤,瘀滞肿痛,经闭痛经,产后瘀阻", level: "二类", mnemonic: "苏木祛瘀止痛", mnemonicExplanation: "苏木活血祛瘀而消肿止痛,为伤科要药" },
  { id: "h_lingxiaohua", name: "凌霄花", category: "活血化瘀药", property: "甘、酸,寒", meridian: "肝、心包", functions: "活血通经,凉血祛风", indications: "月经不调,经闭癥瘕,产后乳肿,风疹发红,皮肤瘙痒", level: "二类", mnemonic: "凌霄活血祛风", mnemonicExplanation: "凌霄花活血通经而凉血祛风(孕妇忌用)" },
  { id: "h_yuejihua", name: "月季花", category: "活血化瘀药", property: "甘,温", meridian: "肝", functions: "活血调经,疏肝解郁", indications: "月经不调,痛经,胸腹胀痛,跌打损伤", level: "二类", mnemonic: "月季调经解郁", mnemonicExplanation: "月季花活血调经而疏肝解郁" },
  { id: "h_zhuamagen", name: "苎麻根", category: "止血药", property: "甘,寒", meridian: "心、肝", functions: "凉血止血,安胎,清热解毒", indications: "血热出血,胎动不安,胎漏下血,痈肿疮毒", level: "二类", mnemonic: "苎麻根安胎止血", mnemonicExplanation: "苎麻根凉血止血而安胎,为治胎漏要药" },
  { id: "h_paojiang", name: "炮姜", category: "止血药", property: "苦、涩,温", meridian: "脾、肝", functions: "温经止血,温中止痛", indications: "虚寒性吐血便血,崩漏,脾胃虚寒,腹痛吐泻", level: "二类", mnemonic: "炮姜温经止血", mnemonicExplanation: "炮姜善温经止血,治虚寒失血(炒炭用)" },
  { id: "h_zaojia", name: "皂荚", category: "化痰止咳平喘药", property: "辛、咸,温,有小毒", meridian: "肺、大肠", functions: "祛痰开窍,散结消肿", indications: "顽痰阻肺,咳喘痰多,中风痰壅,口噤不开,痈肿", level: "二类", mnemonic: "皂荚涤痰开窍", mnemonicExplanation: "皂荚善祛顽痰而开窍,为急救豁痰药(有小毒)" },
  { id: "h_zhuli", name: "竹沥", category: "化痰止咳平喘药", property: "甘,寒", meridian: "心、肺、肝", functions: "清热豁痰,定惊利窍", indications: "痰热咳嗽,中风痰迷,惊痫癫狂,壮热烦渴", level: "二类", mnemonic: "竹沥豁痰定惊", mnemonicExplanation: "竹沥善清热豁痰,为治痰热蒙窍要药(冲服)" },
  { id: "h_tianzhuhuang", name: "天竺黄", category: "化痰止咳平喘药", property: "甘,寒", meridian: "心、肝", functions: "清热豁痰,凉心定惊", indications: "热病神昏,中风痰迷,小儿痰热惊痫,抽搐夜啼", level: "二类", mnemonic: "天竺黄定惊", mnemonicExplanation: "天竺黄清心豁痰而定惊,为小儿惊风要药" },
  { id: "h_mahuanggen", name: "麻黄根", category: "收涩药", property: "甘、涩,平", meridian: "心、肺", functions: "固表止汗", indications: "自汗,盗汗", level: "二类", mnemonic: "麻黄根止汗", mnemonicExplanation: "麻黄根专于收敛止汗,为治汗证要药" },
  { id: "h_fuxiaomai", name: "浮小麦", category: "收涩药", property: "甘,凉", meridian: "心", functions: "固表止汗,益气,除热", indications: "自汗盗汗,骨蒸劳热,虚热多汗", level: "二类", mnemonic: "浮小麦敛汗", mnemonicExplanation: "浮小麦益气固表止汗,兼退虚热" },
  { id: "h_nuodaogen", name: "糯稻根", category: "收涩药", property: "甘,平", meridian: "心、肝", functions: "固表止汗,益胃生津,退虚热", indications: "自汗盗汗,虚汗不止,阴虚发热", level: "二类", mnemonic: "糯稻根止汗", mnemonicExplanation: "糯稻根固表止汗而益胃生津" },
  { id: "h_muzei", name: "木贼", category: "解表药", property: "甘、苦,平", meridian: "肺、肝", functions: "疏散风热,明目退翳,止血", indications: "风热目赤,迎风流泪,目生翳障,便血痔血", level: "二类", mnemonic: "木贼退翳止血", mnemonicExplanation: "木贼疏散风热而明目退翳" },
  { id: "h_dafupi", name: "大腹皮", category: "理气药", property: "辛,微温", meridian: "脾、胃、大肠、小肠", functions: "行气宽中,行水消肿", indications: "脘腹胀满,大便不爽,水肿脚气,小便不利", level: "二类", mnemonic: "大腹皮行气利水", mnemonicExplanation: "大腹皮(槟榔壳)行气宽中而利水消肿" },
  { id: "h_baibiandou", name: "白扁豆", category: "补虚药", property: "甘,微温", meridian: "脾、胃", functions: "健脾化湿,和中消暑", indications: "脾胃虚弱,食欲不振,大便溏泻,暑湿吐泻,白带过多", level: "二类", mnemonic: "扁豆健脾化湿", mnemonicExplanation: "白扁豆健脾化湿而消暑,为清补常用" },
  { id: "h_heizhima", name: "黑芝麻", category: "补虚药", property: "甘,平", meridian: "肝、肾、大肠", functions: "补肝肾,益精血,润肠燥", indications: "精血亏虚,头晕眼花,耳鸣耳聋,须发早白,肠燥便秘", level: "二类", mnemonic: "芝麻补精益血", mnemonicExplanation: "黑芝麻补肝肾益精血,乌须发润肠" },
];

async function main() {
  // 1. 建分类(幂等)
  const catIdMap = new Map<string, number>();
  for (const c of CATEGORIES) {
    const existing = await db.herbCategory.findUnique({ where: { name: c.name } });
    if (existing) {
      catIdMap.set(c.name, existing.id);
      continue;
    }
    const created = await db.herbCategory.create({
      data: { name: c.name, sortOrder: c.sortOrder, description: "" },
    });
    catIdMap.set(c.name, created.id);
  }
  console.log(`✅ 分类就绪(${catIdMap.size} 个)`);

  // 2. 插入中药(幂等:name+source 唯一跳过)
  const SOURCE = "数据整理自《中国药典》2020年版公开条目(供学习参考)";
  let inserted = 0;
  let skipped = 0;
  for (const h of SEED_HERBS) {
    const categoryId = catIdMap.get(h.category);
    if (!categoryId) throw new Error(`分类缺失: ${h.category}`);
    const existing = await db.herb.findUnique({
      where: { name_source: { name: h.name, source: SOURCE } },
    });
    if (existing) {
      skipped++;
      continue;
    }
    await db.herb.create({
      data: {
        id: h.id,
        name: h.name,
        source: SOURCE,
        categoryId,
        property: h.property,
        meridian: h.meridian,
        functions: h.functions,
        indications: h.indications,
        mnemonic: h.mnemonic ?? "",
        mnemonicExplanation: h.mnemonicExplanation ?? "",
        level: h.level,
        sortOrder: 0,
      },
    });
    inserted++;
  }
  console.log(`✅ 中药种子完成:新增 ${inserted} 味,跳过 ${skipped} 味(已存在)`);

  const total = await db.herb.count();
  console.log(`📊 生产库当前中药总数: ${total} 味`);
}

main()
  .catch((e) => {
    console.error("❌ 种子失败:", e);
    process.exit(1);
  })
  .finally(() => db.$disconnect());
