// 腧穴种子数据入库脚本(Phase 2)
// 用法: DATABASE_URL=... DIRECT_URL=... npx tsx scripts/seed-acupoints-db.ts
// 幂等:经络按 name 唯一、穴位按 code 唯一跳过;重复执行安全
import { PrismaClient } from "@prisma/client";

const db = new PrismaClient();

// 十四经
const MERIDIANS: { name: string; code: string; sortOrder: number }[] = [
  { name: "手太阴肺经", code: "LU", sortOrder: 1 },
  { name: "手阳明大肠经", code: "LI", sortOrder: 2 },
  { name: "足阳明胃经", code: "ST", sortOrder: 3 },
  { name: "足太阴脾经", code: "SP", sortOrder: 4 },
  { name: "手少阴心经", code: "HT", sortOrder: 5 },
  { name: "手太阳小肠经", code: "SI", sortOrder: 6 },
  { name: "足太阳膀胱经", code: "BL", sortOrder: 7 },
  { name: "足少阴肾经", code: "KI", sortOrder: 8 },
  { name: "手厥阴心包经", code: "PC", sortOrder: 9 },
  { name: "手少阳三焦经", code: "TE", sortOrder: 10 },
  { name: "足少阳胆经", code: "GB", sortOrder: 11 },
  { name: "足厥阴肝经", code: "LR", sortOrder: 12 },
  { name: "督脉", code: "GV", sortOrder: 13 },
  { name: "任脉", code: "CV", sortOrder: 14 },
];

// 24 个常用经穴(数据整理自《针灸学》教材公开内容,供学习参考)
const SEED_ACUPOINTS: {
  id: string;
  name: string;
  pinyin: string;
  code: string;
  meridian: string;
  location: string;
  indications: string;
  method: string;
  special: string;
  caution: string;
  mnemonic: string;
  mnemonicExplanation: string;
  level: string;
  sortOrder: number;
}[] = [
  { id: "a_lieque", name: "列缺", pinyin: "lieque", code: "LU7", meridian: "手太阴肺经", location: "前臂桡侧缘,桡骨茎突上方,腕横纹上1.5寸", indications: "咳嗽,气喘,咽喉肿痛,偏正头痛,项强", method: "向上斜刺0.3-0.5寸", special: "络穴;八脉交会穴(通任脉)", caution: "", mnemonic: "头项寻列缺", mnemonicExplanation: "列缺为四总穴之一,善治头项部疾患", level: "一类", sortOrder: 1 },
  { id: "a_chize", name: "尺泽", pinyin: "chize", code: "LU5", meridian: "手太阴肺经", location: "肘横纹中,肱二头肌腱桡侧凹陷处", indications: "咳嗽,气喘,咯血,潮热,咽喉肿痛,肘臂挛痛", method: "直刺0.8-1.2寸;或点刺出血", special: "合穴", caution: "", mnemonic: "尺泽清肺泄热", mnemonicExplanation: "尺泽为肺经合穴,善清肺泻热", level: "二类", sortOrder: 2 },
  { id: "a_hegu", name: "合谷", pinyin: "hegu", code: "LI4", meridian: "手阳明大肠经", location: "手背,第1、2掌骨间,第2掌骨桡侧的中点处", indications: "头痛,目赤肿痛,齿痛,口眼歪斜,发热恶寒,经闭,滞产", method: "直刺0.5-1寸", special: "原穴", caution: "孕妇禁针", mnemonic: "面口合谷收", mnemonicExplanation: "合谷为四总穴之一,善治头面口齿诸疾", level: "一类", sortOrder: 3 },
  { id: "a_quchi", name: "曲池", pinyin: "quchi", code: "LI11", meridian: "手阳明大肠经", location: "屈肘成直角,肘横纹外侧端与肱骨外上髁连线中点", indications: "热病,咽喉肿痛,手臂肿痛,瘾疹,高血压,腹痛吐泻", method: "直刺1-1.5寸", special: "合穴", caution: "", mnemonic: "曲池清解热毒", mnemonicExplanation: "曲池为清热要穴,善治热病与皮肤病", level: "一类", sortOrder: 4 },
  { id: "a_zusanli", name: "足三里", pinyin: "zusanli", code: "ST36", meridian: "足阳明胃经", location: "小腿前外侧,犊鼻下3寸,胫骨前嵴外一横指", indications: "胃痛,呕吐,腹胀,泄泻,痢疾,便秘,虚劳羸瘦,下肢痿痹", method: "直刺1-2寸;强壮保健要穴", special: "合穴;胃下合穴", caution: "", mnemonic: "肚腹三里留", mnemonicExplanation: "足三里为四总穴之一,善治胃肠病,又为保健要穴", level: "一类", sortOrder: 5 },
  { id: "a_tianshu", name: "天枢", pinyin: "tianshu", code: "ST25", meridian: "足阳明胃经", location: "腹部,脐中旁开2寸", indications: "腹胀肠鸣,绕脐痛,便秘,泄泻,痢疾,月经不调", method: "直刺1-1.5寸", special: "大肠募穴", caution: "", mnemonic: "天枢调畅肠腑", mnemonicExplanation: "天枢为大肠募穴,善调肠腑气机", level: "一类", sortOrder: 6 },
  { id: "a_sanyinjiao", name: "三阴交", pinyin: "sanyinjiao", code: "SP6", meridian: "足太阴脾经", location: "小腿内侧,内踝尖上3寸,胫骨内侧缘后际", indications: "月经不调,痛经,带下,遗精,遗尿,失眠,下肢痿痹", method: "直刺1-1.5寸", special: "足三阴经交会穴", caution: "孕妇禁针", mnemonic: "三阴交调经血", mnemonicExplanation: "三阴交为肝脾肾三经交会,善治妇科诸疾", level: "一类", sortOrder: 7 },
  { id: "a_xuehai", name: "血海", pinyin: "xuehai", code: "SP10", meridian: "足太阴脾经", location: "屈膝,髌底内侧端上2寸,股内侧肌隆起处", indications: "月经不调,痛经,经闭,瘾疹,湿疹,丹毒", method: "直刺1-1.5寸", special: "", caution: "", mnemonic: "血海调血祛风", mnemonicExplanation: "血海善调血分,为治血证与皮肤病要穴", level: "一类", sortOrder: 8 },
  { id: "a_shenmen", name: "神门", pinyin: "shenmen", code: "HT7", meridian: "手少阴心经", location: "腕横纹尺侧端,尺侧腕屈肌腱的桡侧凹陷处", indications: "心痛,心烦,惊悸,怔忡,健忘,失眠,癫痫", method: "直刺0.3-0.5寸", special: "原穴;输穴", caution: "", mnemonic: "神门安神定志", mnemonicExplanation: "神门为心经原穴,善宁心安神", level: "一类", sortOrder: 9 },
  { id: "a_houxi", name: "后溪", pinyin: "houxi", code: "SI3", meridian: "手太阳小肠经", location: "微握拳,第5掌指关节尺侧后方,掌横纹头赤白肉际", indications: "头项强痛,腰背痛,手指挛痛,目赤,耳聋,癫狂痫", method: "直刺0.5-1寸", special: "输穴;八脉交会穴(通督脉)", caution: "", mnemonic: "后溪通督止项痛", mnemonicExplanation: "后溪通督脉,善治头项腰背痛", level: "一类", sortOrder: 10 },
  { id: "a_weizhong", name: "委中", pinyin: "weizhong", code: "BL40", meridian: "足太阳膀胱经", location: "腘横纹中点,当股二头肌腱与半腱肌腱的中间", indications: "腰背痛,下肢痿痹,腹痛吐泻,小便不利,丹毒", method: "直刺1-1.5寸;或点刺出血", special: "合穴;膀胱下合穴", caution: "", mnemonic: "腰背委中求", mnemonicExplanation: "委中为四总穴之一,善治腰背疾患", level: "一类", sortOrder: 11 },
  { id: "a_chengshan", name: "承山", pinyin: "chengshan", code: "BL57", meridian: "足太阳膀胱经", location: "小腿后面正中,委中与昆仑之间,伸直小腿或足跟上提时腓肠肌肌腹下尖角凹陷处", indications: "腰腿拘急疼痛,小腿转筋,痔疾,便秘", method: "直刺1-2寸", special: "", caution: "", mnemonic: "承山舒筋治痔", mnemonicExplanation: "承山善治小腿转筋与痔疾", level: "二类", sortOrder: 12 },
  { id: "a_jingming", name: "睛明", pinyin: "jingming", code: "BL1", meridian: "足太阳膀胱经", location: "目内眦角稍上方凹陷处", indications: "目赤肿痛,流泪,视物不明,近视,夜盲,色盲", method: "嘱患者闭目,医者轻推眼球向外侧固定,紧靠眶缘缓慢直刺0.5-1寸", special: "", caution: "禁灸;不宜提插捻转", mnemonic: "睛明善疗目疾", mnemonicExplanation: "睛明为治眼病要穴", level: "二类", sortOrder: 13 },
  { id: "a_yongquan", name: "涌泉", pinyin: "yongquan", code: "KI1", meridian: "足少阴肾经", location: "足底前1/3与后2/3交界处凹陷中,蜷足时足前部凹陷处", indications: "头痛,眩晕,失眠,昏厥,癫狂,咽喉肿痛,小便不利", method: "直刺0.5-1寸;可灸", special: "井穴", caution: "", mnemonic: "涌泉开窍苏厥", mnemonicExplanation: "涌泉为肾经井穴,善开窍苏厥,引火下行", level: "一类", sortOrder: 14 },
  { id: "a_taixi", name: "太溪", pinyin: "taixi", code: "KI3", meridian: "足少阴肾经", location: "内踝尖与跟腱之间的凹陷处", indications: "头痛目眩,耳鸣耳聋,咽喉肿痛,失眠,遗精阳痿,腰脊痛", method: "直刺0.5-1寸", special: "原穴;输穴", caution: "", mnemonic: "太溪补肾滋阴", mnemonicExplanation: "太溪为肾经原穴,善滋阴补肾", level: "一类", sortOrder: 15 },
  { id: "a_neiguan", name: "内关", pinyin: "neiguan", code: "PC6", meridian: "手厥阴心包经", location: "前臂掌侧,腕横纹上2寸,掌长肌腱与桡侧腕屈肌腱之间", indications: "心痛,心悸,胸闷,胃痛,呕吐,呃逆,失眠,眩晕", method: "直刺0.5-1寸", special: "络穴;八脉交会穴(通阴维脉)", caution: "", mnemonic: "内关心胸要穴", mnemonicExplanation: "内关善治心胸胃诸疾,为护心要穴", level: "一类", sortOrder: 16 },
  { id: "a_waiguan", name: "外关", pinyin: "waiguan", code: "TE5", meridian: "手少阳三焦经", location: "前臂背侧,腕背横纹上2寸,尺骨与桡骨之间", indications: "热病,头痛,目赤肿痛,耳鸣耳聋,胁肋痛,上肢痹痛", method: "直刺0.5-1寸", special: "络穴;八脉交会穴(通阳维脉)", caution: "", mnemonic: "外关解表退热", mnemonicExplanation: "外关为退热要穴,善治外感热病", level: "一类", sortOrder: 17 },
  { id: "a_fengchi", name: "风池", pinyin: "fengchi", code: "GB20", meridian: "足少阳胆经", location: "项部,枕骨之下,胸锁乳突肌与斜方肌上端之间的凹陷处", indications: "头痛,眩晕,颈项强痛,目赤肿痛,感冒,中风,癫痫", method: "针尖向鼻尖方向斜刺0.8-1.2寸", special: "", caution: "深部为延髓,忌深刺", mnemonic: "风池祛风通络", mnemonicExplanation: "风池善祛风邪,为治头风眩晕要穴", level: "一类", sortOrder: 18 },
  { id: "a_yanglingquan", name: "阳陵泉", pinyin: "yanglingquan", code: "GB34", meridian: "足少阳胆经", location: "小腿外侧,腓骨头前下方凹陷处", indications: "胁肋痛,口苦,呕吐,下肢痿痹,膝肿痛,筋脉拘挛", method: "直刺1-1.5寸", special: "合穴;筋会", caution: "", mnemonic: "阳陵筋会舒筋", mnemonicExplanation: "阳陵泉为八会穴之筋会,善治筋病", level: "一类", sortOrder: 19 },
  { id: "a_taichong", name: "太冲", pinyin: "taichong", code: "LR3", meridian: "足厥阴肝经", location: "足背,第1、2跖骨结合部前方凹陷处", indications: "头痛,眩晕,目赤肿痛,胁痛,郁证,月经不调,癫痫", method: "直刺0.5-0.8寸", special: "原穴;输穴", caution: "", mnemonic: "太冲平肝降逆", mnemonicExplanation: "太冲为肝经原穴,善平肝潜阳,疏肝理气", level: "一类", sortOrder: 20 },
  { id: "a_baihui", name: "百会", pinyin: "baihui", code: "GV20", meridian: "督脉", location: "头顶正中线与两耳尖连线的交点处", indications: "头痛,眩晕,失眠,健忘,中风失语,脱肛,阴挺,久泻", method: "平刺0.5-0.8寸;可灸", special: "督脉与足太阳经交会穴", caution: "", mnemonic: "百会升阳举陷", mnemonicExplanation: "百会为诸阳之会,善升阳举陷,醒脑开窍", level: "一类", sortOrder: 21 },
  { id: "a_dazhui", name: "大椎", pinyin: "dazhui", code: "GV14", meridian: "督脉", location: "后正中线上,第7颈椎棘突下凹陷中", indications: "热病,疟疾,咳嗽气喘,头项强痛,癫痫,骨蒸潮热", method: "斜刺0.5-1寸;可灸", special: "诸阳之会", caution: "", mnemonic: "大椎退热主表", mnemonicExplanation: "大椎为诸阳经交会穴,为退热要穴", level: "一类", sortOrder: 22 },
  { id: "a_guanyuan", name: "关元", pinyin: "guanyuan", code: "CV4", meridian: "任脉", location: "下腹部,前正中线上,脐中下3寸", indications: "遗精,阳痿,遗尿,小便频数,月经不调,虚劳羸瘦,腹痛泄泻", method: "直刺1-1.5寸;多用灸法", special: "小肠募穴;任脉与足三阴经交会穴", caution: "孕妇禁针", mnemonic: "关元培元固本", mnemonicExplanation: "关元为补肾培元要穴,多用灸法温补", level: "一类", sortOrder: 23 },
  { id: "a_zhongwan", name: "中脘", pinyin: "zhongwan", code: "CV12", meridian: "任脉", location: "上腹部,前正中线上,脐中上4寸", indications: "胃痛,腹胀,呕吐,呃逆,食积,泄泻,纳呆", method: "直刺1-1.5寸;可灸", special: "胃募穴;腑会", caution: "", mnemonic: "中脘和胃降逆", mnemonicExplanation: "中脘为胃募穴、腑会,善治胃肠诸疾", level: "一类", sortOrder: 24 },
  // ===== 数据扩充(2026-08 第二批,补齐十四经常用穴) =====
  { id: "a_zhongfu", name: "中府", pinyin: "zhongfu", code: "LU1", meridian: "手太阴肺经", location: "胸前壁外上方,前正中线旁开6寸,平第1肋间隙处", indications: "咳嗽,气喘,胸满痛,肩背痛", method: "向外斜刺或平刺0.5-0.8寸", special: "肺募穴", caution: "不可向内深刺,防伤肺脏", mnemonic: "中府肺募止咳", mnemonicExplanation: "中府为肺之募穴,善止咳平喘", level: "二类", sortOrder: 25 },
  { id: "a_taiyuan", name: "太渊", pinyin: "taiyuan", code: "LU9", meridian: "手太阴肺经", location: "腕掌侧横纹桡侧,桡动脉搏动处", indications: "咳嗽,气喘,咯血,腕臂痛,无脉症", method: "避开桡动脉,直刺0.3-0.5寸", special: "输穴;原穴;脉会", caution: "避开桡动脉", mnemonic: "太渊脉会理气", mnemonicExplanation: "太渊为肺经原穴、八会穴之脉会,善调肺气", level: "二类", sortOrder: 26 },
  { id: "a_yinlingquan", name: "阴陵泉", pinyin: "yinlingquan", code: "SP9", meridian: "足太阴脾经", location: "小腿内侧,胫骨内侧髁后下方凹陷处", indications: "腹胀,泄泻,水肿,黄疸,小便不利,膝痛", method: "直刺1-2寸", special: "合穴", caution: "", mnemonic: "阴陵利水除湿", mnemonicExplanation: "阴陵泉为利水除湿要穴,善治水肿小便不利", level: "二类", sortOrder: 27 },
  { id: "a_taibai", name: "太白", pinyin: "taibai", code: "SP3", meridian: "足太阴脾经", location: "足内侧缘,第1跖骨小头后下方赤白肉际凹陷处", indications: "胃痛,腹胀,肠鸣,泄泻,便秘,体重节痛", method: "直刺0.5-0.8寸", special: "输穴;原穴", caution: "", mnemonic: "太白健脾运化", mnemonicExplanation: "太白为脾经原穴,善健脾化湿", level: "二类", sortOrder: 28 },
  { id: "a_shaohai", name: "少海", pinyin: "shaohai", code: "HT3", meridian: "手少阴心经", location: "屈肘,肘横纹内侧端与肱骨内上髁连线的中点处", indications: "心痛,肘臂挛痛,瘰疬,头项痛", method: "直刺0.5-1寸", special: "合穴", caution: "", mnemonic: "少海清心安神", mnemonicExplanation: "少海为心经合穴,善清心安神", level: "二类", sortOrder: 29 },
  { id: "a_tongli", name: "通里", pinyin: "tongli", code: "HT5", meridian: "手少阴心经", location: "前臂掌侧,尺侧腕屈肌腱的桡侧缘,腕横纹上1寸", indications: "心悸,怔忡,暴喑,舌强不语,腕臂痛", method: "直刺0.3-0.5寸", special: "络穴", caution: "", mnemonic: "通里宁心开音", mnemonicExplanation: "通里为心经络穴,善治心悸与暴喑失语", level: "二类", sortOrder: 30 },
  { id: "a_tinggong", name: "听宫", pinyin: "tinggong", code: "SI19", meridian: "手太阳小肠经", location: "面部,耳屏前,下颌骨髁状突的后方,张口时呈凹陷处", indications: "耳鸣,耳聋,聤耳,齿痛,面痛", method: "张口,直刺0.5-1寸", special: "", caution: "留针时嘱患者勿张口", mnemonic: "听宫聪耳开窍", mnemonicExplanation: "听宫为治耳病要穴,善开窍聪耳", level: "二类", sortOrder: 31 },
  { id: "a_kunlun", name: "昆仑", pinyin: "kunlun", code: "BL60", meridian: "足太阳膀胱经", location: "足踝区,外踝尖与跟腱之间的凹陷处", indications: "头痛,项强,腰骶疼痛,足踝肿痛,难产", method: "直刺0.5-0.8寸", special: "经穴", caution: "孕妇禁针", mnemonic: "昆仑舒筋止痛", mnemonicExplanation: "昆仑善治头项腰背及足踝疾患", level: "二类", sortOrder: 32 },
  { id: "a_shenmai", name: "申脉", pinyin: "shenmai", code: "BL62", meridian: "足太阳膀胱经", location: "踝区,外踝尖直下,外踝下缘与跟骨之间凹陷处", indications: "头痛,眩晕,癫狂痫,失眠,腰腿酸痛,足外翻", method: "直刺0.3-0.5寸", special: "八脉交会穴(通阳跷脉)", caution: "", mnemonic: "申脉通跷安神", mnemonicExplanation: "申脉通阳跷脉,善治失眠癫狂与肢体活动不利", level: "二类", sortOrder: 33 },
  { id: "a_zhaohai", name: "照海", pinyin: "zhaohai", code: "KI6", meridian: "足少阴肾经", location: "踝区,内踝尖下1寸,内踝下缘边际凹陷处", indications: "失眠,癫痫,咽干咽痛,目赤肿痛,小便不利,月经不调", method: "直刺0.5-0.8寸", special: "八脉交会穴(通阴跷脉)", caution: "", mnemonic: "照海滋肾利咽", mnemonicExplanation: "照海通阴跷脉,善治咽干失眠与妇科病", level: "二类", sortOrder: 34 },
  { id: "a_daling", name: "大陵", pinyin: "daling", code: "PC7", meridian: "手厥阴心包经", location: "腕掌侧横纹中点处,当掌长肌腱与桡侧腕屈肌腱之间", indications: "心痛,心悸,胃痛,呕吐,癫狂,腕关节痛", method: "直刺0.3-0.5寸", special: "输穴;原穴", caution: "", mnemonic: "大陵宁心和胃", mnemonicExplanation: "大陵为心包经原穴,善宁心和胃", level: "二类", sortOrder: 35 },
  { id: "a_zhongzhu", name: "中渚", pinyin: "zhongzhu", code: "TE3", meridian: "手少阳三焦经", location: "手背,第4、5掌骨间,掌指关节后方凹陷处", indications: "头痛,目赤,耳鸣耳聋,咽喉肿痛,手指不能屈伸", method: "直刺0.3-0.5寸", special: "输穴", caution: "", mnemonic: "中渚清窍聪耳", mnemonicExplanation: "中渚善清头面之热,为治耳鸣要穴", level: "二类", sortOrder: 36 },
  { id: "a_jianjing", name: "肩井", pinyin: "jianjing", code: "GB21", meridian: "足少阳胆经", location: "肩胛区,第7颈椎棘突与肩峰最外侧点连线的中点", indications: "肩背痹痛,手臂不举,颈项强痛,乳痈,难产", method: "直刺0.5-0.8寸", special: "", caution: "深部为肺尖,不可深刺;孕妇禁针", mnemonic: "肩井通络止痛", mnemonicExplanation: "肩井善治肩颈疾患,为治乳痈要穴", level: "二类", sortOrder: 37 },
  { id: "a_huantiao", name: "环跳", pinyin: "huantiao", code: "GB30", meridian: "足少阳胆经", location: "臀区,股骨大转子最凸点与骶管裂孔连线的外1/3与内2/3交点处", indications: "腰胯疼痛,下肢痿痹,半身不遂,坐骨神经痛", method: "直刺2-3寸", special: "", caution: "深部邻近坐骨神经,宜缓慢进针", mnemonic: "环跳通下肢痿", mnemonicExplanation: "环跳为治下肢痿痹要穴", level: "一类", sortOrder: 38 },
  { id: "a_xuanzhong", name: "悬钟", pinyin: "xuanzhong", code: "GB39", meridian: "足少阳胆经", location: "小腿外侧,外踝尖上3寸,腓骨前缘", indications: "颈项强痛,胸胁胀痛,下肢痿痹,痴呆,中风", method: "直刺0.5-0.8寸", special: "髓会", caution: "", mnemonic: "悬钟髓会强骨", mnemonicExplanation: "悬钟为八会穴之髓会,善治颈项与下肢病", level: "二类", sortOrder: 39 },
  { id: "a_qimen", name: "期门", pinyin: "qimen", code: "LR14", meridian: "足厥阴肝经", location: "胸部,第6肋间隙,前正中线旁开4寸", indications: "胸胁胀痛,呕吐,呃逆,乳痈,郁证", method: "斜刺或平刺0.5-0.8寸", special: "肝募穴", caution: "不可深刺,防伤肝肺", mnemonic: "期门疏肝解郁", mnemonicExplanation: "期门为肝之募穴,善疏肝理气", level: "二类", sortOrder: 40 },
  { id: "a_renzhong", name: "人中", pinyin: "renzhong", code: "GV26", meridian: "督脉", location: "面部,人中沟的上1/3与中1/3交点处", indications: "昏迷,晕厥,中暑,癫狂痫,面瘫,腰脊强痛", method: "向上斜刺0.3-0.5寸", special: "", caution: "", mnemonic: "人中开窍醒神", mnemonicExplanation: "人中为急救要穴,善开窍醒神", level: "二类", sortOrder: 41 },
  { id: "a_mingmen", name: "命门", pinyin: "mingmen", code: "GV4", meridian: "督脉", location: "后正中线上,第2腰椎棘突下凹陷中", indications: "腰脊强痛,下肢痿痹,遗精阳痿,月经不调,五更泄泻", method: "直刺0.5-1寸;多用灸法", special: "", caution: "", mnemonic: "命门培元固本", mnemonicExplanation: "命门为补肾壮阳要穴,多用灸法", level: "二类", sortOrder: 42 },
  { id: "a_danzhong", name: "膻中", pinyin: "danzhong", code: "CV17", meridian: "任脉", location: "胸部,前正中线上,平第4肋间,两乳头连线的中点", indications: "胸闷气短,心悸,心痛,咳嗽气喘,乳少,呃逆", method: "平刺0.3-0.5寸", special: "心包募穴;气会", caution: "", mnemonic: "膻中宽胸理气", mnemonicExplanation: "膻中为气会,善理气宽胸,为治气病要穴", level: "二类", sortOrder: 43 },
  { id: "a_qihai", name: "气海", pinyin: "qihai", code: "CV6", meridian: "任脉", location: "下腹部,前正中线上,脐中下1.5寸", indications: "腹痛,泄泻,便秘,遗尿,遗精阳痿,月经不调,虚脱", method: "直刺1-1.5寸;多用灸法", special: "肓之原", caution: "孕妇禁针", mnemonic: "气海补气要穴", mnemonicExplanation: "气海为补气要穴,善治气虚下陷诸证", level: "二类", sortOrder: 44 },
  { id: "a_tiantu", name: "天突", pinyin: "tiantu", code: "CV22", meridian: "任脉", location: "颈前区,胸骨上窝中央,前正中线上", indications: "咳嗽,气喘,咽喉肿痛,梅核气,暴喑,瘿气", method: "先直刺0.2寸,再沿胸骨柄后缘向下刺1-1.5寸", special: "", caution: "严格掌握进针方向与深度,防伤大血管", mnemonic: "天突利咽平喘", mnemonicExplanation: "天突善利咽下气,为治咳喘要穴", level: "二类", sortOrder: 45 },
  { id: "a_shangjuxu", name: "上巨虚", pinyin: "shangjuxu", code: "ST37", meridian: "足阳明胃经", location: "小腿前外侧,犊鼻下6寸,胫骨前嵴外一横指", indications: "肠鸣,腹痛,泄泻,便秘,肠痈,下肢痿痹", method: "直刺1-2寸", special: "大肠下合穴", caution: "", mnemonic: "上巨调肠下合", mnemonicExplanation: "上巨虚为大肠下合穴,善治肠腑诸疾", level: "二类", sortOrder: 46 },
  { id: "a_neiting", name: "内庭", pinyin: "neiting", code: "ST44", meridian: "足阳明胃经", location: "足背,第2、3趾间,趾蹼缘后方赤白肉际处", indications: "齿痛,咽喉肿痛,口歪,鼻衄,胃病吐酸,腹胀泄泻", method: "直刺或斜刺0.5-0.8寸", special: "荥穴", caution: "", mnemonic: "内庭清胃泻火", mnemonicExplanation: "内庭为胃经荥穴,善清胃火,治牙痛口臭", level: "二类", sortOrder: 47 },
  { id: "a_touwei", name: "头维", pinyin: "touwei", code: "ST8", meridian: "足阳明胃经", location: "头部,额角发际直上0.5寸,头正中线旁开4.5寸", indications: "头痛,目眩,目赤肿痛,迎风流泪,视物不明", method: "平刺0.5-1寸", special: "", caution: "", mnemonic: "头维清头明目", mnemonicExplanation: "头维善治头目疾患,为止头痛要穴", level: "二类", sortOrder: 48 },
  { id: "a_shaoshang", name: "少商", pinyin: "shaoshang", code: "LU11", meridian: "手太阴肺经", location: "拇指末节桡侧,指甲根角侧上方0.1寸", indications: "咽喉肿痛,咳嗽,鼻衄,发热,昏迷,癫狂", method: "浅刺0.1寸;或点刺出血", special: "井穴", caution: "", mnemonic: "少商利咽开窍", mnemonicExplanation: "少商为肺经井穴,点刺出血善治咽痛昏迷", level: "二类", sortOrder: 49 },
  { id: "a_yinbai", name: "隐白", pinyin: "yinbai", code: "SP1", meridian: "足太阴脾经", location: "足大趾末节内侧,趾甲根角侧后方0.1寸", indications: "月经过多,崩漏,便血,尿血,癫狂,多梦,惊风", method: "浅刺0.1寸;或点刺出血", special: "井穴", caution: "", mnemonic: "隐白统血止崩", mnemonicExplanation: "隐白为脾经井穴,善统血止崩漏", level: "二类", sortOrder: 50 },
  { id: "a_xiaochangshu", name: "小肠俞", pinyin: "xiaochangshu", code: "BL27", meridian: "足太阳膀胱经", location: "骶区,横平第1骶后孔,骶正中嵴旁开1.5寸", indications: "小腹胀痛,泄泻痢疾,遗精遗尿,腰骶痛,带下", method: "直刺0.8-1.2寸", special: "小肠背俞穴", caution: "", mnemonic: "小肠俞调肠腑", mnemonicExplanation: "小肠俞为小肠背俞穴,善调肠腑泌尿", level: "二类", sortOrder: 51 },
  { id: "a_shenshu", name: "肾俞", pinyin: "shenshu", code: "BL23", meridian: "足太阳膀胱经", location: "腰部,第2腰椎棘突下,旁开1.5寸", indications: "腰痛,遗精阳痿,遗尿,月经不调,耳鸣耳聋,水肿", method: "直刺0.8-1.2寸;可灸", special: "肾背俞穴", caution: "", mnemonic: "肾俞补肾固精", mnemonicExplanation: "肾俞为肾之背俞穴,善补肾壮腰固精", level: "一类", sortOrder: 52 },
  { id: "a_pishu", name: "脾俞", pinyin: "pishu", code: "BL20", meridian: "足太阳膀胱经", location: "背部,第11胸椎棘突下,旁开1.5寸", indications: "腹胀,呕吐,泄泻,痢疾,便血,水肿,背痛", method: "斜刺0.5-0.8寸;可灸", special: "脾背俞穴", caution: "不宜深刺,防伤内脏", mnemonic: "脾俞健脾化湿", mnemonicExplanation: "脾俞为脾之背俞穴,善健脾益气化湿", level: "二类", sortOrder: 53 },
  { id: "a_geshu", name: "膈俞", pinyin: "geshu", code: "BL17", meridian: "足太阳膀胱经", location: "背部,第7胸椎棘突下,旁开1.5寸", indications: "呕吐,呃逆,气喘,吐血,贫血,瘾疹,皮肤瘙痒", method: "斜刺0.5-0.8寸", special: "血会", caution: "不宜深刺", mnemonic: "膈俞血会活血", mnemonicExplanation: "膈俞为八会穴之血会,善治血证", level: "二类", sortOrder: 54 },
  { id: "a_xinshu", name: "心俞", pinyin: "xinshu", code: "BL15", meridian: "足太阳膀胱经", location: "背部,第5胸椎棘突下,旁开1.5寸", indications: "心痛,惊悸,失眠,健忘,癫痫,咳嗽吐血", method: "斜刺0.5-0.8寸", special: "心背俞穴", caution: "不宜深刺", mnemonic: "心俞宁心安神", mnemonicExplanation: "心俞为心之背俞穴,善宁心安神", level: "二类", sortOrder: 55 },
  { id: "a_dachangshu", name: "大肠俞", pinyin: "dachangshu", code: "BL25", meridian: "足太阳膀胱经", location: "腰部,第4腰椎棘突下,旁开1.5寸", indications: "腰腿痛,腹胀,泄泻,便秘,痢疾,痔疾", method: "直刺0.8-1.2寸", special: "大肠背俞穴", caution: "", mnemonic: "大肠俞调肠腰", mnemonicExplanation: "大肠俞为大肠背俞穴,善治肠腑与腰腿病", level: "二类", sortOrder: 56 },
  { id: "a_fuliu", name: "复溜", pinyin: "fuliu", code: "KI7", meridian: "足少阴肾经", location: "小腿内侧,太溪直上2寸,跟腱前缘", indications: "水肿,腹胀,泄泻,盗汗,汗出不止,腰脊强痛,下肢痿痹", method: "直刺0.5-1寸", special: "经穴", caution: "", mnemonic: "复溜利水止汗", mnemonicExplanation: "复溜善利水消肿,又能敛汗", level: "二类", sortOrder: 57 },
  { id: "a_dadu", name: "大都", pinyin: "dadu", code: "SP2", meridian: "足太阴脾经", location: "足趾,第1跖趾关节远端赤白肉际凹陷处", indications: "胃痛,腹胀,呕吐,泄泻,便秘,热病无汗", method: "直刺0.3-0.5寸", special: "荥穴", caution: "", mnemonic: "大都健脾和胃", mnemonicExplanation: "大都为脾经荥穴,善健脾和胃", level: "二类", sortOrder: 58 },
  { id: "a_guanyuanshu", name: "关元俞", pinyin: "guanyuanshu", code: "BL26", meridian: "足太阳膀胱经", location: "腰部,第5腰椎棘突下,旁开1.5寸", indications: "腰骶痛,腹胀泄泻,小便不利,遗尿,月经不调", method: "直刺0.8-1.2寸", special: "", caution: "", mnemonic: "关元俞补肾腰", mnemonicExplanation: "关元俞善治腰骶部疾患与泌尿生殖病", level: "二类", sortOrder: 59 },
  { id: "a_changqiang", name: "长强", pinyin: "changqiang", code: "GV1", meridian: "督脉", location: "尾骨下方,尾骨端与肛门连线的中点处", indications: "泄泻,痢疾,便秘,便血,痔疾,脱肛,癫狂痫,腰脊强痛", method: "斜刺,针尖向上与骶骨平行刺入0.5-1寸", special: "络穴", caution: "不宜直刺深刺", mnemonic: "长强通督治痔", mnemonicExplanation: "长强为督脉络穴,善治痔疾脱肛", level: "二类", sortOrder: 60 },
  // ===== 腧穴扩充(2026-08,补齐十四经常用穴至 150+) =====
  { id: "a_kongzui", name: "孔最", pinyin: "kongzui", code: "LU6", meridian: "手太阴肺经", location: "前臂前区,腕掌侧远端横纹上7寸,太渊与尺泽连线上", indications: "咯血,咳嗽,气喘,咽喉肿痛,肘臂挛痛", method: "直刺0.5-1寸", special: "郄穴", caution: "", mnemonic: "孔最止血要穴", mnemonicExplanation: "孔最为肺经郄穴,善治咯血", level: "二类", sortOrder: 61 },
  { id: "a_yuji", name: "鱼际", pinyin: "yuji", code: "LU10", meridian: "手太阴肺经", location: "手外侧,第1掌骨桡侧中点赤白肉际处", indications: "咳嗽,咯血,咽喉肿痛,失音,发热", method: "直刺0.5-0.8寸", special: "荥穴", caution: "", mnemonic: "鱼际清肺利咽", mnemonicExplanation: "鱼际为肺经荥穴,善清肺热利咽喉", level: "二类", sortOrder: 62 },
  { id: "a_shangyang", name: "商阳", pinyin: "shangyang", code: "LI1", meridian: "手阳明大肠经", location: "食指末节桡侧,指甲根角侧上方0.1寸", indications: "咽喉肿痛,齿痛,耳聋,热病昏迷,手指麻木", method: "浅刺0.1寸;或点刺出血", special: "井穴", caution: "", mnemonic: "商阳开窍利咽", mnemonicExplanation: "商阳为大肠经井穴,点刺出血治咽痛昏迷", level: "二类", sortOrder: 63 },
  { id: "a_sanjian", name: "三间", pinyin: "sanjian", code: "LI3", meridian: "手阳明大肠经", location: "手背,第2掌指关节桡侧近端凹陷处", indications: "齿痛,咽喉肿痛,目痛,腹胀,手指肿痛", method: "直刺0.3-0.5寸", special: "输穴", caution: "", mnemonic: "三间泻热止痛", mnemonicExplanation: "三间善泻阳明热邪,治齿痛咽肿", level: "二类", sortOrder: 64 },
  { id: "a_pianli", name: "偏历", pinyin: "pianli", code: "LI6", meridian: "手阳明大肠经", location: "前臂,腕背侧远端横纹上3寸,阳溪与曲池连线上", indications: "耳鸣,鼻衄,齿痛,目赤,水肿,手臂酸痛", method: "斜刺0.5-0.8寸", special: "络穴", caution: "", mnemonic: "偏历通络利水", mnemonicExplanation: "偏历为大肠经络穴,善治五官病与水肿", level: "二类", sortOrder: 65 },
  { id: "a_shousanli", name: "手三里", pinyin: "shousanli", code: "LI10", meridian: "手阳明大肠经", location: "前臂,肘横纹下2寸,阳溪与曲池连线上", indications: "肘臂疼痛,上肢麻木,腹痛腹泻,齿痛", method: "直刺0.8-1.2寸", special: "", caution: "", mnemonic: "手三里通络", mnemonicExplanation: "手三里善治肘臂不举与胃肠病", level: "二类", sortOrder: 66 },
  { id: "a_binao", name: "臂臑", pinyin: "binao", code: "LI14", meridian: "手阳明大肠经", location: "臂部,曲池上7寸,三角肌前缘处", indications: "肩臂疼痛,颈项拘挛,瘰疬,目疾", method: "直刺或斜刺0.8-1.5寸", special: "", caution: "", mnemonic: "臂臑通肩止痛", mnemonicExplanation: "臂臑善治肩臂疼痛与颈项拘急", level: "二类", sortOrder: 67 },
  { id: "a_yingxiang", name: "迎香", pinyin: "yingxiang", code: "LI20", meridian: "手阳明大肠经", location: "面部,鼻翼外缘中点旁,鼻唇沟中", indications: "鼻塞,鼻衄,鼻渊,口歪,面痒", method: "斜刺或平刺0.3-0.5寸", special: "", caution: "", mnemonic: "迎香通鼻要穴", mnemonicExplanation: "迎香善通鼻窍,为治鼻病要穴", level: "二类", sortOrder: 68 },
  { id: "a_jianyu", name: "肩髃", pinyin: "jianyu", code: "LI15", meridian: "手阳明大肠经", location: "肩峰前下方,当肩峰与肱骨大结节之间凹陷处", indications: "肩臂挛痛,上肢不遂,瘾疹,瘰疬", method: "直刺或向下斜刺0.8-1.5寸", special: "", caution: "", mnemonic: "肩髃肩痛要穴", mnemonicExplanation: "肩髃为治肩周炎(肩凝)要穴", level: "二类", sortOrder: 69 },
  { id: "a_yangxi", name: "阳溪", pinyin: "yangxi", code: "LI5", meridian: "手阳明大肠经", location: "腕背横纹桡侧,拇指向上翘起时,拇短伸肌腱与拇长伸肌腱之间的凹陷处", indications: "头痛,目赤肿痛,耳聋,齿痛,腕臂痛", method: "直刺0.5-0.8寸", special: "经穴", caution: "", mnemonic: "阳溪清头明目", mnemonicExplanation: "阳溪善清阳明郁热,治头面五官病", level: "二类", sortOrder: 70 },
  { id: "a_chengqi", name: "承泣", pinyin: "chengqi", code: "ST1", meridian: "足阳明胃经", location: "面部,瞳孔直下,眼球与眶下缘之间", indications: "目赤肿痛,流泪,夜盲,眼睑瞤动,口眼歪斜", method: "嘱患者闭目,医者以左手拇指向上轻推眼球,紧靠眶下缘缓慢直刺0.5-1寸", special: "", caution: "不宜提插,防刺伤眼球", mnemonic: "承泣明目要穴", mnemonicExplanation: "承泣为治眼病要穴", level: "二类", sortOrder: 71 },
  { id: "a_dicang", name: "地仓", pinyin: "dicang", code: "ST4", meridian: "足阳明胃经", location: "面部,口角旁开0.4寸", indications: "口歪,流涎,眼睑瞤动,齿痛颊肿", method: "斜刺或平刺0.5-0.8寸", special: "", caution: "", mnemonic: "地仓治口歪", mnemonicExplanation: "地仓善治口角歪斜流涎,为面瘫要穴", level: "二类", sortOrder: 72 },
  { id: "a_jiache", name: "颊车", pinyin: "jiache", code: "ST6", meridian: "足阳明胃经", location: "面部,下颌角前上方约一横指,咀嚼时咬肌隆起处", indications: "口歪,齿痛,颊肿,牙关紧闭,口噤不语", method: "直刺0.3-0.5寸;或平刺0.5-1寸", special: "", caution: "", mnemonic: "颊车开噤止痛", mnemonicExplanation: "颊车善治牙关紧闭与齿痛颊肿", level: "二类", sortOrder: 73 },
  { id: "a_xiaguan", name: "下关", pinyin: "xiaguan", code: "ST7", meridian: "足阳明胃经", location: "面部,颧弓下缘中央与下颌切迹之间的凹陷中", indications: "牙关不利,齿痛,面痛,口眼歪斜,耳鸣耳聋", method: "直刺0.5-1寸", special: "", caution: "", mnemonic: "下关通窍止痛", mnemonicExplanation: "下关善治颞下颌关节疾患与齿痛", level: "二类", sortOrder: 74 },
  { id: "a_liangmen", name: "梁门", pinyin: "liangmen", code: "ST21", meridian: "足阳明胃经", location: "上腹部,脐中上4寸,前正中线旁开2寸", indications: "胃痛,呕吐,食欲不振,腹胀,泄泻", method: "直刺0.8-1.2寸", special: "", caution: "", mnemonic: "梁门和胃消食", mnemonicExplanation: "梁门善治胃脘痛与食欲不振", level: "二类", sortOrder: 75 },
  { id: "a_dubi", name: "犊鼻", pinyin: "dubi", code: "ST35", meridian: "足阳明胃经", location: "膝前区,髌韧带外侧凹陷中", indications: "膝痛,屈伸不利,下肢麻痹,脚气", method: "向后内斜刺0.5-1寸", special: "", caution: "", mnemonic: "犊鼻治膝要穴", mnemonicExplanation: "犊鼻(外膝眼)为治膝痛要穴", level: "二类", sortOrder: 76 },
  { id: "a_fenglong", name: "丰隆", pinyin: "fenglong", code: "ST40", meridian: "足阳明胃经", location: "小腿外侧,外踝尖上8寸,胫骨前嵴外二横指", indications: "痰多咳嗽,头痛眩晕,癫狂痫,下肢痿痹,便秘", method: "直刺1-1.5寸", special: "络穴", caution: "", mnemonic: "丰隆化痰要穴", mnemonicExplanation: "丰隆为化痰要穴,善治一切痰证", level: "一类", sortOrder: 77 },
  { id: "a_liangqiu", name: "梁丘", pinyin: "liangqiu", code: "ST34", meridian: "足阳明胃经", location: "股前区,髌底上2寸,股外侧肌与股直肌肌腱之间", indications: "急性胃痛,膝肿痛,下肢不遂,乳痈", method: "直刺1-1.2寸", special: "郄穴", caution: "", mnemonic: "梁丘急痛要穴", mnemonicExplanation: "梁丘为胃经郄穴,善治急性胃痛", level: "二类", sortOrder: 78 },
  { id: "a_tiaokou", name: "条口", pinyin: "tiaokou", code: "ST38", meridian: "足阳明胃经", location: "小腿外侧,犊鼻下8寸,胫骨前嵴外一横指", indications: "肩臂痛,下肢痿痹,转筋,脘腹疼痛", method: "直刺1-1.5寸", special: "", caution: "", mnemonic: "条口治肩痛", mnemonicExplanation: "条口透承山,善治肩凝与下肢痹痛", level: "二类", sortOrder: 79 },
  { id: "a_jiexi", name: "解溪", pinyin: "jiexi", code: "ST41", meridian: "足阳明胃经", location: "踝区,踝关节前面中央凹陷中,拇长伸肌腱与趾长伸肌腱之间", indications: "头痛,眩晕,癫狂,腹胀便秘,踝关节痛", method: "直刺0.5-1寸", special: "经穴", caution: "", mnemonic: "解溪清胃通络", mnemonicExplanation: "解溪善清胃热,治踝部疾患", level: "二类", sortOrder: 80 },
  { id: "a_lidui", name: "厉兑", pinyin: "lidui", code: "ST45", meridian: "足阳明胃经", location: "足第2趾末节外侧,趾甲根角侧后方0.1寸", indications: "鼻衄,齿痛,咽喉肿痛,热病,多梦,癫狂", method: "浅刺0.1寸", special: "井穴", caution: "", mnemonic: "厉兑清胃醒神", mnemonicExplanation: "厉兑为胃经井穴,点刺出血清胃热", level: "二类", sortOrder: 81 },
  { id: "a_gongsun", name: "公孙", pinyin: "gongsun", code: "SP4", meridian: "足太阴脾经", location: "跖区,第1跖骨基底部的前下方赤白肉际处", indications: "胃痛,呕吐,腹痛泄泻,痢疾,心烦失眠", method: "直刺0.6-1.2寸", special: "络穴;八脉交会穴(通冲脉)", caution: "", mnemonic: "公孙和胃止呕", mnemonicExplanation: "公孙通冲脉,善治脾胃病与心痛", level: "二类", sortOrder: 82 },
  { id: "a_shangqiu", name: "商丘", pinyin: "shangqiu", code: "SP5", meridian: "足太阴脾经", location: "踝区,内踝前下方,舟骨粗隆与内踝尖连线中点凹陷处", indications: "腹胀,泄泻,便秘,黄疸,足踝痛", method: "直刺0.5-0.8寸", special: "经穴", caution: "", mnemonic: "商丘健脾利湿", mnemonicExplanation: "商丘善健脾化湿,治脾胃与踝部病", level: "二类", sortOrder: 83 },
  { id: "a_dabao", name: "大包", pinyin: "dabao", code: "SP21", meridian: "足太阴脾经", location: "胸外侧区,第6肋间隙,腋中线上", indications: "胸胁痛,气喘,全身疼痛,四肢无力", method: "斜刺或平刺0.5-0.8寸", special: "脾之大络", caution: "不可深刺,防伤肺脏", mnemonic: "大包通络宽胸", mnemonicExplanation: "大包为脾之大络,善治胸胁痛与全身疼痛", level: "二类", sortOrder: 84 },
  { id: "a_jiquan", name: "极泉", pinyin: "jiquan", code: "HT1", meridian: "手少阴心经", location: "腋窝中央,腋动脉搏动处", indications: "心痛,心悸,胁肋疼痛,上肢麻木不遂", method: "避开腋动脉,直刺0.5-1寸", special: "", caution: "避开腋动脉", mnemonic: "极泉宽胸宁心", mnemonicExplanation: "极泉善治心胸痹痛与上肢不遂", level: "二类", sortOrder: 85 },
  { id: "a_shaochong", name: "少冲", pinyin: "shaochong", code: "HT9", meridian: "手少阴心经", location: "小指末节桡侧,指甲根角侧上方0.1寸", indications: "心悸,心痛,癫狂,热病昏迷,胸胁痛", method: "浅刺0.1寸;或点刺出血", special: "井穴", caution: "", mnemonic: "少冲开窍醒神", mnemonicExplanation: "少冲为心经井穴,急救开窍醒神", level: "二类", sortOrder: 86 },
  { id: "a_yinxi", name: "阴郄", pinyin: "yinxi", code: "HT6", meridian: "手少阴心经", location: "前臂前区,腕掌侧远端横纹上0.5寸,尺侧腕屈肌腱桡侧缘", indications: "心痛,惊悸,骨蒸盗汗,吐血衄血,暴喑", method: "直刺0.3-0.5寸", special: "郄穴", caution: "", mnemonic: "阴郄止汗要穴", mnemonicExplanation: "阴郄为心经郄穴,善治盗汗与心痛", level: "二类", sortOrder: 87 },
  { id: "a_shaoze", name: "少泽", pinyin: "shaoze", code: "SI1", meridian: "手太阳小肠经", location: "小指末节尺侧,指甲根角侧上方0.1寸", indications: "乳汁不足,乳痈,昏迷,热病,咽喉肿痛", method: "浅刺0.1寸;或点刺出血", special: "井穴", caution: "", mnemonic: "少泽通乳要穴", mnemonicExplanation: "少泽为通乳要穴,点刺出血治乳少乳痈", level: "二类", sortOrder: 88 },
  { id: "a_yanglao", name: "养老", pinyin: "yanglao", code: "SI6", meridian: "手太阳小肠经", location: "前臂后区,腕背横纹上1寸,尺骨头桡侧凹陷中", indications: "目视不明,肩背肘臂酸痛,急性腰痛", method: "以掌心向胸,向肘方向斜刺0.5-0.8寸", special: "郄穴", caution: "", mnemonic: "养老明目止痛", mnemonicExplanation: "养老善治目视不明与肩背腰痛", level: "二类", sortOrder: 89 },
  { id: "a_tianzong", name: "天宗", pinyin: "tianzong", code: "SI11", meridian: "手太阳小肠经", location: "肩胛区,肩胛冈中点与肩胛骨下角连线上1/3与下2/3交点凹陷处", indications: "肩胛疼痛,肩背部损伤,气喘,乳痈", method: "直刺或斜刺0.5-1寸", special: "", caution: "", mnemonic: "天宗肩胛要穴", mnemonicExplanation: "天宗善治肩胛痛,为肩背要穴", level: "二类", sortOrder: 90 },
  { id: "a_xiaohai", name: "小海", pinyin: "xiaohai", code: "SI8", meridian: "手太阳小肠经", location: "肘后区,尺骨鹰嘴与肱骨内上髁之间凹陷处", indications: "肘臂疼痛,麻木,癫痫,耳聋耳鸣", method: "直刺0.3-0.5寸", special: "合穴", caution: "", mnemonic: "小海通络定痫", mnemonicExplanation: "小海为小肠经合穴,治肘臂病与癫痫", level: "二类", sortOrder: 91 },
  { id: "a_quanliao", name: "颧髎", pinyin: "quanliao", code: "SI18", meridian: "手太阳小肠经", location: "面部,目外眦直下,颧骨下缘凹陷处", indications: "口眼歪斜,眼睑瞤动,齿痛,面痛,颊肿", method: "直刺0.3-0.5寸", special: "", caution: "", mnemonic: "颧髎治面瘫", mnemonicExplanation: "颧髎善治面瘫与三叉神经痛", level: "二类", sortOrder: 92 },
  { id: "a_cuanzhu", name: "攒竹", pinyin: "cuanzhu", code: "BL2", meridian: "足太阳膀胱经", location: "面部,眉头凹陷中,额切迹处", indications: "头痛,眉棱骨痛,目赤肿痛,眼睑瞤动,鼻塞", method: "平刺0.5-0.8寸", special: "", caution: "禁灸", mnemonic: "攒竹明目止痛", mnemonicExplanation: "攒竹善治头痛目疾与眼睑瞤动", level: "二类", sortOrder: 93 },
  { id: "a_tianzhu", name: "天柱", pinyin: "tianzhu", code: "BL10", meridian: "足太阳膀胱经", location: "颈后区,横平第2颈椎棘突上际,斜方肌外缘凹陷中", indications: "头痛,项强,眩晕,目赤肿痛,肩背痛", method: "直刺或斜刺0.5-0.8寸", special: "", caution: "不可向内上方深刺,防伤延髓", mnemonic: "天柱清头明目", mnemonicExplanation: "天柱善治头项强痛与目疾", level: "二类", sortOrder: 94 },
  { id: "a_fengmen", name: "风门", pinyin: "fengmen", code: "BL12", meridian: "足太阳膀胱经", location: "背部,第2胸椎棘突下,旁开1.5寸", indications: "感冒,咳嗽,发热头痛,项强,胸背痛", method: "斜刺0.5-0.8寸;可灸", special: "", caution: "不宜深刺", mnemonic: "风门祛风解表", mnemonicExplanation: "风门为祛风要穴,善治外感风寒", level: "二类", sortOrder: 95 },
  { id: "a_feishu", name: "肺俞", pinyin: "feishu", code: "BL13", meridian: "足太阳膀胱经", location: "背部,第3胸椎棘突下,旁开1.5寸", indications: "咳嗽,气喘,咯血,鼻塞,骨蒸潮热,盗汗", method: "斜刺0.5-0.8寸;可灸", special: "肺背俞穴", caution: "不宜深刺", mnemonic: "肺俞止咳平喘", mnemonicExplanation: "肺俞为肺之背俞穴,善治肺系诸疾", level: "一类", sortOrder: 96 },
  { id: "a_ganshu", name: "肝俞", pinyin: "ganshu", code: "BL18", meridian: "足太阳膀胱经", location: "背部,第9胸椎棘突下,旁开1.5寸", indications: "胁痛,黄疸,目赤,视物不明,眩晕,癫狂痫", method: "斜刺0.5-0.8寸", special: "肝背俞穴", caution: "不宜深刺", mnemonic: "肝俞疏肝明目", mnemonicExplanation: "肝俞为肝之背俞穴,善治肝胆与目疾", level: "二类", sortOrder: 97 },
  { id: "a_danshu", name: "胆俞", pinyin: "danshu", code: "BL19", meridian: "足太阳膀胱经", location: "背部,第10胸椎棘突下,旁开1.5寸", indications: "黄疸,口苦,胁痛,肺痨潮热,呕吐", method: "斜刺0.5-0.8寸", special: "胆背俞穴", caution: "不宜深刺", mnemonic: "胆俞利胆退黄", mnemonicExplanation: "胆俞为胆之背俞穴,善治胆病黄疸", level: "二类", sortOrder: 98 },
  { id: "a_weishu", name: "胃俞", pinyin: "weishu", code: "BL21", meridian: "足太阳膀胱经", location: "背部,第12胸椎棘突下,旁开1.5寸", indications: "胃脘痛,呕吐,腹胀肠鸣,胸胁痛,消化不良", method: "斜刺0.5-0.8寸;可灸", special: "胃背俞穴", caution: "不宜深刺", mnemonic: "胃俞和胃止痛", mnemonicExplanation: "胃俞为胃之背俞穴,善治胃脘诸疾", level: "二类", sortOrder: 99 },
  { id: "a_sanjiaoshu", name: "三焦俞", pinyin: "sanjiaoshu", code: "BL22", meridian: "足太阳膀胱经", location: "腰部,第1腰椎棘突下,旁开1.5寸", indications: "肠鸣腹胀,呕吐泄泻,水肿,腰背强痛", method: "直刺0.8-1.2寸", special: "三焦背俞穴", caution: "", mnemonic: "三焦俞利水道", mnemonicExplanation: "三焦俞为三焦背俞穴,善调水道", level: "二类", sortOrder: 100 },
  { id: "a_pangguangshu", name: "膀胱俞", pinyin: "pangguangshu", code: "BL28", meridian: "足太阳膀胱经", location: "骶区,横平第2骶后孔,骶正中嵴旁开1.5寸", indications: "小便不利,遗尿,泄泻,便秘,腰骶疼痛", method: "直刺0.8-1.2寸", special: "膀胱背俞穴", caution: "", mnemonic: "膀胱俞调水道", mnemonicExplanation: "膀胱俞为膀胱背俞穴,善治小便不利", level: "二类", sortOrder: 101 },
  { id: "a_zhubian", name: "秩边", pinyin: "zhubian", code: "BL54", meridian: "足太阳膀胱经", location: "骶区,横平第4骶后孔,骶正中嵴旁开3寸", indications: "腰骶痛,下肢痿痹,小便不利,痔疾,便秘", method: "直刺1.5-2寸", special: "", caution: "", mnemonic: "秩边通络止痛", mnemonicExplanation: "秩边善治腰骶与下肢疾患", level: "二类", sortOrder: 102 },
  { id: "a_chengfu", name: "承扶", pinyin: "chengfu", code: "BL36", meridian: "足太阳膀胱经", location: "臀部,臀沟中点处", indications: "腰骶臀股疼痛,痔疾,下肢痿痹", method: "直刺1-2寸", special: "", caution: "", mnemonic: "承扶通络治痔", mnemonicExplanation: "承扶善治腰臀腿痛与痔疾", level: "二类", sortOrder: 103 },
  { id: "a_dazhu", name: "大杼", pinyin: "dazhu", code: "BL11", meridian: "足太阳膀胱经", location: "背部,第1胸椎棘突下,旁开1.5寸", indications: "咳嗽,发热,项强,肩背痛,骨病", method: "斜刺0.5-0.8寸", special: "八会穴之骨会", caution: "不宜深刺", mnemonic: "大杼骨会强骨", mnemonicExplanation: "大杼为八会穴之骨会,善治骨病", level: "二类", sortOrder: 104 },
  { id: "a_gaohuang", name: "膏肓", pinyin: "gaohuang", code: "BL43", meridian: "足太阳膀胱经", location: "背部,第4胸椎棘突下,旁开3寸", indications: "肺痨,咳嗽气喘,盗汗,健忘,遗精,虚劳羸瘦", method: "斜刺0.5-0.8寸;多用灸法", special: "", caution: "不宜深刺", mnemonic: "膏肓补虚要穴", mnemonicExplanation: "膏肓善治虚劳羸瘦,为强壮要穴", level: "二类", sortOrder: 105 },
  { id: "a_feiyang", name: "飞扬", pinyin: "feiyang", code: "BL58", meridian: "足太阳膀胱经", location: "小腿后区,昆仑直上7寸,腓肠肌外下缘与跟腱移行处", indications: "头痛,目眩,鼻塞,腰腿痛,痔疾", method: "直刺1-1.5寸", special: "络穴", caution: "", mnemonic: "飞扬通络止痛", mnemonicExplanation: "飞扬为膀胱经络穴,善治腰腿痛", level: "二类", sortOrder: 106 },
  { id: "a_jinggu", name: "京骨", pinyin: "jinggu", code: "BL64", meridian: "足太阳膀胱经", location: "跖区,第5跖骨粗隆前下方,赤白肉际处", indications: "头痛,项强,腰腿痛,癫痫,目翳", method: "直刺0.3-0.5寸", special: "原穴", caution: "", mnemonic: "京骨通络止痛", mnemonicExplanation: "京骨为膀胱经原穴,善治头项腰腿痛", level: "二类", sortOrder: 107 },
  { id: "a_zhiyin", name: "至阴", pinyin: "zhiyin", code: "BL67", meridian: "足太阳膀胱经", location: "足小趾末节外侧,趾甲根角侧后方0.1寸", indications: "胎位不正,难产,头痛,目痛,鼻塞,鼻衄", method: "浅刺0.1寸;灸法用于矫正胎位", special: "井穴", caution: "孕妇禁针(灸可矫正胎位)", mnemonic: "至阴矫正胎位", mnemonicExplanation: "至阴为矫正胎位要穴(艾灸)", level: "二类", sortOrder: 108 },
  { id: "a_rangu", name: "然谷", pinyin: "rangu", code: "KI2", meridian: "足少阴肾经", location: "足内侧,舟骨粗隆下方,赤白肉际处", indications: "月经不调,遗精,阳痿,消渴,咽喉肿痛,足跗痛", method: "直刺0.5-0.8寸", special: "荥穴", caution: "", mnemonic: "然谷滋肾清热", mnemonicExplanation: "然谷为肾经荥穴,善滋阴清热", level: "二类", sortOrder: 109 },
  { id: "a_dazhong", name: "大钟", pinyin: "dazhong", code: "KI4", meridian: "足少阴肾经", location: "跟区,内踝后下方,跟腱附着部内侧前方凹陷处", indications: "癃闭,遗尿,便秘,痴呆,足跟痛,气喘", method: "直刺0.3-0.5寸", special: "络穴", caution: "", mnemonic: "大钟通络益肾", mnemonicExplanation: "大钟为肾经络穴,善治肾虚诸证", level: "二类", sortOrder: 110 },
  { id: "a_yingu", name: "阴谷", pinyin: "yingu", code: "KI10", meridian: "足少阴肾经", location: "膝后区,腘横纹上,半腱肌腱外侧缘", indications: "阳痿,疝痛,崩漏,小便不利,膝股内侧痛", method: "直刺1-1.5寸", special: "合穴", caution: "", mnemonic: "阴谷补肾利水", mnemonicExplanation: "阴谷为肾经合穴,善治肾虚与小便不利", level: "二类", sortOrder: 111 },
  { id: "a_zhubin", name: "筑宾", pinyin: "zhubin", code: "KI9", meridian: "足少阴肾经", location: "小腿内侧,太溪直上5寸,比目鱼肌与跟腱之间", indications: "癫狂痫,呕吐涎沫,疝痛,小腿内侧痛", method: "直刺1-1.5寸", special: "阴维脉郄穴", caution: "", mnemonic: "筑宾定痫止呕", mnemonicExplanation: "筑宾为阴维脉郄穴,善治癫狂与呕吐", level: "二类", sortOrder: 112 },
  { id: "a_yufu", name: "俞府", pinyin: "yufu", code: "KI27", meridian: "足少阴肾经", location: "胸部,锁骨下缘,前正中线旁开2寸", indications: "咳嗽,气喘,胸痛,呕吐,不嗜食", method: "斜刺或平刺0.5-0.8寸", special: "", caution: "不可深刺,防伤肺脏", mnemonic: "俞府止咳平喘", mnemonicExplanation: "俞府善治咳喘胸痛", level: "二类", sortOrder: 113 },
  { id: "a_quze", name: "曲泽", pinyin: "quze", code: "PC3", meridian: "手厥阴心包经", location: "肘前区,肘横纹上,肱二头肌腱尺侧缘凹陷中", indications: "心痛,心悸,胃痛,呕吐,热病,肘臂挛痛", method: "直刺0.8-1寸;或点刺出血", special: "合穴", caution: "", mnemonic: "曲泽清心止呕", mnemonicExplanation: "曲泽为心包经合穴,善清心火止呕", level: "二类", sortOrder: 114 },
  { id: "a_laogong", name: "劳宫", pinyin: "laogong", code: "PC8", meridian: "手厥阴心包经", location: "掌区,横平第3掌指关节近端,第2、3掌骨之间偏于第3掌骨", indications: "心痛,心烦,癫狂痫,口疮口臭,鹅掌风", method: "直刺0.3-0.5寸", special: "荥穴", caution: "", mnemonic: "劳宫清心开窍", mnemonicExplanation: "劳宫为心包经荥穴,善清心火,治口疮", level: "二类", sortOrder: 115 },
  { id: "a_zhongchong", name: "中冲", pinyin: "zhongchong", code: "PC9", meridian: "手厥阴心包经", location: "中指末端,指甲根角侧上方0.1寸", indications: "昏迷,中暑,心痛,舌强肿痛,小儿惊风", method: "浅刺0.1寸;或点刺出血", special: "井穴", caution: "", mnemonic: "中冲急救开窍", mnemonicExplanation: "中冲为急救要穴,点刺出血醒神开窍", level: "二类", sortOrder: 116 },
  { id: "a_ximen", name: "郄门", pinyin: "ximen", code: "PC4", meridian: "手厥阴心包经", location: "前臂前区,腕掌侧远端横纹上5寸,掌长肌腱与桡侧腕屈肌腱之间", indications: "心痛,心悸,胸痛,咳血,呕血,疔疮", method: "直刺0.5-1寸", special: "郄穴", caution: "", mnemonic: "郄门急痛止血", mnemonicExplanation: "郄门为心包经郄穴,善治心胸急痛与血证", level: "二类", sortOrder: 117 },
  { id: "a_guanchong", name: "关冲", pinyin: "guanchong", code: "TE1", meridian: "手少阳三焦经", location: "无名指末节尺侧,指甲根角侧上方0.1寸", indications: "头痛,目赤,耳聋,咽喉肿痛,热病,昏厥", method: "浅刺0.1寸;或点刺出血", special: "井穴", caution: "", mnemonic: "关冲清热开窍", mnemonicExplanation: "关冲为三焦经井穴,点刺出血清热开窍", level: "二类", sortOrder: 118 },
  { id: "a_yangchi", name: "阳池", pinyin: "yangchi", code: "TE4", meridian: "手少阳三焦经", location: "腕后区,腕背侧远端横纹上,指伸肌腱的尺侧缘凹陷中", indications: "耳聋,口干,咽喉肿痛,腕痛,消渴", method: "直刺0.3-0.5寸", special: "原穴", caution: "", mnemonic: "阳池通络利腕", mnemonicExplanation: "阳池为三焦经原穴,善治腕痛消渴", level: "二类", sortOrder: 119 },
  { id: "a_zhigou", name: "支沟", pinyin: "zhigou", code: "TE6", meridian: "手少阳三焦经", location: "前臂后区,腕背侧远端横纹上3寸,尺骨与桡骨间隙中点", indications: "便秘,胁肋痛,耳鸣耳聋,暴喑,热病", method: "直刺0.5-1寸", special: "经穴", caution: "", mnemonic: "支沟通便要穴", mnemonicExplanation: "支沟为治便秘要穴,兼理胁痛", level: "二类", sortOrder: 120 },
  { id: "a_yifeng", name: "翳风", pinyin: "yifeng", code: "TE17", meridian: "手少阳三焦经", location: "颈部,耳垂后方,乳突下端前方凹陷中", indications: "耳鸣耳聋,口眼歪斜,牙关紧闭,颊肿,瘰疬", method: "直刺0.5-1寸", special: "", caution: "", mnemonic: "翳风聪耳通络", mnemonicExplanation: "翳风善治耳病与面瘫,为治耳鸣要穴", level: "二类", sortOrder: 121 },
  { id: "a_tianjing", name: "天井", pinyin: "tianjing", code: "TE10", meridian: "手少阳三焦经", location: "肘后区,肘尖直上1寸凹陷中", indications: "偏头痛,耳聋,瘰疬,肘臂痛,癫痫", method: "直刺0.5-1寸", special: "合穴", caution: "", mnemonic: "天井散结通络", mnemonicExplanation: "天井为三焦经合穴,善治瘰疬与肘臂痛", level: "二类", sortOrder: 122 },
  { id: "a_sizhukong", name: "丝竹空", pinyin: "sizhukong", code: "TE23", meridian: "手少阳三焦经", location: "面部,眉梢凹陷处", indications: "头痛,目赤肿痛,眼睑瞤动,齿痛,癫痫", method: "平刺0.3-0.5寸", special: "", caution: "禁灸", mnemonic: "丝竹空清头目", mnemonicExplanation: "丝竹空善治头目疾患,平刺不宜灸", level: "二类", sortOrder: 123 },
  { id: "a_tinghui", name: "听会", pinyin: "tinghui", code: "GB2", meridian: "足少阳胆经", location: "面部,耳屏间切迹与下颌骨髁突之间的凹陷中", indications: "耳鸣,耳聋,聤耳,齿痛,口眼歪斜", method: "张口,直刺0.5-0.8寸", special: "", caution: "", mnemonic: "听会聪耳要穴", mnemonicExplanation: "听会为治耳病要穴,善聪耳", level: "二类", sortOrder: 124 },
  { id: "a_tongziliao", name: "瞳子髎", pinyin: "tongziliao", code: "GB1", meridian: "足少阳胆经", location: "面部,目外眦外侧0.5寸凹陷中", indications: "目赤肿痛,目翳,头痛,口眼歪斜", method: "平刺0.3-0.5寸", special: "", caution: "", mnemonic: "瞳子髎明目", mnemonicExplanation: "瞳子髎善治目疾与面瘫", level: "二类", sortOrder: 125 },
  { id: "a_shuaigu", name: "率谷", pinyin: "shuaigu", code: "GB8", meridian: "足少阳胆经", location: "头部,耳尖直上入发际1.5寸", indications: "偏头痛,眩晕,小儿急慢惊风", method: "平刺0.5-0.8寸", special: "", caution: "", mnemonic: "率谷止偏头痛", mnemonicExplanation: "率谷善治偏头痛,为少阳头痛要穴", level: "二类", sortOrder: 126 },
  { id: "a_yangbai", name: "阳白", pinyin: "yangbai", code: "GB14", meridian: "足少阳胆经", location: "头部,眉上1寸,瞳孔直上", indications: "头痛,目眩,目痛,视物模糊,眼睑瞤动", method: "平刺0.3-0.5寸", special: "", caution: "", mnemonic: "阳白清头明目", mnemonicExplanation: "阳白善治前额头痛与目疾", level: "二类", sortOrder: 127 },
  { id: "a_toulinqi", name: "头临泣", pinyin: "toulinqi", code: "GB15", meridian: "足少阳胆经", location: "头部,前发际上0.5寸,瞳孔直上", indications: "头痛,目眩,目赤肿痛,流泪,鼻塞,癫痫", method: "平刺0.5-0.8寸", special: "", caution: "", mnemonic: "临泣清头明目", mnemonicExplanation: "头临泣善治头目诸疾", level: "二类", sortOrder: 128 },
  { id: "a_fengshi", name: "风市", pinyin: "fengshi", code: "GB31", meridian: "足少阳胆经", location: "大腿外侧,腘横纹上7寸,直立垂手时中指尖处", indications: "下肢痿痹,麻木,半身不遂,遍身瘙痒", method: "直刺1-2寸", special: "", caution: "", mnemonic: "风市祛风通络", mnemonicExplanation: "风市善治下肢痿痹,兼祛风止痒", level: "二类", sortOrder: 129 },
  { id: "a_guangming", name: "光明", pinyin: "guangming", code: "GB37", meridian: "足少阳胆经", location: "小腿外侧,外踝尖上5寸,腓骨前缘", indications: "目痛,夜盲,近视,乳胀痛,下肢痿痹", method: "直刺0.5-0.8寸", special: "络穴", caution: "", mnemonic: "光明明目要穴", mnemonicExplanation: "光明为胆经络穴,善明目,为治眼病要穴", level: "二类", sortOrder: 130 },
  { id: "a_muchuang", name: "目窗", pinyin: "muchuang", code: "GB16", meridian: "足少阳胆经", location: "头部,前发际上1.5寸,瞳孔直上", indications: "头痛,目赤肿痛,青盲,鼻塞,癫痫", method: "平刺0.5-0.8寸", special: "", caution: "", mnemonic: "目窗明目开窍", mnemonicExplanation: "目窗善治目疾与头痛", level: "二类", sortOrder: 131 },
  { id: "a_qiuxu", name: "丘墟", pinyin: "qiuxu", code: "GB40", meridian: "足少阳胆经", location: "踝区,外踝的前下方,趾长伸肌腱的外侧凹陷中", indications: "胸胁痛,颈项痛,踝关节痛,目赤肿痛,疟疾", method: "直刺0.5-0.8寸", special: "原穴", caution: "", mnemonic: "丘墟疏肝通络", mnemonicExplanation: "丘墟为胆经原穴,善治胁痛踝痛", level: "二类", sortOrder: 132 },
  { id: "a_zuqiaoyin", name: "足窍阴", pinyin: "zuqiaoyin", code: "GB44", meridian: "足少阳胆经", location: "足第4趾末节外侧,趾甲根角侧后方0.1寸", indications: "头痛,目赤肿痛,耳聋,咽喉肿痛,失眠,胁痛", method: "浅刺0.1寸;或点刺出血", special: "井穴", caution: "", mnemonic: "窍阴清热开窍", mnemonicExplanation: "足窍阴为胆经井穴,善清肝胆热", level: "二类", sortOrder: 133 },
  { id: "a_dadun", name: "大敦", pinyin: "dadun", code: "LR1", meridian: "足厥阴肝经", location: "足大趾末节外侧,趾甲根角侧后方0.1寸", indications: "疝气,遗尿,癃闭,月经不调,崩漏,癫痫", method: "浅刺0.1寸;或点刺出血", special: "井穴", caution: "", mnemonic: "大敦疏肝治疝", mnemonicExplanation: "大敦为肝经井穴,善治疝气与崩漏", level: "二类", sortOrder: 134 },
  { id: "a_xingjian", name: "行间", pinyin: "xingjian", code: "LR2", meridian: "足厥阴肝经", location: "足背,第1、2趾间,趾蹼缘后方赤白肉际处", indications: "头痛,目赤肿痛,胁痛,月经不调,痛经,癫痫", method: "直刺0.5-0.8寸", special: "荥穴", caution: "", mnemonic: "行间清肝泻火", mnemonicExplanation: "行间为肝经荥穴,善清肝泻火", level: "二类", sortOrder: 135 },
  { id: "a_ligou", name: "蠡沟", pinyin: "ligou", code: "LR5", meridian: "足厥阴肝经", location: "小腿内侧,内踝尖上5寸,胫骨内侧面的中央", indications: "阴痒,带下,月经不调,小便不利,疝气,足胫痛", method: "平刺0.5-0.8寸", special: "络穴", caution: "", mnemonic: "蠡沟调经止痒", mnemonicExplanation: "蠡沟为肝经络穴,善治阴痒带下", level: "二类", sortOrder: 136 },
  { id: "a_zhongdu", name: "中都", pinyin: "zhongdu", code: "LR6", meridian: "足厥阴肝经", location: "小腿内侧,内踝尖上7寸,胫骨内侧面的中央", indications: "疝气,崩漏,小腹痛,胁痛,下肢痿痹", method: "平刺0.5-0.8寸", special: "郄穴", caution: "", mnemonic: "中都郄穴止痛", mnemonicExplanation: "中都为肝经郄穴,善治崩漏急痛", level: "二类", sortOrder: 137 },
  { id: "a_ququan", name: "曲泉", pinyin: "ququan", code: "LR8", meridian: "足厥阴肝经", location: "膝部,腘横纹内侧端,半腱肌肌腱内缘凹陷中", indications: "月经不调,痛经,遗精,阳痿,膝股内侧痛", method: "直刺1-1.5寸", special: "合穴", caution: "", mnemonic: "曲泉补肝调经", mnemonicExplanation: "曲泉为肝经合穴,善治妇科与膝痛", level: "二类", sortOrder: 138 },
  { id: "a_shenting", name: "神庭", pinyin: "shenting", code: "GV24", meridian: "督脉", location: "头部,前发际正中直上0.5寸", indications: "头痛,眩晕,失眠,鼻渊,癫痫", method: "平刺0.3-0.5寸", special: "", caution: "", mnemonic: "神庭安神定志", mnemonicExplanation: "神庭善治头痛失眠与癫痫", level: "二类", sortOrder: 139 },
  { id: "a_shenzhu", name: "身柱", pinyin: "shenzhu", code: "GV12", meridian: "督脉", location: "背部,第3胸椎棘突下凹陷中", indications: "咳嗽,气喘,癫痫,脊背强痛,小儿惊风", method: "向上斜刺0.5-1寸", special: "", caution: "", mnemonic: "身柱止咳定惊", mnemonicExplanation: "身柱善治咳喘与小儿惊风", level: "二类", sortOrder: 140 },
  { id: "a_zhiyang", name: "至阳", pinyin: "zhiyang", code: "GV9", meridian: "督脉", location: "背部,第7胸椎棘突下凹陷中", indications: "胸胁胀痛,黄疸,咳嗽气喘,脊背强痛", method: "向上斜刺0.5-1寸", special: "", caution: "", mnemonic: "至阳退黄止痛", mnemonicExplanation: "至阳善治胸胁痛与黄疸", level: "二类", sortOrder: 141 },
  { id: "a_yaoyangguan", name: "腰阳关", pinyin: "yaoyangguan", code: "GV3", meridian: "督脉", location: "腰部,第4腰椎棘突下凹陷中", indications: "腰骶疼痛,下肢痿痹,月经不调,遗精阳痿", method: "直刺0.5-1寸", special: "", caution: "", mnemonic: "腰阳关壮腰", mnemonicExplanation: "腰阳关善治腰骶痛与下肢痿痹", level: "二类", sortOrder: 142 },
  { id: "a_fengfu", name: "风府", pinyin: "fengfu", code: "GV16", meridian: "督脉", location: "颈后区,枕外隆凸直下,两侧斜方肌之间凹陷中", indications: "头痛,项强,眩晕,咽喉肿痛,中风不语,癫狂", method: "正坐位,头微前倾,向下颌方向缓慢刺入0.5-1寸", special: "", caution: "不可向上深刺,防伤延髓", mnemonic: "风府祛风开窍", mnemonicExplanation: "风府善祛风邪,治头项强痛", level: "二类", sortOrder: 143 },
  { id: "a_yanmen", name: "哑门", pinyin: "yanmen", code: "GV15", meridian: "督脉", location: "颈后区,第2颈椎棘突上际凹陷中", indications: "暴喑,舌强不语,头痛项强,癫痫", method: "正坐位,头微前倾,向下颌方向缓慢刺入0.5-1寸", special: "", caution: "不可向上深刺,防伤延髓", mnemonic: "哑门开音要穴", mnemonicExplanation: "哑门善治暴喑失语,为开音要穴", level: "二类", sortOrder: 144 },
  { id: "a_shendao", name: "神道", pinyin: "shendao", code: "GV11", meridian: "督脉", location: "背部,第5胸椎棘突下凹陷中", indications: "心痛,心悸,失眠,健忘,咳嗽,脊背强痛", method: "向上斜刺0.5-1寸", special: "", caution: "", mnemonic: "神道宁心安神", mnemonicExplanation: "神道善治心悸失眠", level: "二类", sortOrder: 145 },
  { id: "a_qugu", name: "曲骨", pinyin: "qugu", code: "CV2", meridian: "任脉", location: "下腹部,前正中线上,耻骨联合上缘的中点处", indications: "小便不利,遗尿,遗精阳痿,月经不调,带下", method: "直刺0.5-1寸", special: "任脉与足厥阴经交会穴", caution: "排尿后进行针刺", mnemonic: "曲骨利水调经", mnemonicExplanation: "曲骨善治泌尿生殖系疾患", level: "二类", sortOrder: 146 },
  { id: "a_shenque", name: "神阙", pinyin: "shenque", code: "CV8", meridian: "任脉", location: "腹部,脐中央", indications: "腹痛,泄泻,脱肛,水肿,虚脱,中风脱证", method: "一般不针,多用艾炷隔盐灸", special: "", caution: "禁针,多用灸法", mnemonic: "神阙回阳救逆", mnemonicExplanation: "神阙多用隔盐灸,善回阳固脱", level: "二类", sortOrder: 147 },
  { id: "a_yinjiao", name: "阴交", pinyin: "yinjiao", code: "CV7", meridian: "任脉", location: "下腹部,前正中线上,脐中下1寸", indications: "腹痛,水肿,月经不调,带下,疝气,脐周痛", method: "直刺1-1.5寸", special: "任脉与冲脉交会穴", caution: "孕妇慎用", mnemonic: "阴交调经利水", mnemonicExplanation: "阴交善治妇科与水肿诸证", level: "二类", sortOrder: 148 },
  { id: "a_shimen", name: "石门", pinyin: "shimen", code: "CV5", meridian: "任脉", location: "下腹部,前正中线上,脐中下2寸", indications: "腹痛,水肿,小便不利,泄泻,经闭,带下", method: "直刺1-1.5寸", special: "三焦募穴", caution: "孕妇禁针", mnemonic: "石门利水通经", mnemonicExplanation: "石门为三焦募穴,善治水肿与经闭", level: "二类", sortOrder: 149 },
  { id: "a_zhongji", name: "中极", pinyin: "zhongji", code: "CV3", meridian: "任脉", location: "下腹部,前正中线上,脐中下4寸", indications: "癃闭,遗尿,尿频,月经不调,痛经,带下,遗精", method: "直刺1-1.5寸;排尿后针刺", special: "膀胱募穴;任脉与足三阴经交会穴", caution: "排尿后进行针刺", mnemonic: "中极通利膀胱", mnemonicExplanation: "中极为膀胱募穴,善治小便不利与妇科病", level: "一类", sortOrder: 150 },
  { id: "a_shangwan", name: "上脘", pinyin: "shangwan", code: "CV13", meridian: "任脉", location: "上腹部,前正中线上,脐中上5寸", indications: "胃痛,呕吐,呃逆,腹胀,癫痫", method: "直刺1-1.5寸", special: "任脉与足阳明经交会穴", caution: "", mnemonic: "上脘和胃降逆", mnemonicExplanation: "上脘善治胃痛呕吐与癫痫", level: "二类", sortOrder: 151 },
  // ===== 腧穴扩充(2026-08,补齐常用经穴至 260+) =====
  { id: "a_yunmen", name: "云门", pinyin: "yunmen", code: "LU2", meridian: "手太阴肺经", location: "胸前壁外上方,锁骨下窝凹陷处,前正中线旁开6寸", indications: "咳嗽,气喘,胸痛,肩背痛", method: "向外斜刺0.5-0.8寸", special: "", caution: "不可深刺,防伤肺脏", mnemonic: "云门宣肺止咳", mnemonicExplanation: "云门善宣肺气,治咳喘胸痛", level: "二类", sortOrder: 152 },
  { id: "a_xiabai", name: "侠白", pinyin: "xiabai", code: "LU4", meridian: "手太阴肺经", location: "前臂前区,腋前纹头下4寸,肱二头肌桡侧缘处", indications: "咳嗽,气喘,干呕,烦满,上臂内侧痛", method: "直刺0.5-0.8寸", special: "", caution: "", mnemonic: "侠白理肺宽胸", mnemonicExplanation: "侠白善理肺气治咳喘", level: "二类", sortOrder: 153 },
  { id: "a_jingqu", name: "经渠", pinyin: "jingqu", code: "LU8", meridian: "手太阴肺经", location: "前臂前区,腕掌侧远端横纹上1寸,桡骨茎突与桡动脉之间", indications: "咳嗽,气喘,胸痛,咽喉肿痛,手腕痛", method: "避开桡动脉,直刺0.3-0.5寸", special: "经穴", caution: "避开桡动脉", mnemonic: "经渠宣肺利咽", mnemonicExplanation: "经渠为肺经经穴,治咳喘咽痛", level: "二类", sortOrder: 154 },
  { id: "a_erjian", name: "二间", pinyin: "erjian", code: "LI2", meridian: "手阳明大肠经", location: "手背,第2掌指关节桡侧远端赤白肉际处", indications: "齿痛,鼻衄,咽喉肿痛,目痛,热病", method: "直刺0.2-0.3寸", special: "荥穴", caution: "", mnemonic: "二间清胃止痛", mnemonicExplanation: "二间为大肠经荥穴,善清阳明热", level: "二类", sortOrder: 155 },
  { id: "a_wenliu", name: "温溜", pinyin: "wenliu", code: "LI7", meridian: "手阳明大肠经", location: "前臂,腕背侧远端横纹上5寸,阳溪与曲池连线上", indications: "头痛,面肿,咽喉肿痛,肠鸣腹痛,疔疮", method: "直刺0.5-1寸", special: "郄穴", caution: "", mnemonic: "温溜清泻阳明", mnemonicExplanation: "温溜为大肠经郄穴,治头面热病", level: "二类", sortOrder: 156 },
  { id: "a_shanglian", name: "上廉", pinyin: "shanglian", code: "LI9", meridian: "手阳明大肠经", location: "前臂,肘横纹下3寸,阳溪与曲池连线上", indications: "肘臂酸痛,上肢麻木,肠鸣腹痛,头痛", method: "直刺0.5-1寸", special: "", caution: "", mnemonic: "上廉通络止痛", mnemonicExplanation: "上廉善治上肢痹痛", level: "二类", sortOrder: 157 },
  { id: "a_shouwuli", name: "手五里", pinyin: "shouwuli", code: "LI13", meridian: "手阳明大肠经", location: "臂部,肘横纹上3寸,曲池与肩髃连线上", indications: "肘臂挛痛,瘰疬,咳嗽,心下胀满", method: "直刺0.5-0.8寸", special: "", caution: "", mnemonic: "五里散结通络", mnemonicExplanation: "手五里善治瘰疬与肘臂痛", level: "二类", sortOrder: 158 },
  { id: "a_jugu", name: "巨骨", pinyin: "jugu", code: "LI16", meridian: "手阳明大肠经", location: "肩胛区,锁骨肩峰端与肩胛冈之间凹陷处", indications: "肩臂挛痛,活动不利,瘰疬,瘿气", method: "直刺0.4-0.6寸", special: "", caution: "不可深刺,防伤肺尖", mnemonic: "巨骨通肩止痛", mnemonicExplanation: "巨骨善治肩臂疼痛", level: "二类", sortOrder: 159 },
  { id: "a_futu", name: "扶突", pinyin: "futu", code: "LI18", meridian: "手阳明大肠经", location: "颈外侧,喉结旁开3寸,胸锁乳突肌的胸骨头与锁骨头之间", indications: "咳嗽,气喘,咽喉肿痛,暴喑,瘿气,瘰疬", method: "直刺0.5-0.8寸", special: "", caution: "不宜深刺", mnemonic: "扶突利咽消瘿", mnemonicExplanation: "扶突善治咽喉病与瘿瘤", level: "二类", sortOrder: 160 },
  { id: "a_sibai", name: "四白", pinyin: "sibai", code: "ST2", meridian: "足阳明胃经", location: "面部,瞳孔直下,眶下孔凹陷处", indications: "目赤痛痒,目翳,眼睑瞤动,口眼歪斜,面痛", method: "直刺0.2-0.3寸", special: "", caution: "", mnemonic: "四白明目要穴", mnemonicExplanation: "四白善治目疾与面瘫", level: "二类", sortOrder: 161 },
  { id: "a_juliao", name: "巨髎", pinyin: "juliao", code: "ST3", meridian: "足阳明胃经", location: "面部,瞳孔直下,平鼻翼下缘处,鼻唇沟外侧", indications: "口眼歪斜,眼睑瞤动,鼻衄,齿痛,面痛", method: "斜刺或平刺0.3-0.5寸", special: "", caution: "", mnemonic: "巨髎治面瘫", mnemonicExplanation: "巨髎善治面瘫面痛", level: "二类", sortOrder: 162 },
  { id: "a_daying", name: "大迎", pinyin: "daying", code: "ST5", meridian: "足阳明胃经", location: "面部,下颌角前方,咬肌附着部的前缘凹陷中", indications: "口歪,齿痛,颊肿,牙关紧闭,瘰疬", method: "避开动脉,斜刺或平刺0.3-0.5寸", special: "", caution: "避开动脉", mnemonic: "大迎开噤止痛", mnemonicExplanation: "大迎善治牙关紧闭与面痛", level: "二类", sortOrder: 163 },
  { id: "a_renying", name: "人迎", pinyin: "renying", code: "ST9", meridian: "足阳明胃经", location: "颈部,喉结旁开1.5寸,胸锁乳突肌前缘,颈总动脉搏动处", indications: "瘿气,瘰疬,咽喉肿痛,高血压,气喘", method: "避开颈总动脉,直刺0.2-0.4寸", special: "", caution: "避开动脉,不可深刺", mnemonic: "人迎平喘消瘿", mnemonicExplanation: "人迎善治瘿瘤与咽喉病", level: "二类", sortOrder: 164 },
  { id: "a_rugen", name: "乳根", pinyin: "rugen", code: "ST18", meridian: "足阳明胃经", location: "胸部,第5肋间隙,前正中线旁开4寸", indications: "乳痈,乳汁不足,胸痛,咳喘,呃逆", method: "斜刺或平刺0.5-0.8寸", special: "", caution: "不可深刺,防伤肺脏", mnemonic: "乳根通乳消痈", mnemonicExplanation: "乳根善治乳痈与乳汁不通", level: "二类", sortOrder: 165 },
  { id: "a_burong", name: "不容", pinyin: "burong", code: "ST19", meridian: "足阳明胃经", location: "上腹部,脐中上6寸,前正中线旁开2寸", indications: "胃痛,呕吐,食欲不振,腹胀,胸胁痛", method: "直刺0.5-0.8寸", special: "", caution: "", mnemonic: "不容和胃止呕", mnemonicExplanation: "不容善治胃痛呕吐", level: "二类", sortOrder: 166 },
  { id: "a_huaroumen", name: "滑肉门", pinyin: "huaroumen", code: "ST24", meridian: "足阳明胃经", location: "上腹部,脐中上1寸,前正中线旁开2寸", indications: "胃痛,呕吐,腹胀,癫狂,吐舌", method: "直刺0.8-1.2寸", special: "", caution: "", mnemonic: "滑肉门调胃肠", mnemonicExplanation: "滑肉门善治胃肠病与癫狂", level: "二类", sortOrder: 167 },
  { id: "a_wailing", name: "外陵", pinyin: "wailing", code: "ST26", meridian: "足阳明胃经", location: "下腹部,脐中下1寸,前正中线旁开2寸", indications: "腹痛,疝气,痛经,月经不调", method: "直刺1-1.5寸", special: "", caution: "", mnemonic: "外陵理气止痛", mnemonicExplanation: "外陵善治腹痛疝气", level: "二类", sortOrder: 168 },
  { id: "a_shuidao", name: "水道", pinyin: "shuidao", code: "ST28", meridian: "足阳明胃经", location: "下腹部,脐中下3寸,前正中线旁开2寸", indications: "小腹胀满,小便不利,痛经,疝气,水肿", method: "直刺1-1.5寸", special: "", caution: "", mnemonic: "水道利水通淋", mnemonicExplanation: "水道善利水消肿通淋", level: "二类", sortOrder: 169 },
  { id: "a_guilai", name: "归来", pinyin: "guilai", code: "ST29", meridian: "足阳明胃经", location: "下腹部,脐中下4寸,前正中线旁开2寸", indications: "腹痛,疝气,月经不调,闭经,带下,阴挺", method: "直刺1-1.5寸", special: "", caution: "", mnemonic: "归来调经缩阴", mnemonicExplanation: "归来善治妇科诸疾与疝气", level: "二类", sortOrder: 170 },
  { id: "a_futu2", name: "伏兔", pinyin: "futu2", code: "ST32", meridian: "足阳明胃经", location: "股前区,髌底上6寸,髂前上棘与髌底外侧端的连线上", indications: "腰膝冷痛,下肢痿痹,疝气,脚气", method: "直刺1-1.5寸", special: "", caution: "", mnemonic: "伏兔通络治痿", mnemonicExplanation: "伏兔善治下肢痿痹与腰膝冷痛", level: "二类", sortOrder: 171 },
  { id: "a_yinshi", name: "阴市", pinyin: "yinshi", code: "ST33", meridian: "足阳明胃经", location: "股前区,髌底上3寸,股直肌肌腱外侧缘", indications: "膝冷,腹胀,疝气,下肢痿痹", method: "直刺1-1.5寸", special: "", caution: "", mnemonic: "阴市散寒止痛", mnemonicExplanation: "阴市善治膝冷与下肢痿痹", level: "二类", sortOrder: 172 },
  { id: "a_xiajuxu", name: "下巨虚", pinyin: "xiajuxu", code: "ST39", meridian: "足阳明胃经", location: "小腿前外侧,犊鼻下9寸,胫骨前嵴外一横指", indications: "小腹痛,泄泻,痢疾,乳痈,下肢痿痹", method: "直刺1-1.5寸", special: "小肠下合穴", caution: "", mnemonic: "下巨调肠通络", mnemonicExplanation: "下巨虚为小肠下合穴,善调肠腑", level: "二类", sortOrder: 173 },
  { id: "a_chongyang", name: "冲阳", pinyin: "chongyang", code: "ST42", meridian: "足阳明胃经", location: "足背,第2跖骨基底部与中间楔状骨关节处,足背动脉搏动处", indications: "胃痛,腹胀,口眼歪斜,面肿,足背肿痛", method: "避开动脉,直刺0.3-0.5寸", special: "原穴", caution: "避开足背动脉", mnemonic: "冲阳和胃通络", mnemonicExplanation: "冲阳为胃经原穴,善治胃痛", level: "二类", sortOrder: 174 },
  { id: "a_xiangu", name: "陷谷", pinyin: "xiangu", code: "ST43", meridian: "足阳明胃经", location: "足背,第2、3跖骨间,第2跖趾关节近端凹陷处", indications: "面目浮肿,肠鸣腹痛,足背肿痛,热病", method: "直刺0.3-0.5寸", special: "输穴", caution: "", mnemonic: "陷谷利水消肿", mnemonicExplanation: "陷谷善治面目浮肿", level: "二类", sortOrder: 175 },
  { id: "a_lougu", name: "漏谷", pinyin: "lougu", code: "SP7", meridian: "足太阴脾经", location: "小腿内侧,内踝尖上6寸,胫骨内侧缘后际", indications: "腹胀,肠鸣,遗精,小便不利,下肢痿痹", method: "直刺1-1.5寸", special: "", caution: "", mnemonic: "漏谷健脾利水", mnemonicExplanation: "漏谷善治腹胀与小便不利", level: "二类", sortOrder: 176 },
  { id: "a_diji", name: "地机", pinyin: "diji", code: "SP8", meridian: "足太阴脾经", location: "小腿内侧,阴陵泉下3寸,胫骨内侧缘后际", indications: "痛经,崩漏,月经不调,腹痛泄泻,水肿", method: "直刺1-1.5寸", special: "郄穴", caution: "", mnemonic: "地机调经止血", mnemonicExplanation: "地机为脾经郄穴,善治妇科血证", level: "二类", sortOrder: 177 },
  { id: "a_jimen", name: "箕门", pinyin: "jimen", code: "SP11", meridian: "足太阴脾经", location: "股前区,髌底内侧端与冲门的连线上1/3与下2/3交点", indications: "小便不利,遗尿,腹股沟肿痛,下肢痿痹", method: "直刺0.5-0.8寸", special: "", caution: "", mnemonic: "箕门利水通淋", mnemonicExplanation: "箕门善治小便不利", level: "二类", sortOrder: 178 },
  { id: "a_daheng", name: "大横", pinyin: "daheng", code: "SP15", meridian: "足太阴脾经", location: "腹部,脐中旁开4寸", indications: "腹胀,腹痛,泄泻,便秘,痢疾", method: "直刺1-1.5寸", special: "", caution: "", mnemonic: "大横调肠止泻", mnemonicExplanation: "大横善治胃肠诸疾", level: "二类", sortOrder: 179 },
  { id: "a_zhourong", name: "周荣", pinyin: "zhourong", code: "SP20", meridian: "足太阴脾经", location: "胸部,第2肋间隙,前正中线旁开6寸", indications: "胸胁胀满,咳嗽,气喘,食欲不振", method: "斜刺或平刺0.5-0.8寸", special: "", caution: "不可深刺", mnemonic: "周荣宽胸理气", mnemonicExplanation: "周荣善治胸胁胀满与咳喘", level: "二类", sortOrder: 180 },
  { id: "a_lingdao", name: "灵道", pinyin: "lingdao", code: "HT4", meridian: "手少阴心经", location: "前臂前区,腕掌侧远端横纹上1.5寸,尺侧腕屈肌腱桡侧缘", indications: "心痛,心悸,暴喑,肘臂挛痛", method: "直刺0.3-0.5寸", special: "经穴", caution: "", mnemonic: "灵道宁心开音", mnemonicExplanation: "灵道善治心痛与暴喑", level: "二类", sortOrder: 181 },
  { id: "a_shaofu", name: "少府", pinyin: "shaofu", code: "HT8", meridian: "手少阴心经", location: "手掌,横平第5掌指关节近端,第4、5掌骨之间", indications: "心悸,心痛,小便不利,阴痒,掌中热,小指挛痛", method: "直刺0.3-0.5寸", special: "荥穴", caution: "", mnemonic: "少府清心利尿", mnemonicExplanation: "少府为心经荥穴,善清心火", level: "二类", sortOrder: 182 },
  { id: "a_qiangu", name: "前谷", pinyin: "qiangu", code: "SI2", meridian: "手太阳小肠经", location: "手指,第5掌指关节尺侧远端赤白肉际凹陷处", indications: "头痛,目痛,耳鸣,咽喉肿痛,热病,乳汁不足", method: "直刺0.2-0.3寸", special: "荥穴", caution: "", mnemonic: "前谷清热通乳", mnemonicExplanation: "前谷为小肠经荥穴,清热通乳", level: "二类", sortOrder: 183 },
  { id: "a_wangu", name: "腕骨", pinyin: "wangu", code: "SI4", meridian: "手太阳小肠经", location: "腕区,第5掌骨底与三角骨之间的赤白肉际凹陷处", indications: "头项强痛,耳鸣,目翳,黄疸,热病,腕痛", method: "直刺0.3-0.5寸", special: "原穴", caution: "", mnemonic: "腕骨通络退黄", mnemonicExplanation: "腕骨为小肠经原穴,善治项强黄疸", level: "二类", sortOrder: 184 },
  { id: "a_zhizheng", name: "支正", pinyin: "zhizheng", code: "SI7", meridian: "手太阳小肠经", location: "前臂后区,腕背侧远端横纹上5寸,尺骨尺侧与尺侧腕屈肌之间", indications: "头痛,项强,肘臂酸痛,热病,癫狂,疣症", method: "直刺0.5-0.8寸", special: "络穴", caution: "", mnemonic: "支正通络散结", mnemonicExplanation: "支正为小肠经络穴,善治项强疣赘", level: "二类", sortOrder: 185 },
  { id: "a_jianzhen", name: "肩贞", pinyin: "jianzhen", code: "SI9", meridian: "手太阳小肠经", location: "肩后区,腋后纹头直上1寸", indications: "肩臂疼痛,上肢不遂,瘰疬,耳鸣", method: "直刺1-1.5寸", special: "", caution: "", mnemonic: "肩贞通肩止痛", mnemonicExplanation: "肩贞善治肩臂痛与瘰疬", level: "二类", sortOrder: 186 },
  { id: "a_naoshu", name: "臑俞", pinyin: "naoshu", code: "SI10", meridian: "手太阳小肠经", location: "肩胛区,腋后纹头直上,肩胛冈下缘凹陷处", indications: "肩臂酸痛,上肢不遂,瘰疬", method: "直刺0.8-1.2寸", special: "", caution: "", mnemonic: "臑俞通肩通络", mnemonicExplanation: "臑俞善治肩臂疼痛", level: "二类", sortOrder: 187 },
  { id: "a_bingfeng", name: "秉风", pinyin: "bingfeng", code: "SI12", meridian: "手太阳小肠经", location: "肩胛区,肩胛冈中点上方冈上窝中", indications: "肩胛疼痛,上肢酸麻,颈项强直", method: "直刺0.5-0.8寸", special: "", caution: "", mnemonic: "秉风祛风通络", mnemonicExplanation: "秉风善治肩胛疼痛", level: "二类", sortOrder: 188 },
  { id: "a_tianchuang", name: "天窗", pinyin: "tianchuang", code: "SI16", meridian: "手太阳小肠经", location: "颈部,横平喉结,胸锁乳突肌的后缘", indications: "耳鸣,耳聋,咽喉肿痛,颈项强痛,暴喑", method: "直刺0.5-1寸", special: "", caution: "", mnemonic: "天窗聪耳开音", mnemonicExplanation: "天窗善治耳病与暴喑", level: "二类", sortOrder: 189 },
  { id: "a_meichong", name: "眉冲", pinyin: "meichong", code: "BL3", meridian: "足太阳膀胱经", location: "头部,额切际直上入发际0.5寸,神庭与曲差连线之间", indications: "头痛,眩晕,鼻塞,癫痫", method: "平刺0.3-0.5寸", special: "", caution: "", mnemonic: "眉冲清头通窍", mnemonicExplanation: "眉冲善治头痛鼻塞", level: "二类", sortOrder: 190 },
  { id: "a_qucha", name: "曲差", pinyin: "qucha", code: "BL4", meridian: "足太阳膀胱经", location: "头部,前发际正中直上0.5寸,旁开1.5寸", indications: "头痛,鼻塞,鼻衄,目视不明", method: "平刺0.3-0.5寸", special: "", caution: "", mnemonic: "曲差通窍明目", mnemonicExplanation: "曲差善治头痛鼻塞目疾", level: "二类", sortOrder: 191 },
  { id: "a_jueyinshu", name: "厥阴俞", pinyin: "jueyinshu", code: "BL14", meridian: "足太阳膀胱经", location: "背部,第4胸椎棘突下,旁开1.5寸", indications: "心痛,心悸,胸闷,咳嗽,呕吐", method: "斜刺0.5-0.8寸", special: "心包背俞穴", caution: "不宜深刺", mnemonic: "厥阴俞宁心", mnemonicExplanation: "厥阴俞为心包背俞穴,善宁心", level: "二类", sortOrder: 192 },
  { id: "a_dushu", name: "督俞", pinyin: "dushu", code: "BL16", meridian: "足太阳膀胱经", location: "背部,第6胸椎棘突下,旁开1.5寸", indications: "心痛,胸闷,腹痛,寒热,气喘", method: "斜刺0.5-0.8寸", special: "", caution: "不宜深刺", mnemonic: "督俞宽胸理气", mnemonicExplanation: "督俞善治心痛胸闷", level: "二类", sortOrder: 193 },
  { id: "a_qihaishu", name: "气海俞", pinyin: "qihaishu", code: "BL24", meridian: "足太阳膀胱经", location: "腰部,第3腰椎棘突下,旁开1.5寸", indications: "腰痛,痛经,痔疾,下肢痿痹", method: "直刺0.8-1.2寸", special: "", caution: "", mnemonic: "气海俞壮腰", mnemonicExplanation: "气海俞善治腰痛与经带病", level: "二类", sortOrder: 194 },
  { id: "a_baihuanshu", name: "白环俞", pinyin: "baihuanshu", code: "BL30", meridian: "足太阳膀胱经", location: "骶区,横平第4骶后孔,骶正中嵴旁开1.5寸", indications: "腰骶痛,遗精,遗尿,月经不调,带下", method: "直刺0.8-1.2寸", special: "", caution: "", mnemonic: "白环俞固精", mnemonicExplanation: "白环俞善治遗精带下", level: "二类", sortOrder: 195 },
  { id: "a_ciliao", name: "次髎", pinyin: "ciliao", code: "BL32", meridian: "足太阳膀胱经", location: "骶区,正对第2骶后孔中", indications: "腰骶痛,月经不调,痛经,带下,小便不利,遗精", method: "直刺1-1.5寸", special: "", caution: "", mnemonic: "次髎妇科要穴", mnemonicExplanation: "次髎为治痛经带下要穴", level: "二类", sortOrder: 196 },
  { id: "a_weiyang", name: "委阳", pinyin: "weiyang", code: "BL39", meridian: "足太阳膀胱经", location: "膝部,腘横纹外侧端,股二头肌腱内侧缘", indications: "小便不利,腹满水肿,腰背痛,下肢痿痹", method: "直刺1-1.5寸", special: "三焦下合穴", caution: "", mnemonic: "委阳利水通淋", mnemonicExplanation: "委阳为三焦下合穴,善利水道", level: "二类", sortOrder: 197 },
  { id: "a_heyang", name: "合阳", pinyin: "heyang", code: "BL55", meridian: "足太阳膀胱经", location: "小腿后区,腘横纹下2寸,腓肠肌内、外侧头之间", indications: "腰脊强痛,下肢痿痹,疝气,崩漏", method: "直刺1-2寸", special: "", caution: "", mnemonic: "合阳强腰止痛", mnemonicExplanation: "合阳善治腰脊痛与崩漏", level: "二类", sortOrder: 198 },
  { id: "a_chengjin", name: "承筋", pinyin: "chengjin", code: "BL56", meridian: "足太阳膀胱经", location: "小腿后区,腘横纹下5寸,腓肠肌两肌腹之间", indications: "小腿转筋,腰腿痛,痔疾,便秘", method: "直刺1-1.5寸", special: "", caution: "", mnemonic: "承筋舒筋治转筋", mnemonicExplanation: "承筋善治小腿转筋", level: "二类", sortOrder: 199 },
  { id: "a_fuyang", name: "跗阳", pinyin: "fuyang", code: "BL59", meridian: "足太阳膀胱经", location: "小腿后区,昆仑直上3寸,腓骨与跟腱之间", indications: "头重头痛,腰骶痛,外踝肿痛,下肢痿痹", method: "直刺0.8-1.2寸", special: "阳跷脉郄穴", caution: "", mnemonic: "跗阳通络止痛", mnemonicExplanation: "跗阳为阳跷脉郄穴,善治头腰踝痛", level: "二类", sortOrder: 200 },
  { id: "a_pushen", name: "仆参", pinyin: "pushen", code: "BL61", meridian: "足太阳膀胱经", location: "跟区,昆仑直下,跟骨外侧赤白肉际处", indications: "下肢痿痹,足跟痛,癫痫,脚气", method: "直刺0.3-0.5寸", special: "", caution: "", mnemonic: "仆参治足跟痛", mnemonicExplanation: "仆参善治足跟痛", level: "二类", sortOrder: 201 },
  { id: "a_shugu", name: "束骨", pinyin: "shugu", code: "BL65", meridian: "足太阳膀胱经", location: "跖区,第5跖趾关节的近端,赤白肉际处", indications: "头痛,项强,目眩,腰腿痛,癫狂", method: "直刺0.3-0.5寸", special: "输穴", caution: "", mnemonic: "束骨清头通络", mnemonicExplanation: "束骨善治头项腰腿痛", level: "二类", sortOrder: 202 },
  { id: "a_zutonggu", name: "足通谷", pinyin: "zutonggu", code: "BL66", meridian: "足太阳膀胱经", location: "足趾,第5跖趾关节的远端,赤白肉际处", indications: "头痛,项强,目眩,鼻衄,癫狂", method: "直刺0.2-0.3寸", special: "荥穴", caution: "", mnemonic: "通谷清头止衄", mnemonicExplanation: "足通谷为膀胱经荥穴,善清头热", level: "二类", sortOrder: 203 },
  { id: "a_shuiquan", name: "水泉", pinyin: "shuiquan", code: "KI5", meridian: "足少阴肾经", location: "跟区,太溪直下1寸,跟骨结节内侧凹陷处", indications: "月经不调,痛经,经闭,小便不利,足跟痛", method: "直刺0.3-0.5寸", special: "郄穴", caution: "", mnemonic: "水泉调经止痛", mnemonicExplanation: "水泉为肾经郄穴,善治妇科血证", level: "二类", sortOrder: 204 },
  { id: "a_henggu", name: "横骨", pinyin: "henggu", code: "KI11", meridian: "足少阴肾经", location: "下腹部,脐中下5寸,前正中线旁开0.5寸", indications: "少腹胀痛,遗精,阳痿,遗尿,疝气", method: "直刺0.8-1.2寸", special: "", caution: "针刺前排尿", mnemonic: "横骨固精缩尿", mnemonicExplanation: "横骨善治遗精遗尿", level: "二类", sortOrder: 205 },
  { id: "a_dahe", name: "大赫", pinyin: "dahe", code: "KI12", meridian: "足少阴肾经", location: "下腹部,脐中下4寸,前正中线旁开0.5寸", indications: "遗精,阳痿,阴挺,带下,月经不调,小腹痛", method: "直刺0.8-1.2寸", special: "", caution: "", mnemonic: "大赫补肾固精", mnemonicExplanation: "大赫善治遗精阳痿带下", level: "二类", sortOrder: 206 },
  { id: "a_qixue", name: "气穴", pinyin: "qixue", code: "KI13", meridian: "足少阴肾经", location: "下腹部,脐中下3寸,前正中线旁开0.5寸", indications: "月经不调,痛经,带下,遗精,阳痿,腹泻", method: "直刺0.8-1.2寸", special: "", caution: "", mnemonic: "气穴调经固精", mnemonicExplanation: "气穴善治月经不调与遗精", level: "二类", sortOrder: 207 },
  { id: "a_siman", name: "四满", pinyin: "siman", code: "KI14", meridian: "足少阴肾经", location: "下腹部,脐中下2寸,前正中线旁开0.5寸", indications: "月经不调,痛经,带下,遗精,小腹痛,便秘", method: "直刺0.8-1.2寸", special: "", caution: "", mnemonic: "四满调经止痛", mnemonicExplanation: "四满善治妇科诸疾", level: "二类", sortOrder: 208 },
  { id: "a_huangshu", name: "肓俞", pinyin: "huangshu", code: "KI16", meridian: "足少阴肾经", location: "腹部,脐中旁开0.5寸", indications: "腹痛绕脐,呕吐,泄泻,便秘,疝气", method: "直刺0.8-1.2寸", special: "", caution: "", mnemonic: "肓俞调肠止泻", mnemonicExplanation: "肓俞善治绕脐腹痛", level: "二类", sortOrder: 209 },
  { id: "a_youmen", name: "幽门", pinyin: "youmen", code: "KI21", meridian: "足少阴肾经", location: "上腹部,脐中上6寸,前正中线旁开0.5寸", indications: "腹痛,呕吐,腹胀,泄泻,消化不良", method: "直刺0.5-0.8寸", special: "", caution: "", mnemonic: "幽门和胃降逆", mnemonicExplanation: "幽门善治胃痛呕吐", level: "二类", sortOrder: 210 },
  { id: "a_bulang", name: "步廊", pinyin: "bulang", code: "KI22", meridian: "足少阴肾经", location: "胸部,第5肋间隙,前正中线旁开2寸", indications: "胸痛,咳嗽,气喘,乳痈,呕吐", method: "斜刺或平刺0.5-0.8寸", special: "", caution: "不可深刺", mnemonic: "步廊宽胸止咳", mnemonicExplanation: "步廊善治胸痛咳喘", level: "二类", sortOrder: 211 },
  { id: "a_shenfeng", name: "神封", pinyin: "shenfeng", code: "KI23", meridian: "足少阴肾经", location: "胸部,第4肋间隙,前正中线旁开2寸", indications: "咳嗽,气喘,胸胁胀满,呕吐,乳痈", method: "斜刺或平刺0.5-0.8寸", special: "", caution: "不可深刺", mnemonic: "神封宽胸理气", mnemonicExplanation: "神封善治胸胁胀满", level: "二类", sortOrder: 212 },
  { id: "a_jianshi", name: "间使", pinyin: "jianshi", code: "PC5", meridian: "手厥阴心包经", location: "前臂前区,腕掌侧远端横纹上3寸,掌长肌腱与桡侧腕屈肌腱之间", indications: "心痛,心悸,胃痛,呕吐,热病,疟疾,癫狂痫", method: "直刺0.5-1寸", special: "经穴", caution: "", mnemonic: "间使宁心止疟", mnemonicExplanation: "间使为心包经经穴,善治疟疾与心痛", level: "二类", sortOrder: 213 },
  { id: "a_yemen", name: "液门", pinyin: "yemen", code: "TE2", meridian: "手少阳三焦经", location: "手背,第4、5指间,指蹼缘后方赤白肉际处", indications: "头痛,目赤,耳聋,咽喉肿痛,疟疾,手臂痛", method: "直刺0.3-0.5寸", special: "荥穴", caution: "", mnemonic: "液门清热利咽", mnemonicExplanation: "液门为三焦经荥穴,善清热利咽", level: "二类", sortOrder: 214 },
  { id: "a_huizong", name: "会宗", pinyin: "huizong", code: "TE7", meridian: "手少阳三焦经", location: "前臂后区,腕背侧远端横纹上3寸,尺骨的桡侧缘", indications: "耳聋,耳鸣,癫痫,上肢痹痛", method: "直刺0.5-1寸", special: "郄穴", caution: "", mnemonic: "会宗聪耳定痫", mnemonicExplanation: "会宗为三焦经郄穴,善治耳聋癫痫", level: "二类", sortOrder: 215 },
  { id: "a_sanyangluo", name: "三阳络", pinyin: "sanyangluo", code: "TE8", meridian: "手少阳三焦经", location: "前臂后区,腕背侧远端横纹上4寸,尺骨与桡骨间隙中点", indications: "暴喑,耳聋,齿痛,上肢痹痛", method: "直刺0.8-1.2寸", special: "", caution: "", mnemonic: "三阳络开音", mnemonicExplanation: "三阳络善治暴喑耳聋", level: "二类", sortOrder: 216 },
  { id: "a_sidu", name: "四渎", pinyin: "sidu", code: "TE9", meridian: "手少阳三焦经", location: "前臂后区,肘尖下5寸,尺骨与桡骨间隙中点", indications: "耳聋,齿痛,咽喉肿痛,暴喑,上肢痹痛", method: "直刺0.8-1.2寸", special: "", caution: "", mnemonic: "四渎利咽通络", mnemonicExplanation: "四渎善治咽喉病与上肢痹痛", level: "二类", sortOrder: 217 },
  { id: "a_qinglengyuan", name: "清冷渊", pinyin: "qinglengyuan", code: "TE11", meridian: "手少阳三焦经", location: "臂后区,肘尖与肩峰角连线上,肘尖上2寸", indications: "头痛,目黄,肩臂痛,瘰疬", method: "直刺0.8-1.2寸", special: "", caution: "", mnemonic: "清冷渊散寒痛", mnemonicExplanation: "清冷渊善治肩臂痛与头痛", level: "二类", sortOrder: 218 },
  { id: "a_jianliao", name: "肩髎", pinyin: "jianliao", code: "TE14", meridian: "手少阳三焦经", location: "肩胛区,肩峰角与肱骨大结节两骨间凹陷中", indications: "肩臂挛痛,上肢不遂,肩周炎", method: "直刺1-1.5寸", special: "", caution: "", mnemonic: "肩髎治肩凝", mnemonicExplanation: "肩髎善治肩周炎与肩臂痛", level: "二类", sortOrder: 219 },
  { id: "a_luxi", name: "颅息", pinyin: "luxi", code: "TE19", meridian: "手少阳三焦经", location: "头部,角孙至翳风之间,沿耳轮连线的上、中1/3交点处", indications: "头痛,耳鸣,耳聋,小儿惊风,呕吐涎沫", method: "平刺0.3-0.5寸", special: "", caution: "", mnemonic: "颅息聪耳定惊", mnemonicExplanation: "颅息善治耳鸣与小儿惊风", level: "二类", sortOrder: 220 },
  { id: "a_ermen", name: "耳门", pinyin: "ermen", code: "TE21", meridian: "手少阳三焦经", location: "耳区,耳屏上切迹与下颌骨髁突之间的凹陷中", indications: "耳鸣,耳聋,聤耳,齿痛,颔肿", method: "张口,直刺0.3-0.5寸", special: "", caution: "", mnemonic: "耳门聪耳要穴", mnemonicExplanation: "耳门为治耳鸣耳聋要穴", level: "二类", sortOrder: 221 },
  { id: "a_shangguan", name: "上关", pinyin: "shangguan", code: "GB3", meridian: "足少阳胆经", location: "面部,颧弓上缘中央凹陷处", indications: "偏头痛,耳鸣,耳聋,齿痛,口眼歪斜", method: "直刺0.3-0.5寸", special: "", caution: "", mnemonic: "上关聪耳止痛", mnemonicExplanation: "上关善治偏头痛与耳病", level: "二类", sortOrder: 222 },
  { id: "a_hanyan", name: "颔厌", pinyin: "hanyan", code: "GB4", meridian: "足少阳胆经", location: "头部,头维与曲鬓弧形连线的上1/4与下3/4交点处", indications: "偏头痛,眩晕,目外眦痛,耳鸣,癫痫", method: "平刺0.3-0.5寸", special: "", caution: "", mnemonic: "颔厌止偏头痛", mnemonicExplanation: "颔厌善治偏头痛眩晕", level: "二类", sortOrder: 223 },
  { id: "a_xuanli", name: "悬厘", pinyin: "xuanli", code: "GB6", meridian: "足少阳胆经", location: "头部,头维与曲鬓弧形连线的上3/4与下1/4交点处", indications: "偏头痛,面肿,目外眦痛,耳鸣,癫痫", method: "平刺0.3-0.5寸", special: "", caution: "", mnemonic: "悬厘清头止痛", mnemonicExplanation: "悬厘善治偏头痛面肿", level: "二类", sortOrder: 224 },
  { id: "a_qubin", name: "曲鬓", pinyin: "qubin", code: "GB7", meridian: "足少阳胆经", location: "头部,耳前鬓角发际后缘与耳尖水平线的交点处", indications: "偏头痛,齿痛,口眼歪斜,暴喑,牙关紧闭", method: "平刺0.3-0.5寸", special: "", caution: "", mnemonic: "曲鬓通络止痛", mnemonicExplanation: "曲鬓善治偏头痛与面瘫", level: "二类", sortOrder: 225 },
  { id: "a_wangu2", name: "完骨", pinyin: "wangu2", code: "GB12", meridian: "足少阳胆经", location: "头部,耳后乳突的后下方凹陷处", indications: "头痛,颈项强痛,齿痛,口歪,失眠,癫痫", method: "斜刺0.5-0.8寸", special: "", caution: "", mnemonic: "完骨祛风安神", mnemonicExplanation: "完骨善治头项痛与失眠", level: "二类", sortOrder: 226 },
  { id: "a_benshen", name: "本神", pinyin: "benshen", code: "GB13", meridian: "足少阳胆经", location: "头部,前发际上0.5寸,头正中线旁开3寸", indications: "头痛,目眩,癫痫,小儿惊风,中风昏迷", method: "平刺0.3-0.5寸", special: "", caution: "", mnemonic: "本神定惊安神", mnemonicExplanation: "本神善治癫痫与头痛", level: "二类", sortOrder: 227 },
  { id: "a_naokong", name: "脑空", pinyin: "naokong", code: "GB19", meridian: "足少阳胆经", location: "枕区,枕外隆凸上缘外侧,头正中线旁开2.25寸", indications: "头痛,眩晕,项强,目痛,癫痫,鼻渊", method: "平刺0.3-0.5寸", special: "", caution: "", mnemonic: "脑空清头通窍", mnemonicExplanation: "脑空善治头痛眩晕鼻渊", level: "二类", sortOrder: 228 },
  { id: "a_riyue", name: "日月", pinyin: "riyue", code: "GB24", meridian: "足少阳胆经", location: "胸部,第7肋间隙,前正中线旁开4寸", indications: "胁肋疼痛,黄疸,呕吐,吞酸,呃逆", method: "斜刺或平刺0.5-0.8寸", special: "胆募穴", caution: "不可深刺", mnemonic: "日月利胆退黄", mnemonicExplanation: "日月为胆募穴,善治胆病黄疸", level: "二类", sortOrder: 229 },
  { id: "a_jingmen", name: "京门", pinyin: "jingmen", code: "GB25", meridian: "足少阳胆经", location: "侧腹部,第12肋骨游离端的下际", indications: "胁痛,腹胀,腰痛,小便不利,水肿", method: "斜刺0.5-1寸", special: "肾募穴", caution: "不可深刺", mnemonic: "京门益肾利水", mnemonicExplanation: "京门为肾募穴,善治胁腹胀痛", level: "二类", sortOrder: 230 },
  { id: "a_daimai", name: "带脉", pinyin: "daimai", code: "GB26", meridian: "足少阳胆经", location: "侧腹部,第11肋骨游离端垂线与脐水平线的交点上", indications: "带下,月经不调,经闭,疝气,腰胁痛", method: "直刺1-1.5寸", special: "", caution: "", mnemonic: "带脉止带调经", mnemonicExplanation: "带脉善治带下与月经不调", level: "二类", sortOrder: 231 },
  { id: "a_weidao", name: "维道", pinyin: "weidao", code: "GB28", meridian: "足少阳胆经", location: "下腹部,髂前上棘前下方,五枢前下0.5寸", indications: "少腹痛,带下,阴挺,疝气,月经不调", method: "直刺1-1.5寸", special: "", caution: "", mnemonic: "维道固带升提", mnemonicExplanation: "维道善治带下阴挺", level: "二类", sortOrder: 232 },
  { id: "a_juliao2", name: "居髎", pinyin: "juliao2", code: "GB29", meridian: "足少阳胆经", location: "臀区,髂前上棘与股骨大转子最凸点连线的中点处", indications: "腰腿痹痛,下肢痿痹,疝气", method: "直刺1.5-2寸", special: "", caution: "", mnemonic: "居髎通络治痹", mnemonicExplanation: "居髎善治腰胯腿痛", level: "二类", sortOrder: 233 },
  { id: "a_zhongdu2", name: "中渎", pinyin: "zhongdu2", code: "GB32", meridian: "足少阳胆经", location: "大腿外侧,腘横纹上5寸,髂胫束后缘", indications: "下肢痿痹,麻木,半身不遂", method: "直刺1-1.5寸", special: "", caution: "", mnemonic: "中渎通络治痿", mnemonicExplanation: "中渎善治下肢痿痹", level: "二类", sortOrder: 234 },
  { id: "a_xiyangguan", name: "膝阳关", pinyin: "xiyangguan", code: "GB33", meridian: "足少阳胆经", location: "膝外侧,阳陵泉上3寸,股骨外上髁上方的凹陷处", indications: "膝膑肿痛,腘筋挛急,小腿麻木", method: "直刺1-1.5寸", special: "", caution: "", mnemonic: "膝阳关治膝痛", mnemonicExplanation: "膝阳关善治膝关节痛", level: "二类", sortOrder: 235 },
  { id: "a_yangfu", name: "阳辅", pinyin: "yangfu", code: "GB38", meridian: "足少阳胆经", location: "小腿外侧,外踝尖上4寸,腓骨前缘", indications: "偏头痛,目外眦痛,咽喉肿痛,腋下肿痛,下肢痿痹", method: "直刺0.8-1.2寸", special: "经穴", caution: "", mnemonic: "阳辅清胆通络", mnemonicExplanation: "阳辅为胆经经穴,善治偏头痛与下肢痹痛", level: "二类", sortOrder: 236 },
  { id: "a_diwuhui", name: "地五会", pinyin: "diwuhui", code: "GB42", meridian: "足少阳胆经", location: "足背,第4、5跖骨间,第4跖趾关节近端凹陷处", indications: "头痛,目赤,耳鸣,胁痛,乳痈,足背肿痛", method: "直刺0.3-0.5寸", special: "", caution: "", mnemonic: "地五会清胆", mnemonicExplanation: "地五会善治头目胁乳诸疾", level: "二类", sortOrder: 237 },
  { id: "a_xiaxi", name: "侠溪", pinyin: "xiaxi", code: "GB43", meridian: "足少阳胆经", location: "足背,第4、5趾间,趾蹼缘后方赤白肉际处", indications: "头痛,眩晕,耳鸣,耳聋,目赤肿痛,胁痛,乳痈", method: "直刺0.3-0.5寸", special: "荥穴", caution: "", mnemonic: "侠溪清肝利胆", mnemonicExplanation: "侠溪为胆经荥穴,善清肝胆热", level: "二类", sortOrder: 238 },
  { id: "a_zhongfeng", name: "中封", pinyin: "zhongfeng", code: "LR4", meridian: "足厥阴肝经", location: "踝区,内踝前下方,胫骨前肌腱的内侧缘凹陷处", indications: "疝气,遗精,小便不利,腰痛,足踝痛", method: "直刺0.5-0.8寸", special: "经穴", caution: "", mnemonic: "中封疏肝通淋", mnemonicExplanation: "中封为肝经经穴,善治疝气遗精", level: "二类", sortOrder: 239 },
  { id: "a_xiguan", name: "膝关", pinyin: "xiguan", code: "LR7", meridian: "足厥阴肝经", location: "膝部,胫骨内侧髁的下方,阴陵泉后1寸", indications: "膝膑肿痛,下肢痿痹,咽喉肿痛", method: "直刺0.8-1寸", special: "", caution: "", mnemonic: "膝关治膝肿痛", mnemonicExplanation: "膝关善治膝关节肿痛", level: "二类", sortOrder: 240 },
  { id: "a_yinbao", name: "阴包", pinyin: "yinbao", code: "LR9", meridian: "足厥阴肝经", location: "股前区,髌底上4寸,股薄肌与缝匠肌之间", indications: "月经不调,遗尿,小便不利,腰骶痛引少腹", method: "直刺0.8-1.2寸", special: "", caution: "", mnemonic: "阴包调经缩尿", mnemonicExplanation: "阴包善治妇科与小便病", level: "二类", sortOrder: 241 },
  { id: "a_zhangmen", name: "章门", pinyin: "zhangmen", code: "LR13", meridian: "足厥阴肝经", location: "侧腹部,第11肋游离端的下际", indications: "腹胀,泄泻,胁痛,痞块,黄疸", method: "斜刺0.5-0.8寸", special: "脾募穴;脏会", caution: "不可深刺", mnemonic: "章门脏会健脾", mnemonicExplanation: "章门为脾募、脏会,善健脾消痞", level: "二类", sortOrder: 242 },
  { id: "a_shangxing", name: "上星", pinyin: "shangxing", code: "GV23", meridian: "督脉", location: "头部,前发际正中直上1寸", indications: "头痛,目痛,鼻渊,鼻衄,癫狂,疟疾", method: "平刺0.5-0.8寸", special: "", caution: "", mnemonic: "上星通窍止血", mnemonicExplanation: "上星善治鼻渊鼻衄与头痛", level: "二类", sortOrder: 243 },
  { id: "a_suliao", name: "素髎", pinyin: "suliao", code: "GV25", meridian: "督脉", location: "面部,鼻尖的正中央", indications: "昏迷,昏厥,鼻塞,鼻衄,鼻渊,喘息", method: "向上斜刺0.3-0.5寸", special: "", caution: "", mnemonic: "素髎急救开窍", mnemonicExplanation: "素髎为急救要穴,善开窍醒神", level: "二类", sortOrder: 244 },
  { id: "a_duiduan", name: "兑端", pinyin: "duiduan", code: "GV27", meridian: "督脉", location: "面部,上唇结节的中点", indications: "口歪,齿龈肿痛,鼻衄,癫狂,昏迷", method: "向上斜刺0.2-0.3寸", special: "", caution: "", mnemonic: "兑端开窍止痛", mnemonicExplanation: "兑端善治口歪与癫狂", level: "二类", sortOrder: 245 },
  { id: "a_yinjiao2", name: "龈交", pinyin: "yinjiao2", code: "GV28", meridian: "督脉", location: "上唇内,上唇系带与上齿龈的交点处", indications: "齿龈肿痛,口歪,口臭,鼻渊,癫狂", method: "向上斜刺0.2-0.3寸", special: "", caution: "", mnemonic: "龈交消肿止痛", mnemonicExplanation: "龈交善治齿龈肿痛", level: "二类", sortOrder: 246 },
  { id: "a_xuanshu", name: "悬枢", pinyin: "xuanshu", code: "GV5", meridian: "督脉", location: "腰部,第1腰椎棘突下凹陷中", indications: "腰脊强痛,腹胀,泄泻,痢疾", method: "直刺0.5-1寸", special: "", caution: "", mnemonic: "悬枢壮腰止泻", mnemonicExplanation: "悬枢善治腰脊痛与泄泻", level: "二类", sortOrder: 247 },
  { id: "a_jizhong", name: "脊中", pinyin: "jizhong", code: "GV6", meridian: "督脉", location: "背部,第11胸椎棘突下凹陷中", indications: "腰脊强痛,泄泻,黄疸,癫痫,痔疾", method: "向上斜刺0.5-1寸", special: "", caution: "", mnemonic: "脊中健脾止泻", mnemonicExplanation: "脊中善治腰脊痛与泄泻", level: "二类", sortOrder: 248 },
  { id: "a_jinsuo", name: "筋缩", pinyin: "jinsuo", code: "GV8", meridian: "督脉", location: "背部,第9胸椎棘突下凹陷中", indications: "脊背强痛,癫痫,抽搐,胃痛,黄疸", method: "向上斜刺0.5-1寸", special: "", caution: "", mnemonic: "筋缩止痉定痫", mnemonicExplanation: "筋缩善治痉挛抽搐", level: "二类", sortOrder: 249 },
  { id: "a_lingtai", name: "灵台", pinyin: "lingtai", code: "GV10", meridian: "督脉", location: "背部,第6胸椎棘突下凹陷中", indications: "咳嗽,气喘,疔疮,脊背强痛", method: "向上斜刺0.5-1寸", special: "", caution: "", mnemonic: "灵台治疔止咳", mnemonicExplanation: "灵台善治疔疮与咳喘", level: "二类", sortOrder: 250 },
  { id: "a_taodao", name: "陶道", pinyin: "taodao", code: "GV13", meridian: "督脉", location: "背部,第1胸椎棘突下凹陷中", indications: "热病,疟疾,头痛,项强,脊背酸痛,癫痫", method: "向上斜刺0.5-1寸", special: "", caution: "", mnemonic: "陶道退热截疟", mnemonicExplanation: "陶道善治热病疟疾", level: "二类", sortOrder: 251 },
  { id: "a_huiyin", name: "会阴", pinyin: "huiyin", code: "CV1", meridian: "任脉", location: "会阴区,男性在阴囊根部与肛门连线的中点,女性在大阴唇后联合与肛门连线的中点", indications: "溺水窒息,昏迷,癫狂,遗精,遗尿,阴痛,月经不调", method: "直刺0.5-1寸", special: "任脉与督脉冲脉交会穴", caution: "急救时强刺激", mnemonic: "会阴急救醒神", mnemonicExplanation: "会阴为急救要穴,善醒神苏厥", level: "二类", sortOrder: 252 },
  { id: "a_shuifen", name: "水分", pinyin: "shuifen", code: "CV9", meridian: "任脉", location: "上腹部,前正中线上,脐中上1寸", indications: "水肿,小便不利,腹痛,泄泻,腹水", method: "直刺1-1.5寸", special: "", caution: "", mnemonic: "水分利水消肿", mnemonicExplanation: "水分善利水,为治水肿要穴", level: "二类", sortOrder: 253 },
  { id: "a_xiawan", name: "下脘", pinyin: "xiawan", code: "CV10", meridian: "任脉", location: "上腹部,前正中线上,脐中上2寸", indications: "腹痛,腹胀,呕吐,食谷不化,泄泻,痞块", method: "直刺1-1.5寸", special: "任脉与足太阴经交会穴", caution: "", mnemonic: "下脘健脾和胃", mnemonicExplanation: "下脘善治脾胃虚弱", level: "二类", sortOrder: 254 },
  { id: "a_jianli", name: "建里", pinyin: "jianli", code: "CV11", meridian: "任脉", location: "上腹部,前正中线上,脐中上3寸", indications: "胃痛,呕吐,食欲不振,腹胀,水肿", method: "直刺1-1.5寸", special: "", caution: "", mnemonic: "建里和胃消食", mnemonicExplanation: "建里善治胃脘胀痛", level: "二类", sortOrder: 255 },
  { id: "a_juewei", name: "巨阙", pinyin: "juewei", code: "CV14", meridian: "任脉", location: "上腹部,前正中线上,脐中上6寸", indications: "心痛,心悸,癫狂痫,呕吐,吞酸,黄疸", method: "向下斜刺0.5-1寸", special: "心募穴", caution: "不可深刺,防伤肝脏", mnemonic: "巨阙宁心定悸", mnemonicExplanation: "巨阙为心募穴,善治心悸心痛", level: "二类", sortOrder: 256 },
  { id: "a_jiuwei", name: "鸠尾", pinyin: "jiuwei", code: "CV15", meridian: "任脉", location: "上腹部,前正中线上,剑胸结合部下1寸", indications: "心痛,心悸,癫狂痫,呕吐,呃逆", method: "向下斜刺0.5-1寸", special: "任脉络穴;膏之原", caution: "不可深刺", mnemonic: "鸠尾定痫宁心", mnemonicExplanation: "鸠尾善治癫狂痫与心痛", level: "二类", sortOrder: 257 },
  { id: "a_lianquan", name: "廉泉", pinyin: "lianquan", code: "CV23", meridian: "任脉", location: "颈前区,喉结上方,舌骨上缘凹陷处", indications: "舌下肿痛,舌缓流涎,舌强不语,暴喑,吞咽困难", method: "向舌根方向斜刺0.5-0.8寸", special: "", caution: "", mnemonic: "廉泉开音利舌", mnemonicExplanation: "廉泉善治舌强不语与暴喑", level: "二类", sortOrder: 258 },
  { id: "a_chengjiang", name: "承浆", pinyin: "chengjiang", code: "CV24", meridian: "任脉", location: "面部,颏唇沟的正中凹陷处", indications: "口歪,齿龈肿痛,流涎,暴喑,癫狂", method: "斜刺0.3-0.5寸", special: "", caution: "", mnemonic: "承浆通络止痛", mnemonicExplanation: "承浆善治口歪流涎与齿痛", level: "二类", sortOrder: 259 },
];

async function main() {
  // 1. 建经络(幂等:name 唯一)
  const meridianIdMap = new Map<string, number>();
  for (const m of MERIDIANS) {
    const existing = await db.meridian.findUnique({ where: { name: m.name } });
    if (existing) {
      meridianIdMap.set(m.name, existing.id);
      continue;
    }
    const created = await db.meridian.create({
      data: { name: m.name, code: m.code, sortOrder: m.sortOrder, description: "" },
    });
    meridianIdMap.set(m.name, created.id);
  }
  console.log(`✅ 经络就绪(${meridianIdMap.size} 条)`);

  // 2. 插入穴位(幂等:code 唯一跳过)
  let inserted = 0;
  let skipped = 0;
  for (const p of SEED_ACUPOINTS) {
    const meridianId = meridianIdMap.get(p.meridian);
    if (!meridianId) throw new Error(`经络缺失: ${p.meridian}`);
    const existing = await db.acupoint.findUnique({ where: { code: p.code } });
    if (existing) {
      skipped++;
      continue;
    }
    await db.acupoint.create({
      data: {
        id: p.id,
        name: p.name,
        pinyin: p.pinyin,
        code: p.code,
        meridianId,
        location: p.location,
        indications: p.indications,
        method: p.method,
        special: p.special,
        caution: p.caution,
        mnemonic: p.mnemonic,
        mnemonicExplanation: p.mnemonicExplanation,
        level: p.level,
        sortOrder: p.sortOrder,
      },
    });
    inserted++;
  }
  console.log(`✅ 腧穴种子完成:新增 ${inserted} 穴,跳过 ${skipped} 穴(已存在)`);

  const total = await db.acupoint.count();
  console.log(`📊 生产库当前腧穴总数: ${total} 穴`);
}

main()
  .catch((e) => {
    console.error("❌ 种子失败:", e);
    process.exit(1);
  })
  .finally(() => db.$disconnect());
